### ISSUE TITLE
最新版的eclipse64位的，扫描后eclipse一直在做些啥，卡的死

### ISSUE THREAD

**Issue by jiaxuan0701** [alibaba/p3c#102]
如题，其他版本的没发现这问题

**Comment by jackyrong** [comment]
我也发现了，只开ECLIPSE MARS也是这样！然后打开每个扫描后的结果，都是光标在转

**Comment by jiaxuan0701** [comment]
eclipse4.7.1卸载了jpt扫描后，一直是扫描状态，但是事实上问题也不增加了，就是eclipse假死

**Comment by chenkuifang** [comment]
我的也是啊，怎么破？

**Comment by chenkuifang** [comment]
发现只要不要针对整个项目扫描就不卡，可以针对某个包，某个类进行扫描，修改好后clear markers 就行了

**Comment by xusheng1987** [comment]
我也是卡，卸载jpa插件也没用

**Comment by jiaxuan0701** [comment]
只能按 @chenkuifang 说的，不整个项目扫描咯，看后续版本修复
