### ISSUE TITLE
[Suggestion] Eclipse插件 Rules设定 和 配置页面UI优化的建议

### ISSUE THREAD

**Issue by reJaHiGr** [alibaba/p3c#103]
环境 ： Eclipse 4.4 ，  JDK 1.7

（1）规则设定的建议：
    现在Preference的 Alibaba Code Analysis配置页面只能查看规则，其实可以做个增加、删除的功能，增加的话只能增加Alibaba定义好的Rules，而删除呢，则是可以删除其中的这些rules. 这样的话，就可以适当的做一些规则的设定。因为可能有些规则可能特定的场合下不需要。

（2）配置页面的建议：
    在Preference的 Alibaba Code Analysis 配置页面中，这个composite的展示有待完善啊：1.整个页面全部被占满了；2：在放大缩小整个窗口时，左侧的rules和右侧的details的composite size都没改变。建议做的稍稍自适应些会更好。

之前做过一段时间的插件开发，稍稍了解一点，期望可以看到更好用户体现的配置页面。

**Comment by mfkvfn** [comment]
第一个功能很有用。我也需要可配置，能关闭某些检查，比如“缺少@Override”，或者检查也行，不要弄到Blocker级别。

第二个功能，我原来以为只有rules。经你一说，我才发现右边有details。建议改成上下panel。上面list，下面detail。可以改变上下panel的高度。

**Comment by xuantan** [comment]
非常欢迎加入我们，一起贡献代码。
