### ISSUE TITLE
清理无用代码的提示位置不准确... 建议优化

### ISSUE THREAD

**Issue by joker-fu** [alibaba/p3c#104]
//                    @Override
//                    public void onSubscribe(Disposable d) {
//                        System.out.println("====Observer: " + d.toString());
//                    }

                    @Override
                    public void onNext(String value) {
                        System.out.println("====onNext: " + value);
                    }

这样的话提示不在注释代码的位置，而是在下面未注释代码位置

**Comment by ITDreamSKY** [comment]
<img width="472" alt="default" src="https://user-images.githubusercontent.com/22219146/31752872-ddd94708-b4bf-11e7-8ce1-7f0be3d3c09e.png">

**Comment by xuantan** [comment]
@kerie 具体看下
