### ISSUE TITLE
[Enhancement] Rules中的example格式没有follow规范

### ISSUE THREAD

**Issue by reJaHiGr** [alibaba/p3c#107]
Fork了项目，阅读了代码，发现resources中的rulesets给出的example没有参考规范来写。

比如说，
1. 代码行中需要空格的地方没有按照guideline来写 ，if （a = b） {  } 
2. equals的用法，  “true”.equals(key)  
3. 中英文没有统一，  ali-oop.xml中 使用的正反例（中文描述），其他文件使用英文（Negative、Positive）；
4. ali-concurrent.xml 中 没有规范使用，换行的使用，第二行开始缩进4个空格

**Comment by SeanCai** [comment]
@reJaHiGr 谢谢反馈，我们这边会处理掉
