### ISSUE TITLE
第9页 (五)集合处理 第4条规范描述不够精确

### ISSUE THREAD

**Issue by Pengfei-Lu** [alibaba/p3c#11]
![default](https://user-images.githubusercontent.com/7485400/31380964-991573de-ade5-11e7-9fc2-37efc6575a12.png)

如图，“**下标为[ list.size() ]的数组元素将被置为 null**”，该描述不够精确。

Java Doc中的描述为“**If the list fits in the specified array with room to spare (i.e., the array has more elements than the list), the element in the array immediately following the end of the list is set to null.)**”

修改为“**下标为从list.size()至数组末尾的全部元素将被置为 null**”是不是更合适些呢？

**Comment by huo920** [comment]
我也认为应该这样

**Comment by xuantan** [comment]
@yangguanbao 具体看下

**Comment by yangguanbao** [comment]
接受你的建议，我将进行修改，下一个版本会面世，感谢你对《阿里巴巴Java开发手册》的支持。
