### ISSUE TITLE
Inspection Results 右侧提示窗口中文乱码 

### ISSUE THREAD

**Issue by zhangqqqf** [alibaba/p3c#110]
目前有两个中文乱码的问题
1.  菜单乱码 
Appearance&Behavior -> Appearance -> UI Options -> Name 里面设置成支持中文的字体 例如微软雅黑
2. Inspection Results 右侧提示窗口中文乱码 
Editor -> Color & Fonts -> Font  Primary Font 设置一种支持中文的字体 例如微软雅黑
 如下图:
![](http://olryihear.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720171019165833.png)
这种中文显示不出来只能更改Editor的字体来支持中文显示, 真的是忍不了, 已经习惯了Consolas字体, 换个字体看着难受的不得了!!!!

**Comment by SeanCai** [comment]
非常欢迎加入进来解决这个问题 :-D
