### ISSUE TITLE
注释信息也会被提示清理

### ISSUE THREAD

**Issue by jayleco** [alibaba/p3c#112]
![tim 20171019171937](https://user-images.githubusercontent.com/9976349/31763758-d429e1a4-b4f1-11e7-8beb-e8f1a50fe6f3.png)

如上图

**Comment by xuantan** [comment]
@jayleco 完整代码麻烦再粘贴下

**Comment by jayleco** [comment]
@xuantan 我找到原因的，是因为插件定位行不准造成的，我在这段代码上方第96行有一行注释掉的代码，结果插件提醒到这里了，上面的注释掉的代码删掉这里就没有提示了
