### ISSUE TITLE
IntelliJ IDEA 中文在右侧鼠标悬停预览代码时显示为乱码方框

### ISSUE THREAD

**Issue by hfchanCN** [alibaba/p3c#114]
如图：
![chs_messy_code](https://user-images.githubusercontent.com/27403411/31765132-f57f8468-b4f5-11e7-9d12-aced61137775.png)

另外中文是不是开发组自己用拼音输入法打出来的呢，有些字需要校核哦，比如：
![pinyin_cw](https://user-images.githubusercontent.com/27403411/31765005-88d2aad4-b4f5-11e7-9ee9-09483edf5ea7.png)

PS：阿里真的做了一件大好事，感谢阿里程序猿做出的贡献！^_^

**Comment by SeanCai** [comment]
@hfchanCN https://github.com/alibaba/p3c/issues/32
