### ISSUE TITLE
IntelliJ IDEA 类属性字段javadoc注释提示，中间隔着@注解或空一行时不能提示

### ISSUE THREAD

**Issue by hfchanCN** [alibaba/p3c#115]
如图：
![anno](https://user-images.githubusercontent.com/27403411/31766213-89744ec6-b4f9-11e7-8289-661dec7915a9.png)

**Comment by xuantan** [comment]
@hfchanCN 此问题已确认是个bug，后续会修复掉

**Comment by xuantan** [comment]
代码已提交，插件版本本周会更新。
