### ISSUE TITLE
alibaba插件在eclipse Oxygen Release (4.7.0) 下与vrapper插件冲突

### ISSUE THREAD

**Issue by siriusckx** [alibaba/p3c#116]
1、下载vrapper插件vrapper_0.72.0_20170311，手动解压放到eclipse安装目录的dropins下。
2、后面安装alibaba插件后，vrapper插件不见了。
3、卸载alibaba插件后，vrapper插件又OK了。

**Comment by imu2008** [comment]
@siriusckx 在4.7上，vrapper插件同样使用updatesite方式安装即可。
