### ISSUE TITLE
Intellij 的 inspection results 窗口，部分扫描结果不能使用quick fix

### ISSUE THREAD

**Issue by pcyan** [alibaba/p3c#122]
比如“常量命名应该全部大写，单词间用下划线隔开，力求语义表达完整清楚，不要嫌名字长”这种情况

扫描完毕，在inspection results 窗口，不能在结果中批量`quick fix`，但是直接在常量上是可以`quick fix` 和`fix all in file`的。

**Comment by SeanCai** [comment]
@pcyan 这个涉及到跨文件引用，单个QuickFix只是提供一个快捷修改名字的操作，但可能会出现非预期的结果，所以并不适合批量修复
