### ISSUE TITLE
希望有maven插件，可以用maven命令执行检查，类似pmd

### ISSUE THREAD

**Issue by lusong1986** [alibaba/p3c#123]
希望有maven插件，可以用maven命令执行检查，类似pmd
mvn pmd:pmd

**Comment by jdkhome** [comment]
同求 gradle

**Comment by dryadx** [comment]
这个可以自己做，在maven pmd 插件中添加P3C的依赖，把规则放进ruleset。

**Comment by xuantan** [comment]
@smiler158 可以考虑提供个样例

**Comment by zengyoubin** [comment]
@xuantan 
![image](https://user-images.githubusercontent.com/18280912/32259661-f46eb1c2-be8f-11e7-8cd4-2baf72dd31a6.png)
