### ISSUE TITLE
'Date(int, int, int)' 已经过时了 然后打开提示的是URLDecoder ！？

### ISSUE THREAD

**Issue by my36z** [alibaba/p3c#128]
'Date(int, int, int)' 已经过时了 less... (Ctrl+F1) 
不能使用过时的类或方法。 说明：java.net.URLDecoder 中的方法decode(String encodeStr) 这个方法已经过时，应该使用双参数decode(String source, String encode)。接口提供方既然明确是过时接口，那么有义务同时提供新的接口；作为调用方来说，有义务去考证过时方法的新实现是什么。

**Comment by SeanCai** [comment]
@my36z 下面的是规则的说明，并不是你使用的过时类的说明
