### ISSUE TITLE
所以用这个插件还必须得用gradle？

### ISSUE THREAD

**Issue by youyinnn** [alibaba/p3c#13]
我只会用maven 很尴尬

**Comment by suncunhu** [comment]
阿里内部都是使用gradle吗？ 不使用maven了？

**Comment by jxgxldl** [comment]
maven也可以的，已经用上了，很赞。
<dependency>
       <groupId>com.alibaba.p3c.idea</groupId>
       <artifactId>p3c-common</artifactId>
       <version>1.0.0</version>
</dependency>

**Comment by xingguang2013** [comment]
@jxgxldl 是不是安装个插件就行，你这个依赖是做什么的？

**Comment by changdaye** [comment]
@xingguang2013 安装插件应该是配合jenkins在构建项目时扫描代码用的、

**Comment by xingguang2013** [comment]
@jxgxldl 好的 谢谢

**Comment by SeanCai** [comment]
@youyinnn IDE插件开发依赖管理都是由各自平台提供支持哈，比如Idea提供了 gradle-intellij-plugin 插件，Eclipse提供 tycho插件

**Comment by qiujiayu** [comment]
@SeanCai  在gradle中要如何使用？
