### ISSUE TITLE
关于：使用工具类Arrays.asList()把数组转换成集合时，不能使用其修改集合相关的方法，它的add/remove/clear方法会抛出UnsupportedOperationException异常。

### ISSUE THREAD

**Issue by Jessay** [alibaba/p3c#136]
![image](https://user-images.githubusercontent.com/25023163/31933218-22430094-b86e-11e7-9a99-81d1072e6503.png)

这种情况下不会抛出UnsupportedOperationException异常，但仍然会提示。

**Comment by xuantan** [comment]
@yangguanbao 看一下

**Comment by yangguanbao** [comment]
你这种方式完整是一个新的集合，与Arrays的集合没有任何关系。感谢你对阿里巴巴Java开发手册的支持。
