### ISSUE TITLE
期望新增一份代码格式公约，并且可以自定义化

### ISSUE THREAD

**Issue by ruanyi** [alibaba/p3c#137]
例如：类名头部格式，每一行的注释，每行有多少字符等等，并且在类创建的时候，能够自动加上。这些虽然，用idea、eclipse自己配置也能做到，但是，希望这样的功能，能够做到插件中去，能够保证大部分的代码格式是一致的
![image](https://user-images.githubusercontent.com/5568762/31951049-a83ff9fc-b8a2-11e7-9867-8908639247d7.png)

**Comment by xuantan** [comment]
见这里  https://github.com/alibaba/p3c/tree/master/p3c-formatter

**Comment by ruanyi** [comment]
点个赞！！不过，只有eclipse的？。。intellj通过eclipse formatter插件来实现？
