### ISSUE TITLE
白名单机制

### ISSUE THREAD

**Issue by weinierfei** [alibaba/p3c#139]
能不能有类似白名单的机制,比如"类名使用UpperCamelCase风格，必须遵从驼峰形式";如果要写一个二维码相关的,那就是"QRCode"呀?

**Comment by www1350** [comment]
https://github.com/alibaba/p3c/blob/43363bf402c50c4ade4e252030cbf524d28882a2/p3c-pmd/src/main/resources/namelist.properties

LowerCamelCaseVariableNamingRule_WHITE_LIST

**Comment by xuantan** [comment]
两条选择：
1、自己修改源码，在源码中有白名单机制，然后构建打包出自己的插件。
2、严格遵从开源插件扫描出的结果
