### ISSUE TITLE
希望加入忽略名单,功能类似.gitignore

### ISSUE THREAD

**Issue by xiaomoinfo** [alibaba/p3c#141]
痛点：
在使用protobuf的时候生成的java文件不符合规范，但是又不可能去修改。希望能够过滤掉这些代码文件。
![image](https://user-images.githubusercontent.com/12625278/31997858-0daa2718-b9c0-11e7-8e21-ae8cee7df24a.png)

**Comment by pkptzx** [comment]
https://github.com/alibaba/p3c/issues/15

使用右键单独扫描 或 在不想扫描的类上加 @generated

**Comment by xiaomoinfo** [comment]
@pkptzx  多谢
