### ISSUE TITLE
这个算不算bug

### ISSUE THREAD

**Issue by shuohao** [alibaba/p3c#142]
避免Random实例被多线程使用，虽然共享该实例是线程安全的，但会因竞争同一seed 导致的性能下降。**说明**：Random实例包括java.util.Random 的实例或者 Math.random()的方式。 **说明**：使用线程池的好处是减少在创建和销毁线程上所花的时间以及系统资源的开销，解决资源不足的问题。如果不使用线程池，有可能造成系统创建大量同类线程而导致消耗完内存或者“过度切换”的问题

跟着了两个说明

**Comment by yangguanbao** [comment]
并没有，在哪里？

**Comment by SeanCai** [comment]
@shuohao 没有发现这个问题，如果再次复现，请截图然后重新打开这个issue，thx
