### ISSUE TITLE
插件扫描时能否排除一些包?

### ISSUE THREAD

**Issue by pkptzx** [alibaba/p3c#15]
例如一些生成的代码,扫描后一大堆问题...
protobuf 生成的检测出来的问题相当多...还有部分mybatis生成的代码~

能否有个功能排除掉部分包?

还有些是第三方规定的package路径,里面有大写只有一个包名的情况.

**Comment by cddesire** [comment]
pb生成的java文件，里面好多方法和类都不遵守规约。

**Comment by Michly1991** [comment]
webservice生成的代码，以及ide自动生成的equals方法也不遵守规约

**Comment by simonjava** [comment]
求解决，不然PB生成的java一堆问题

**Comment by xuantan** [comment]
@pkptzx  这个功能我们后续会考虑。
目前推荐只在需要扫的目录下手动触发扫描；或者在需要跳过的类上方加上 @Generated
