### ISSUE TITLE
如何选择一部分规约，集成到gradle task

### ISSUE THREAD

**Issue by biaomingzhong** [alibaba/p3c#155]
[https://github.com/vincentbrison/vb-android-app-quality](https://github.com/vincentbrison/vb-android-app-quality)，类似于这个项目的写法，怎么在task中调用p3c-pmd呢？

**Comment by smiler158** [comment]
参考 https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F

**Comment by biaomingzhong** [comment]
@smiler158 谢谢
