### ISSUE TITLE
能用GPU加速吗？

### ISSUE THREAD

**Issue by maoguoxu** [alibaba/p3c#157]
如题，大神们能把扫描用GPU性能提升下吗？，另外100%后卡死。。。( ╯□╰ )

**Comment by maoguoxu** [comment]
另外还需要做缓存，扫描后记录MD5，如MD5没修改关闭后应该拿原来的分析结果。提示速度。

**Comment by SeanCai** [comment]
@maoguoxu  Eclipse吗？ 扫描完成后有没有出现 cpu 100%的情况？

**Comment by maoguoxu** [comment]
Cpu没有100%，只是扫描100%后eclipse 卡死，提示总数快接近两万个。

**Comment by SeanCai** [comment]
@maoguoxu 调高内存有效果吗？
