### ISSUE TITLE
[BUG] Different language setting leads to different results

### ISSUE THREAD

**Issue by alphatan** [alibaba/p3c#16]
Analyzing **the same source code** leads to different result by setting the plugin to different language.

* Chinese
![p3c_env_cn](https://user-images.githubusercontent.com/26187550/31580399-57983c76-b181-11e7-9374-310698ef444e.png)
* English
![p3c_env_en](https://user-images.githubusercontent.com/26187550/31580403-5e9cfb10-b181-11e7-9d27-88b161bbbcd6.png)

Versions

| Software | Version|
| ---------: | :------- |
| Idea | 15.0.2 |
| Alibaba Java Coding Guidelines | 1.0.0 |

**Comment by SeanCai** [comment]
@alphatan 重新扫描能够复现吗？有没有报错，或者终止扫描。或者扫描的范围一致吗？

**Comment by alphatan** [comment]
OIC. The cause is the **current** position of selected project.

My project consists of multiple submodules. If my cursor places at any file in a submodule, then it will only analyze the highlighted submodule, though it will show the parent module name at the result window.

Thanks for the hint. @SeanCai
