### ISSUE TITLE
类作者和时间提取的那块：javadoc里@date不是标准标签，建议改成@since

### ISSUE THREAD

**Issue by rofinily** [alibaba/p3c#161]
![np xzg 4qc2f__ql e i 5](https://user-images.githubusercontent.com/19247885/32364278-e3ebe6d2-c0ae-11e7-9d90-4caced29e92e.png)

**Comment by SeanCai** [comment]
@rofinily 1.0.1正在审核中，新版会自动将date加入到customtag中

since标签范围太广 一般用于版本方面，比如jdk中的定义 @since 1.x
