### ISSUE TITLE
缩写词汇提示不符合命名规范

### ISSUE THREAD

**Issue by jqj1994** [alibaba/p3c#162]
比如类名UIManage，UIHandler之类的，希望这些常用词汇不要进行提示。

**Comment by yangguanbao** [comment]
UiManage, UiHandler
多看几眼，其实也还顺眼的。

**Comment by msdx** [comment]
同#172

**Comment by ccpwcn** [comment]
这个东西没有统一的标准，作为工具，我感觉p3c很难处理，总不能维护一个白名单放行？还是需要开发人员自己想办法。

**Comment by msdx** [comment]
@ccpwcn 不需要p3c自己维护，只需要制定一个规则，比如在项目的xxx目录下放一个xxx的文件，上面是白名单。

**Comment by xuantan** [comment]
https://github.com/alibaba/p3c/issues/172
