### ISSUE TITLE
if或者for循环的循环体如果只有单行，没有加括号，能否用黄色提示？推荐修改，而不是直接红色提醒报错。

### ISSUE THREAD

**Issue by ruanyi** [alibaba/p3c#165]
![image](https://user-images.githubusercontent.com/5568762/32479653-7c793852-c350-11e7-9f76-bfe0d5674bfc.png)

**Comment by ruanyi** [comment]
有些人就是喜欢这么写，如果都提示错误，有点蛋疼。。

**Comment by SingleTime** [comment]
是的    只有单行代码个人觉得确实可以不加括号，而且这个也不是致命错误，不会隐藏执行错误

**Comment by LQZYC** [comment]
如果后面还有人要在你这个if条件下加代码，很可能因为忘记加括号而导致严重的后果，最好还是把括号加上吧

**Comment by ruanyi** [comment]
赞同。。但是，历史总有包袱，而且，这种本仁者见仁智者见智的事情，直接标红，个人觉得：有点过了，可以稍微下降一个级别：强烈建议修改。
