### ISSUE TITLE
类名使用UpperCamelCase风格检查

### ISSUE THREAD

**Issue by AlanDelon** [alibaba/p3c#166]
对于一些工具类，类似DESPlus AESUtil可不可以放宽一些，还有就是两个字母的单词或者单个字母后面跟单词遵从UpperCamelCase风格不是很好看

**Comment by LQZYC** [comment]
DesPlus AesUtil 这样也还不错吧

**Comment by Ruffianjiang** [comment]
对于特定的缩写类单词，还是遵从主流认知比较好，像AES、DES、QRCode，主流写法容易辨认，无论是代码还是文案，大家都是这么写的

**Comment by yangguanbao** [comment]
习惯了就好。
