### ISSUE TITLE
eclipse插件与idea插件扫描结果差异很大

### ISSUE THREAD

**Issue by shook2012** [alibaba/p3c#170]
同一java工程，二者扫描结果
idea:
broker : 0
critical:43
marjor:1309
eclipse:
broker : 17   [Map/Set 的key为自定义对象时，必须重写hashCode和equals]，事实上用了Class<?>为key。System.currentTimeMills替换new Date().getTime()，idea没有扫出来。
critical:12
marjor:478

**Comment by SeanCai** [comment]
@shook2012 都是1.0.1版本的插件吗？

**Comment by shook2012** [comment]
都是1.0.0版本的插件。version是1.0.0.201710110354

**Comment by shook2012** [comment]
**编译了1.0.1版本的idea与eclipse插件，二者扫描结果还是差异不小。
eclipse neon:critical：45， critical：1538  idea 2016.2.2 : critical：43， critical：1341     jdk都是1.8.0_60**

**Comment by xuantan** [comment]
具体哪个规则麻烦列举下吧
