### ISSUE TITLE
希望能给一篇英文的比较评测文章，方便说服队伍使用AJCG

### ISSUE THREAD

**Issue by PremierWen** [alibaba/p3c#171]
人在英国，组里目前没有确定coding style checks的标准，刚好AJCG推出了看了下觉得很不错，就想在组里推广，已经使用了IDEA的插件感觉很好，准备和其他几个主流的标准，比如checkstyle(goole checks)比较，不知道有没有类似的比较评测文章，搜了下还没找到，如果你们能抽空写一篇能够帮助推广，谢谢

**Comment by yangguanbao** [comment]
你是英国的团队，还是国内外派的？

**Comment by yangguanbao** [comment]
https://www.cmg.org/2017/10/impact-2017-speaker-spotlight-series-increase-productivity-alibaba-java-coding-guidelines-ide-plugin/
