### ISSUE TITLE
QRCode命名也不能算符合驼峰命名吗？

### ISSUE THREAD

**Issue by msdx** [alibaba/p3c#172]
QR都是缩写，zxing里面也是类似这样的命名，如：QRCodeReader, QRCodeMultiReader

**Comment by yorenew** [comment]
+1 
类名出现MD5、GRPC都会提示不符合UpperCamelCase
![3f8f92b6-20e0-46ba-9461-f1a0902696f7](https://user-images.githubusercontent.com/18479014/32689707-ae06524a-c6ae-11e7-8bab-9645407a5397.png)
~~强迫症真的忍不了~~

**Comment by yangguanbao** [comment]
Md5， 也可以的
QrCode，看多了，也习惯了。
当初坚定地使用这种方式，就是让大家不纠结，一律是驼峰形式，其实也没有那么难看。

**Comment by msdx** [comment]
QRCode也没不对。
