### ISSUE TITLE
抽象类命名规范

### ISSUE THREAD

**Issue by msdx** [alibaba/p3c#173]
我一个抽象类使用Abs开头命名，也提示不符合规范，应使用Abstract或Base开头。但是Android源码里也有以Abs开头来命名的呀。比如AbsListView, AbsSavedState, AbsSeekBar, AbsSpinner。像这种命名能否宽松点？

**Comment by yangguanbao** [comment]
Abs是绝对值的简写，还是依照Abstract的方式。

**Comment by msdx** [comment]
那Android源码的AbsListView是绝对值列表？
