### ISSUE TITLE
是否可以做个sonar的插件，方便集成到sonar中

### ISSUE THREAD

**Issue by andChow** [alibaba/p3c#174]
我们代码规范基于sonar平台统计，java这块命名规则使用的是google-checkstyle，还添加了findbugs检查代码bug，p3c是否可以弄个sonar插件方便我们集成。

**Comment by smiler158** [comment]
参考https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F
