### ISSUE TITLE
遍历map 推荐

### ISSUE THREAD

**Issue by wenbochang888** [alibaba/p3c#177]
《java命名规范》里面的 集合处理 的第十条，推荐遍历map的时候：“如果是 JDK 8，使用 Map . foreach 方法。” 
但经过我的测试 如下：
Map<String, String> map = new HashMap<>(16);
map.put("1", "chang");
map.put("2", "wen");
map.put("3", "bo");

long start = System.nanoTime();
for (Map.Entry<String, String> me : map.entrySet()) {
System.out.println(me.getKey() + " " + me.getValue());
}
long end = System.nanoTime();
long t1 = end - start;
System.out.println(t1);

System.out.println("-------我是分割线--------");
start = System.nanoTime();
map.forEach((key, value) -> System.out.println(key + " " + value));
end = System.nanoTime();
long t2 = end - start;
System.out.println(t2);
System.out.println(t2/t1);

大概map.foreach比map.entryset慢了200倍左右，为什么还这样推荐呢？？？？

**Comment by Jazzylol** [comment]
https://stackoverflow.com/questions/34585444/java-lambdas-20-times-slower-than-anonymous-classes

lambda表达式有初始化开销，事实上你第一次执行lambda表达式以后再多次执行就会发现时间是keyset的一半左右。@wenbochang888

**Comment by xuantan** [comment]
感谢 @Jazzylol 的回复
