### ISSUE TITLE
使用 @SuppressWarnings无效

### ISSUE THREAD

**Issue by joker-fu** [alibaba/p3c#179]
![image](https://user-images.githubusercontent.com/20105457/32707014-10ee007a-c85c-11e7-8d8e-c55a495eeede.png)

如图所示！

**Comment by SeanCai** [comment]
@joker-fu 规则实现的时候禁用了SuppressWarning 的影响

**Comment by joker-fu** [comment]
@SeanCai 那我不想看到红色的报错 怎么破

**Comment by SeanCai** [comment]
@joker-fu 可以修改提示等级

**Comment by FrewenWong** [comment]
修改等级就会针对所有的文件都修改了提示等级。如果只想针对某个或者部分文件不进行这个错误的告警，怎么办？
