### ISSUE TITLE
希望支持Eclipse3.2+的版本，因为MyEclipse 10包含的是Eclipse 3.7

### ISSUE THREAD

**Issue by rogerlin0330** [alibaba/p3c#18]
现在很多企业还是采用MyEclipse 10开发的，而其包含的Eclipse版本是3.7，无法用现在发布的插件

**Comment by zhipfang** [comment]
+1

**Comment by PuYuhang** [comment]
+1

**Comment by yushang1** [comment]
求在myeclipse里面安装该插件的解决方案

**Comment by SeanCai** [comment]
看看MyEclipse是不是已经集成了PMD相关的插件，感觉是因为net.sourceforge.pmd.lang.Language类冲突了
