### ISSUE TITLE
是否能够做一个gradle的配置，像lint检测一样可以自由配置如果出现相应的Issue就编译失败？

### ISSUE THREAD

**Issue by ouyangpeng** [alibaba/p3c#182]
>是否能够做一个gradle的配置，像lint检测一样可以自由配置如果出现相应的Issue就编译失败？

>因为现在将阿里的插件集成到了Android Studio，但是团队无法去监控每个人是否真的按照插件的提示去优化代码了，所以想是否可以像lint一样每个阿里的issue都可以配置error级别，然后我们可以在Jenkins编译的时候直接控制那些Issue是必改的，哪些是可以商榷的。这样就可以逐步将大家的代码规范起来？？

**Comment by xuantan** [comment]
短时间内没有这个计划

**Comment by ouyangpeng** [comment]
@xuantan 尴尬！想问下阿里内部推行这个插件之后是如何去推动大家都按照规范来优化代码的？？
