### ISSUE TITLE
右侧description里面的 中文乱码。

### ISSUE THREAD

**Issue by baronvv** [alibaba/p3c#183]
![image](https://user-images.githubusercontent.com/18189939/32814485-6fcb33da-c9ea-11e7-9c56-a45be55c0674.png)

**Comment by yuzhiping** [comment]
![image](https://user-images.githubusercontent.com/10362461/32836426-b3b57a56-ca44-11e7-90c3-2d2a4961f279.png)
我在IDEA中安装了一个Material Theme UI后，右键菜单中的中文也乱码了。

**Comment by SeanCai** [comment]
https://github.com/alibaba/p3c/issues/32
