### ISSUE TITLE
eclipse和idea里代码检查的错误级别不一致

### ISSUE THREAD

**Issue by tbahh** [alibaba/p3c#187]
Map/Set的key为自定义对象时，必须重写hashCode和equals。
这个错误在eclipse 里是block 级别 （显示的代码错误提示，十分不友好）
而idea 里是 critical 级别

eclipse下是否有办法自定义关掉这些错误提示

**Comment by xuantan** [comment]
好的，谢谢反馈，eclipse新的版本中会修复这个问题。
