### ISSUE TITLE
javadoc没有@date标签

### ISSUE THREAD

**Issue by zlsq** [alibaba/p3c#188]
规约插件推荐开发者在添加类的时候添加上作者名加时间，推荐用@date标签，然而javaDoc没有@date标签，在生成javadoc的时候会报错。

**Comment by SeanCai** [comment]
在构建工具上加上对应配置即可
比如maven：
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-javadoc-plugin</artifactId>
        <version>2.10.4</version>
        <executions>
          <execution>
            <id>attach-javadocs</id>
            <goals>
              <goal>jar</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <tags>
            <tag>
              <name>date</name>
            </tag>
          </tags>
        </configuration>
      </plugin>
