### ISSUE TITLE
重复的规则——避免Random实例被多线程使用

### ISSUE THREAD

**Issue by JonsonJiao** [alibaba/p3c#191]
Inspection中存在两个相同的规则（避免Random实例被多线程使用...），其中第二个Critical级别真实的目的是避免显示的使用new Thread方式使用线程。请修改下这个规则的名称，避免重复。
1.0.1版本 IDEA插件中
规则1：

> 避免Random实例被多线程使用，虽然共享该实例是线程安全的，但会因竞争同一seed 导致的性能下降。说明：Random实例包括java.util.Random 的实例或者 Math.random()的方式。 

规则2：

> 避免Random实例被多线程使用，虽然共享该实例是线程安全的，但会因竞争同一seed 导致的性能下降。说明：Random实例包括java.util.Random 的实例或者 Math.random()的方式。 说明：使用线程池的好处是减少在创建和销毁线程上所花的时间以及系统资源的开销，解决资源不足的问题。如果不使用线程池，有可能造成系统创建大量同类线程而导致消耗完内存或者“过度切换”的问题。

**Comment by xuantan** [comment]
麻烦贴一下当时的截图

**Comment by JonsonJiao** [comment]
![default](https://user-images.githubusercontent.com/9884460/33379285-a7413eb8-d552-11e7-90be-e4776f1002fc.PNG)
![default](https://user-images.githubusercontent.com/9884460/33379301-b27a6e1c-d552-11e7-8b97-1c0ec65da80c.PNG)

**Comment by JonsonJiao** [comment]
[
![same rule name](https://user-images.githubusercontent.com/9884460/33379579-885001d2-d553-11e7-99e8-0c076658b72b.PNG)



](url)

**Comment by xuantan** [comment]
@SeanCai 看一下
