### ISSUE TITLE
1.0.1 Idea 插件无法下载/更新

### ISSUE THREAD

**Issue by agamem** [alibaba/p3c#192]
https://plugins.jetbrains.com/plugin/10046-alibaba-java-coding-guidelines
下载1.0.1，报下面的链接不存在：
 http://p3ctest.oss-cn-hangzhou.aliyuncs.com/Alibaba%20Java%20Coding%20Guidelines-1.0.1.zip

**Comment by xuantan** [comment]
无法复现
