### ISSUE TITLE
IDEA下插件图标显示异常

### ISSUE THREAD

**Issue by JohnstonW** [alibaba/p3c#195]
![snipaste20171201_104946](https://user-images.githubusercontent.com/24651716/33465927-9be51984-d685-11e7-90b2-2297df8cfc67.png)
没有和其它图标一样左对齐。
屏幕分辨率：1920X1080
IDEA版本：2017.2

**Comment by xhaiben** [comment]
mac pro，图标不清晰

**Comment by TYZRPVX** [comment]
![image](https://user-images.githubusercontent.com/7645818/33974843-a3f72b4a-e0c5-11e7-87a8-4e3d62bc2fd9.png)
同样的问题，win10
