### ISSUE TITLE
希望能提供集成到sonar的插件或源碼

### ISSUE THREAD

**Issue by wataei** [alibaba/p3c#197]
目前這方面的教程比較少

**Comment by mrprince** [comment]
please check
https://github.com/mrprince/sonar-p3c-pmd

**Comment by jackokcc** [comment]
please check
https://github.com/mrprince/sonar-p3c-pmd

运行起来
The PMD configuration file is not valid

**Comment by pwjack** [comment]
有人遇到这样导入的sonar-p3c规则，本地使用sonarlint关联服务器时无法检测出问题的情况吗？

**Comment by chaojidachanmao** [comment]
现在互联网公司越来越多的使用sonarqube 建议正式加入到roadmap中

**Comment by willmao** [comment]
@mrprince sonar-p3c-pmd does not support sonar 7.5

**Comment by caoyihong** [comment]
sonar-p3c-pmd just support sonar6.5,but in my computer sonar6.5 does not work

**Comment by huayaoyue6** [comment]
可以查看[huayaoyue6/sonar-pmd-p3c](https://github.com/huayaoyue6/sonar-pmd-p3c)

**Comment by wuwen5** [comment]
似乎 [huayaoyue6/sonar-pmd-p3c](https://github.com/huayaoyue6/sonar-pmd-p3c) 的方式更合规，他是基于源库 https://github.com/jborgers/sonar-pmd 的基础上fork，保留源库版本记录，进行的扩展提交，这样方便后续`cherry-pick`操作，同时保留和遵循了源库的license。

https://github.com/mrprince/sonar-p3c-pmd 库是完全独立的提交，对https://github.com/jborgers/sonar-pmd 库的内容进行了独立提交，且未保留原license，不确定这样是否合规。
