### ISSUE TITLE
关于Java开发规约插件

### ISSUE THREAD

**Issue by gugia** [alibaba/p3c#2]
手册中提到的Java开发规约插件是基于IDE的吗，支持哪些IDE呢？
在此感谢阿里Java技术团队对Java项目的工程性和规范性进行了非常有价值的提炼，帮助国内Java相关从业者和团队不断进步。

**Comment by chaomurray** [comment]
期待插件，能详细说下 支持哪些ide呢

**Comment by SeanCai** [comment]
支持Eclipse和Idea哈

**Comment by VeiZhang** [comment]
期待**10.14**
