### ISSUE TITLE
[Suggestion] allow add custom item to CLASS_NAMING_WHITE_LIST

### ISSUE THREAD

**Issue by dongfg** [alibaba/p3c#20]
### Problem
Some class names that contains IOS,GUI will not match upperCamelCase pattern.
Hope to allow add custom item to CLASS_NAMING_WHITE_LIST.
> p3c/p3c-pmd/src/main/resources/namelist.properties
```
...
ClassNamingShouldBeCamelRule_CLASS_NAMING_WHITE_LIST=["Hbase","HBase","ID"]
```
### Suggestion
- Allow add a custom properties file under project root to add custom item

**Comment by xuantan** [comment]
@dongfg 可以在源码的白名单中自己加上，然后本地自己打个插件出来。
