### ISSUE TITLE
eclipse p3c插件 和 com.alibaba.p3c.pmd 规则区别

### ISSUE THREAD

**Issue by xiaomin0322** [alibaba/p3c#202]
eclipse p3c插件能检测到调用过期方法的规则

而用java -jar com.alibaba.p3c.pmd 里面的规则，是检测不到调用过期方法的规则。

是不是eclipse p3c插件比com.alibaba.p3c.pmd里面的规则多一些？？

**Comment by xuantan** [comment]
是的，详见Readme，有描述的。
![image](https://user-images.githubusercontent.com/1271849/34349555-aa660948-ea4c-11e7-9718-d9b38ae3ac32.png)
