### ISSUE TITLE
规约插件乱码

### ISSUE THREAD

**Issue by kingning1** [alibaba/p3c#203]
![134234](https://user-images.githubusercontent.com/28945542/33918173-ed9f5a30-dfec-11e7-94df-5c6b323efa50.png)
我换了字体之后就乱码了

**Comment by kingning1** [comment]
![123](https://user-images.githubusercontent.com/28945542/33918205-25e25ea6-dfed-11e7-9ec2-f2749785d41a.png)

**Comment by kingning1** [comment]
![32423](https://user-images.githubusercontent.com/28945542/33918241-4fb1ccd0-dfed-11e7-9e90-d042a4c5bd0f.png)

**Comment by xuantan** [comment]
请参照这里
https://github.com/alibaba/p3c/wiki/IDEA%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95
