### ISSUE TITLE
eclipse p3c插件和直接使用com.alibaba.p3c.pmd扫描结果有差异

### ISSUE THREAD

**Issue by xiaomin0322** [alibaba/p3c#204]
eclipse p3c插件和直接使用com.alibaba.p3c.pmd扫描结果有差异

eclipse p3c 插件可以扫描到过期得方法，而com.alibaba.p3c.pmd扫描不到

**Comment by xuantan** [comment]
这个过时方法检测并没有在p3c-pmd中实现，而是单独在IDE插件中实现的，这个在工程概述中已经描述过了。
