### ISSUE TITLE
为什么插件不推荐使用Apache Beanutils呢？

### ISSUE THREAD

**Issue by L-Gravel** [alibaba/p3c#205]
我的代码是这样，
```//属性复制
 BeanUtils.copyProperties(objectA,objectB);
```
然后用插件检测，会报Avoid using *Apache Beanutils* to copy attributes.的blocker错误。想问问这是出于什么考虑，以及有什么替代方法吗？

**Comment by L-Gravel** [comment]
自问自答了，因为Apache Beanutils的资源消耗很大，建议使用Spring 的Beanutils
apache的对象复制，把目标对象的所有属性都存在一个map里面，然后通过properities的名字来复制给另一个对象的属性。而spring的beanUtils,我看到他好像会在存储目标对象属性的时候，过滤一些不必要的属性。

**Comment by ramsayleung** [comment]
之前我也遇到同样的问题, 我作了下总结, 对于具体的原因分析有兴趣的可以参考这篇文章 [为什么不要使用Apache BeanUtils进行属性的copy](https://samray.me/%E4%B8%BA%E4%BB%80%E4%B9%88%E4%B8%8D%E8%A6%81%E4%BD%BF%E7%94%A8Apache-BeanUtils%E8%BF%9B%E8%A1%8C%E5%B1%9E%E6%80%A7%E7%9A%84copy)
