### ISSUE TITLE
IntelliJ: 异常应该以 Exception 结尾

### ISSUE THREAD

**Issue by aristotll** [alibaba/p3c#206]
<img width="552" alt="2017-12-14 18 39 19" src="https://user-images.githubusercontent.com/13341544/33988086-2913e9a2-e0fe-11e7-930d-c1c55ae6bd3a.png">

让 Error 也以 Exception 结尾不合理吧....

**Comment by aristotll** [comment]
Throwable 不仅仅是异常

**Comment by yangguanbao** [comment]
定义一个Error，这本身就是一个错误

**Comment by aristotll** [comment]
@yangguanbao 能给出上面的断言的来源吗 

我搜索了下 类库包括 Junit 也有 error 的类
`junit.framework.AssertionFailedError`

**Comment by yangguanbao** [comment]
别的框架定义的，未必是正确的做法。反正在程序员写中上层业务，就是不应该写Error
Error的级别就像地震这样无法预知，并且这种信息完全没有任何RESPONSE的存在。
