### ISSUE TITLE
p3c规则扫描bug,Integer数组长度比较问题

### ISSUE THREAD

**Issue by xiaomin0322** [alibaba/p3c#209]
伪代码：
 Integer[]  a ;
 Integer[]  b ; 
 if(a.length == b.length){
 }
 扫描报 Integer 不能用==，建议用equals方法
 这种场景不应该报吧

**Comment by songqs** [comment]
亲，你用== 容易出现问题，比如2个65535，按照默认配置是false，但是用equals则一直是true

**Comment by xiaomin0322** [comment]
@songqs 是Integer得长度比较，不是Integer对象比较。
System.out.println(Integer.MAX_VALUE == Integer.MAX_VALUE);true

**Comment by xuantan** [comment]
@fw8899 看一下

**Comment by fw8899** [comment]
PMD解析AST的问题，a.length解析出的类型不是int，而是a的类型。具体fix方案还在确定中。
