### ISSUE TITLE
一个类标记为过时的,如果一个变量名称和这个类相似,也会被识别为过时的

### ISSUE THREAD

**Issue by LambdaV5** [alibaba/p3c#210]
![image](https://user-images.githubusercontent.com/17512402/34242734-16d54a10-e658-11e7-9e26-1ba424536df6.png)

**Comment by xuantan** [comment]
@SeanCai 看一下

**Comment by SeanCai** [comment]
@LambdaV5 这个不是因为名称相似，是因为他属于一个过时的类，就算是在本类中也被提示出来了
下一版会对这种情况不检测、提示
