### ISSUE TITLE
p3c-pmd是否可以和pmd混用？

### ISSUE THREAD

**Issue by herbageh3h** [alibaba/p3c#212]
是否有办法将p3c-pmd中的规则以及pmd中的一些规则混合使用？如果可以的话，有什么好的做法推荐？

**Comment by herbageh3h** [comment]
另外，目前的p3c-pmd是基于pmd5.5的，将p3c-pmd的jar包加入到pmd6.0则无法正常使用p3c的检查规则，预计什么时候可以兼容pmd6.0?

**Comment by xuantan** [comment]
没办法混用。
