### ISSUE TITLE
eclipse 安装后插件后，默认是英文，怎么切换回中文？

### ISSUE THREAD

**Issue by kentTanL** [alibaba/p3c#213]
如题，手册也是看的中文，谢谢

**Comment by xuantan** [comment]
见文档：   https://github.com/alibaba/p3c/wiki/Eclipse%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E5%9B%BD%E9%99%85%E5%8C%96

**Comment by kentTanL** [comment]
Thanks for your help
