### ISSUE TITLE
关于驼峰命名的检测，是否合理？

### ISSUE THREAD

**Issue by kentTanL** [alibaba/p3c#214]
下面是我在测试项目中的部分检测结果，

![image](https://user-images.githubusercontent.com/15412193/34318578-ab719728-e806-11e7-956f-6ee9dc10f192.png)

这里说类名需要满足大写开头的驼峰命名规则，但是 DO、BO、DTO、VO等除外，这里像 BDTO 这样的命名，除去 DTO 外只有一个字母的类名，应该是正常的才对啊？虽然正式开发时可能不会这样只使用一个字母来命名，但是检测的时候这种情况是否应该出现？

**Comment by yangguanbao** [comment]
A/B这样名字，违反了另一条：
11. 【推荐】为了达到代码自解释的目标，任何自定义编程元素在命名时，使用尽量完整的单词 组合来表达其意。
