### ISSUE TITLE
没有注释可以标注某段特定的代码不检查吗？

### ISSUE THREAD

**Issue by kswen** [alibaba/p3c#218]
as title， 比如：

		// p3c:off
		ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor(new ThreadFactory() {

			@Override
			public Thread newThread(Runnable runnable) {

				Thread thread = new Thread(runnable, "System Clock");
				thread.setDaemon(true);
				return thread;
			}
		}); 
              // p3c:on

**Comment by xuantan** [comment]
不好意思，目前没有这个功能。
