### ISSUE TITLE
希望增加代码格式的检查。

### ISSUE THREAD

**Issue by jaune162** [alibaba/p3c#221]
1、缩进4个空格(可以配置最好)
```
public class Test {
    public void a() {
    }
}
```
2、`;` 应该在行尾,并且前面不能有空格

```
//bad
void test()
;

//good
void test();
```
3、类和方法定义中的`{`前应该有一个空格
```
public class Test {
    public void a() {
    }
}
```
4、if、for、while 条件前后应该有一个空格
```
if (a > 0) {
}

for (String s in strs) {
}

while (true) {
}
```
5、=号前后应该各有一个空格
```
String name = "Jaune";
```
6、代码中不允许出现多个空行
7、extends应该在implements之前
8、一行不应该超过120个字符

等一些约定俗成的Java代码格式规范

**Comment by xuantan** [comment]
你好，目前我们提供了eclipse的formatter配置文件。
https://github.com/alibaba/p3c/tree/master/p3c-formatter
格式的检查我们短时间内不考虑提供。
