### ISSUE TITLE
提示文字出现了4次

### ISSUE THREAD

**Issue by ccpwcn** [alibaba/p3c#224]
![4](https://user-images.githubusercontent.com/5465756/34551709-430cf3bc-f157-11e7-9985-9185a9280a42.png)

提示文字出现了4次。

**Comment by xuantan** [comment]
能复现吗？
是否每次都这样？

**Comment by ccpwcn** [comment]
并不一定会出现4次，也有可能出现两次，如下图所示：
![tim 20180109152841](https://user-images.githubusercontent.com/5465756/34709419-27d67006-f552-11e7-887f-36561f09ea13.jpg)
也不是一定会出现，但是出现概率还是比较高的。

**Comment by xuantan** [comment]
这个我们无法复现，猜测是本地机器或IDE配置问题。

**Comment by ccpwcn** [comment]
@xuantan 操作系统已经被我删除重新安装（当然IDEA也是重新安装了的），问题仍然存在。
