### ISSUE TITLE
[improvement] 建议每个规范有个固定的编码

### ISSUE THREAD

**Issue by jiming** [alibaba/p3c#225]
比如

```markdown
## 比如编程约定：1xxxx
* 命名风格   11xxx
* 常量定义   12xxx
```

这样，如果想要给这个规范提供建议或者是团队内的约定跟本手册约定不同的时候，可以直接采用该约定的编号来进行说明。避免手册升级而造成的说明不匹配

谢谢！

**Comment by jiming** [comment]
这样有以下几个好处

* 规范标准化
* 可以在插件里方便的 enable/disable 一些约定
* 方便在各种技术文章或者规范中引用阿里规范，这样更利于规范的推广
  比如： `请参见阿里java 规范 12356 项`

谢谢

**Comment by SeanCai** [comment]
@yangguanbao

**Comment by yangguanbao** [comment]
1）插件和手册，我们是同一个团队在维护，我们尽可能地保证两边是同步的。
2）编号是不固定的。因为它的排序是【强制】【推荐】【参考 】为主顺序 。新增加的内容有可能是在强制项上。也有可能同一领域的内容分布在三个级别上。

**Comment by zqq90** [comment]
虽然被 Close, 还是希望能够重新考虑,
基于需求本身, 我们似乎并不是要求编号要和 "顺序" 以及 "执行等级" 相关,  更类似 Issue ID, 
唯一的要求是, 尽量按照一级大类分组, 每个分组预留即可
