### ISSUE TITLE
README.md file, SimpleDataFormat is not right，shoud be SimpleDateFormat

### ISSUE THREAD

**Issue by yobuke** [alibaba/p3c#229]
5 [Mandatory] **SimpleDataFormat** is unsafe, do not define it as a static variable. If you have to, lock or Apache DateUtils class must be used. Positive example: Pay attention to thread-safety when using DateUtils. It is recommended to use below:

Ivan Yu.

**Comment by xuantan** [comment]
Thank you~

**Comment by xuantan** [comment]
Fixed.
