### ISSUE TITLE
eclipse idea 的类关联规则，有计划在p3c jar中添加吗？

### ISSUE THREAD

**Issue by xiaomin0322** [alibaba/p3c#232]
eclipse idea 的类关联规则，有计划在p3c jar中添加吗？

**Comment by xuantan** [comment]
你好，能否举例说明一下什么是类关联规则么？

**Comment by xiaomin0322** [comment]
@xuantan 
[Mandatory]禁止使用不赞成使用的类或方法。
注意：例如，应该使用decode（String source，String encode），而不是使用不赞成使用的方法decode（String encodeStr）。一旦接口被弃用，接口提供者有义务提供一个新接口。与此同时，客户程序员有义务检查它的新实现是什么。

[Mandatory]来自接口或抽象类的重写方法必须用@Override注解标记。计数器示例：对于getObject（）和get0bject（），第一个字母为“O”，第二个为数字“0”。要准确确定覆盖是否成功，@Override注释是必要的。同时，一旦抽象类中的方法签名被更改，实现类将立即报告编译时错误。

[Mandatory] 一个静态字段或方法应该直接通过它的类名来引用，而不是相应的对象名。

[Mandatory] hashCode和equals的用法如下：

如果equals被覆盖，则覆盖hashCode。
这两个方法必须被重写，因为它们被用来确保在Set中不会有重复的对象被插入。
如果使用自定义对象作为Map的关键字，则必须重写这两个方法。注意：由于这两个方法已被重写，字符串可以用作Map的键。

这些规则

**Comment by xuantan** [comment]
这些规则需要进行跨文件检测，p3c-pmd目前还支持不了这个特性。所以目前没有计划。
