### ISSUE TITLE
希望能关闭掉提示线

### ISSUE THREAD

**Issue by deelew** [alibaba/p3c#235]
看一些老代码时，满屏的波浪线会非常影响可读性，希望提供手动关闭提示的功能，毕竟它只是个工具，没必要太霸道不是么

**Comment by xuantan** [comment]
见wiki  https://github.com/alibaba/p3c/wiki/IDEA%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E5%85%B3%E9%97%AD%E5%AE%9E%E6%97%B6%E6%A3%80%E6%B5%8B

**Comment by mfkvfn** [comment]
Eclipse下怎么弄？
