### ISSUE TITLE
Unable to create the selected preference page.An error occurred while automatically activating bundle com.alibaba.smartfox.eclipse.plugin (1255).

### ISSUE THREAD

**Issue by FrankZhcz** [alibaba/p3c#238]
null
org.eclipse.ui
Error
Wed Jan 24 09:36:10 CST 2018
Conflicting handlers for org.eclipse.ui.navigate.backwardHistory: {ActionHandler(org.eclipse.ui.internal.NavigationHistoryAction@7edb2a4b)} vs {ActionHandler(org.eclipse.ui.internal.dialogs.PreferencePageHistory$1@4e16f173)}

**Comment by FrankZhcz** [comment]
求解，急！

**Comment by xuantan** [comment]
麻烦贴一下更详细的堆栈信息。
