### ISSUE TITLE
自定义规则

### ISSUE THREAD

**Issue by lry1108** [alibaba/p3c#240]
1.由源码（eclipse-plugin、idea-plugin、p3c-formatter、p3c-pmd）怎么能得到eclipse或者IDEA所用的插件呢？如果不通过eclipse或IDEA通过url等自动获取，想自己生成，怎么生成呢？

2.如果想自定义规范，应该修改哪里呢？

求助大神！

**Comment by SeanCai** [comment]
1. Eclipse https://github.com/alibaba/p3c/tree/master/eclipse-plugin#build 在updatesite目录的target包下就可以看到了
2. Idea https://github.com/alibaba/p3c/tree/master/idea-plugin#build
