### ISSUE TITLE
“集合初始化时，指定集合初始值大小”规则目前只对Map起作用

### ISSUE THREAD

**Issue by leeeevincent0123** [alibaba/p3c#249]
Eclipse Oxygen.2 Release (4.7.2)上测试，发现“集合初始化时，指定集合初始值大小”这个规则只对Map集合起作用，对其他集合例如List,Set等均没有相应提示。

**Comment by xuantan** [comment]
是的，规则实现时确实只针对了Map。
不包括List，Set等。
