### ISSUE TITLE
关于System.out.println与e.printStackTrace();一类问题

### ISSUE THREAD

**Issue by changdaye** [alibaba/p3c#26]
Noncompliant Code Example
     System.out.println("My Message");  // Noncompliant
Compliant Solution
    logger.log("My Message");

Noncompliant Code Example
    try {
      /* ... */
    } catch(Exception e) {
      e.printStackTrace();        // Noncompliant
    }
Compliant Solution
    try {
      /* ... */
    } catch(Exception e) {
      LOGGER.log("context", e);
}

昨天简单实用了下插件，提交的小建议，参照sonarlint

**Comment by xuantan** [comment]
谢谢您的建议。
