### ISSUE TITLE
关于插件和仓库版本管理的意见

### ISSUE THREAD

**Issue by minghu6** [alibaba/p3c#262]
在我想要基于1.0.4版本的idea plugin进行修改的时候发现repository里的tag只打到1.0.3．

个人猜测现在是`p3c-pmd`, `idea-plugin`, `eclipse-plugin`都需要版本更新的时候才会在某个commit上同时为这三个标一下tag．其实严格讲这三个应该是三个子模块，但如果一定要放在一个repository里，还是分别标记tag吧（两个插件模块的前三位版本号应该保持一致，对应于Coding Guideline 的版本, 但是插件本身的规则以外的变动（比如bug修复，行为模式的变化）引起的版本变化也应该被标记出来．可以使用第四位版本号，这个版本号可以直接用master 分支的 short merge commit id，比如1.0.4的idea plugin 可以被标记为 `idea-plugin-1.0.3.1a444fc`）．

**Comment by SeanCai** [comment]
感谢反馈 我们这边会讨论一下

**Comment by SeanCai** [comment]
你好，关于tag只打到1.0.3这个，是因为1.0.4的pr还没有合过来，现在好了。并不是都需要更新的时候才会打tag，主要是一般p3c-pmd有变动，三者都需要重新发。

三位版本号 第三位表示 bug修复、行为模式的变化就可以了，第二位表示有新增或者删减功能、规则。
