### ISSUE TITLE
android  @interface 不符合lowerCamelCase命名风格 

### ISSUE THREAD

**Issue by jikun2008** [alibaba/p3c#269]
//添加支持注解的依赖到你的项目中，需要在build.gradle文件中的依赖块中添加：
    //dependencies { compile 'com.android.support:support-annotations:24.2.0' }
    @IntDef({TYPE.DO_NO_THING, TYPE.DO_ONE_START_TO_END_ROUTE,  TYPE.DO_ONE_CAR_TO_START_ROUTE,TYPE.DO_TWO_ROUTE})
    @Retention(RetentionPolicy.SOURCE)
    public @interface TYPE {
        int DO_NO_THING = 0;
        int DO_ONE_START_TO_END_ROUTE = 1;
        int DO_ONE_CAR_TO_START_ROUTE = 2;
        int DO_TWO_ROUTE = 3;
    }

你好 在上面的代码是Android的常量写法 跟enum一样 只是这样写效率会高些。  
但是编码扫描会报这个约束问题, 变量名【DO_NO_THING】不符合lowerCamelCase命名风格 (line 36)
这个能改下吗

**Comment by jianbinJava** [comment]
我也顺便补充一下,
希望lowerCamelCase命名规范补充支持中间带下划线的规则,
比如 props_userName 这样的命名.

**Comment by xuantan** [comment]
好的，确实是我们的问题，下一个版本中会修复掉。

**Comment by JiongBull** [comment]
补充一下，设置忽略警告没有用，不管是阿里的还是系统的。
![1522053696 1](https://user-images.githubusercontent.com/4413502/37895860-05a6bd0c-3115-11e8-8f63-88bf36810f30.jpg)
![_15220537478234](https://user-images.githubusercontent.com/4413502/37895867-07ac0954-3115-11e8-830e-3a57a5f78936.png)

**Comment by jikun2008** [comment]
嗨  你好  在1.0.5版本中     //添加支持注解的依赖到你的项目中，需要在build.gradle文件中的依赖块中添加：
    //dependencies { compile 'com.android.support:support-annotations:24.2.0' }
    @IntDef({TextAlign.LEFT, TextAlign.CENTER, TextAlign.RIGHT})
    @Retention(RetentionPolicy.SOURCE)
    public @interface TextAlign {

        int LEFT = 0;
        int CENTER = 1;
        int RIGHT = 2;
    }

如果放在内部类中依然有这个问题  还是会提示这个检查
