### ISSUE TITLE
// @formatter:off 识别为普通注释

### ISSUE THREAD

**Issue by licardoY** [alibaba/p3c#271]
建议优化 @formatter:off注释, 现在是将其当做普通注释(提示使用javadoc形式的注释等),本来使用@formatter:off, @formatter:on就是这里面的格式要特殊对待,结果把这个注释当做普通注释了

**Comment by xuantan** [comment]
麻烦具体代码截图发一下

**Comment by SeanCai** [comment]
@kerie

**Comment by xuantan** [comment]
把javadoc注释加上就好了
