### ISSUE TITLE
mac  eclipse Oxygen 安装后 不能用 

### ISSUE THREAD

**Issue by xll0617** [alibaba/p3c#273]
mac eclipse 版本： Oxygen.1a Release (4.7.1a)
<img width="602" alt="1111111" src="https://user-images.githubusercontent.com/36976607/36880468-ce16fbf0-1e03-11e8-8636-6c7a3a3f41ad.png">

安装成功 工具栏 右键都不显示插件  有安装成功的吗？_

**Comment by licardoY** [comment]
我的可以啊 Version: Oxygen Release (4.7.0) , 还有一个4.7.2也可以用

**Comment by xll0617** [comment]
@licardoY 那我的可能是和其它插件有冲突 ，我图片里面的哪个插件你没有？

**Comment by xuantan** [comment]
1、下载重装试一下。
2、或者和其它插件冲突了。
