### ISSUE TITLE
idea插件扫描出来的结果，和pmd的不一样

### ISSUE THREAD

**Issue by lfgg123** [alibaba/p3c#275]
通过maven的pmd扫描出的结果比idea要少了下图红框所示的部分。请问这是为什么，怎么解决
![image](https://user-images.githubusercontent.com/30794147/37142737-ea06e420-22f3-11e8-915d-0b3e8a46454c.png)

**Comment by SeanCai** [comment]
红框的步伐理论上不会少的，只不过在IDEA也有原生实现，所以IDEA在导入的时候把这几条屏蔽了

**Comment by lfgg123** [comment]
谢谢回答，我进行了进一步确认。idea的EqualsAvoidNullRule规则和ali的规则是有区别的，idea的规则我不知道哪里看，但是我对同一段代码进行扫描之后，发现通过pmd的方式不会认为违反了EqualsAvoidNullRule规则，而idea的却认为会违反该规则。
![image](https://user-images.githubusercontent.com/30794147/37455970-4e9428b4-2879-11e8-8397-fe7f1b513321.png)
上图就是idea会扫面出来，而pmd则认为没有错误的代码段
