### ISSUE TITLE
eclipse-codestyle.xml 格式有误

### ISSUE THREAD

**Issue by geekerview** [alibaba/p3c#276]
Eclipse导入失败：

<img width="690" alt="wx20180312-194336 2x" src="https://user-images.githubusercontent.com/28476370/37281961-b7e30482-262d-11e8-8427-8d3e4fee6aea.png">

FindBugs检查失败：
<img width="1279" alt="wx20180312-194503 2x" src="https://user-images.githubusercontent.com/28476370/37282010-e2c98716-262d-11e8-8de7-b3289ebc9a6a.png">

**Comment by imu2008** [comment]
@geekerview 能提供一下eclipse的具体版本么？或者重新下载一个模板试一下？我暂未复现。
