### ISSUE TITLE
idea对EqualsAvoidNullRule规则判断与阿里的有区别

### ISSUE THREAD

**Issue by lfgg123** [alibaba/p3c#278]
我进行了进一步确认。idea的EqualsAvoidNullRule规则和ali的规则是有区别的，idea的规则我不知道哪里看，但是我对同一段代码进行扫描之后，发现通过pmd的方式不会认为违反了EqualsAvoidNullRule规则，而idea的却认为会违反该规则。
![image](https://user-images.githubusercontent.com/30794147/37456076-8ae65922-2879-11e8-8592-f6f8c045fa4f.png)
上图就是idea会扫描出来，而pmd则认为没有错误的代码段

**Comment by SeanCai** [comment]
这个IDEA基于其环境有一个实现了，所以我们在集成插件的时候尽量复用IDEA的规则，PMD在检测上有一定的局限性。有可能出现 IDE扫描结果>PMD的情况
