### ISSUE TITLE
在命令行中怎样使用p3c

### ISSUE THREAD

**Issue by guowei1651** [alibaba/p3c#280]
如果需要将p3c作为CI的一部分，在命令行上怎样使用P3C?

**Comment by t-chuma** [comment]
mvn pmd:pmd

**Comment by xuantan** [comment]
见这里
https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F
