### ISSUE TITLE
P3C-idea运行无效

### ISSUE THREAD

**Issue by JayceJiaa** [alibaba/p3c#291]
求助：想自定义一些自己的规则把源码down下来运行idea插件开发沙箱环境，但是程序跑起来之后并没有在Tools工具栏中看到，debug application component也没有进到构造当中。。
![image](https://user-images.githubusercontent.com/22383871/38235877-2a9c785e-3755-11e8-9675-b1a43da18dff.png)
本地打包安装也提示错误，怀疑是因为引用velocity导致（因为这边报红）
![image](https://user-images.githubusercontent.com/22383871/38235952-556c7b42-3755-11e8-855c-9e4abd77561f.png)
然而我在sdk的classpath中加入了相关jar包但是没有生效
![image](https://user-images.githubusercontent.com/22383871/38236015-80c5a336-3755-11e8-9e2d-53d14844bade.png)
第一次开发插件，求大神指点

**Comment by JayceJiaa** [comment]
貌似我在plugin.xml里加自己的action也不能生效，但是新建项目是没有问题的，是哪里的配置出了问题嘛

**Comment by xuantan** [comment]
@SeanCai 看下

**Comment by SeanCai** [comment]
@JayceJiaa 是通过gradle 启动的吗？不用自己添加classpath的

**Comment by JayceJiaa** [comment]
@SeanCai 是用gradle的，之前可能是因为我本地的gradle配置有问题所以一直起不来，后来也忘了怎么调了就好了……抱歉……我先把这个关了
