### ISSUE TITLE
请问一下您的eclipse截图用的什么主题,谢谢

### ISSUE THREAD

**Issue by edc8023** [alibaba/p3c#293]
![image](https://user-images.githubusercontent.com/31379520/38462538-66fe7580-3b1b-11e8-8e08-7ce336701a53.png)

**Comment by SeanCai** [comment]
![image](https://user-images.githubusercontent.com/5645909/38852172-59fcf6ae-424b-11e8-994d-55fe121b5442.png)
你好，我的配置是这个，好像Eclipse有些主题插件，你也可以试试
