### ISSUE TITLE
[常量命名全部大写] static final 属性并不都是常量

### ISSUE THREAD

**Issue by bianjp** [alibaba/p3c#299]
建议参考 [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html#s5.2.4-constant-names) 中对常量的定义: 

> Constants are static final fields whose contents are deeply immutable and whose methods have no detectable side effects.

有些 static final 属性并不是常量，比如手册中出现的一处示例代码：

```java
private static final Logger logger = LoggerFactory.getLogger(Abc.class);
```

把 `logger` 改成 `LOGGER` 并不合理。

**Comment by xuantan** [comment]
logger这个我们确实是加入白名单了，即使不写成全部大写也不会检测报错。

**Comment by bianjp** [comment]
然而还是有很多代码会误报的。

建议保守一些，只有能确定是常量的类型（基本类型、String等）才强制这条规则。我觉得漏报比误报要好些。
