### ISSUE TITLE
提示框显示文字为方框

### ISSUE THREAD

**Issue by Alphrye** [alibaba/p3c#30]
展开提示(ctrl + f1)里的文字正常显示
请问是环境的原因吗?
(Android Studio 3.0 beta 7, Ubuntu 17.04)

**Comment by l-i-h-e** [comment]
给IDE的界面环境指定一个包含中文的字体就好了。

**Comment by xuantan** [comment]
@Alphrye 参照这个Issue https://github.com/alibaba/p3c/issues/32
