### ISSUE TITLE
请教个问题,为什么二方库返回值不能为枚举或者包含枚举的POJO?

### ISSUE THREAD

**Issue by ccc1994** [alibaba/p3c#303]
假如我想在Dubbo接口的返回值里加上一个用来标识返回状态(类似Http状态码)的枚举呢?

或者说是否能在此条目下增加一跳说明呢?

**Comment by xuantan** [comment]
说明：由于升级原因，导致双方的枚举类不尽相同，在接口解析，类反序列化时出现异常。
