### ISSUE TITLE
适配pmd 6.3.0 以上版本

### ISSUE THREAD

**Issue by Richie12138** [alibaba/p3c#306]
### 修改点
1. ruleset、rule 缺少 description
2. test-data xml声明补充
`<test-data xmlns="http://pmd.sourceforge.net/rule-tests"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://pmd.sourceforge.net/rule-tests http://pmd.sourceforge.net/rule-tests_1_0_0.xsd">`
3. test-data expected-linenumbers 跟随 expected-problems

**Comment by xuantan** [comment]
谢谢你的反馈，第四季度我们会考虑升级pmd的版本。

**Comment by arthur657834** [comment]
pmd 6.13.0未适配，所以你们并没有升级！！！！
