### ISSUE TITLE
FAIL TestCase 3

### ISSUE THREAD

**Issue by Richie12138** [alibaba/p3c#307]
1. ThreadLocalShouldRemoveRule::3 with initial 1(com.alibaba.p3c.pmd.lang.java.rule.concurrent.ConcurrentRuleTest)  Time elapsed: 0.017 sec  <<< FAILURE!
java.lang.AssertionError: "with initial 1" resulted in wrong number of failures, expected:<0> but was:<1>
2. TestClassShouldEndWithTestNamingRule::2 Test Class Name Should End With Test(com.alibaba.p3c.pmd.lang.java.rule.naming.NamingRulesTest)  Time elapsed: 0.008 sec  <<< FAILURE!
java.lang.AssertionError: "Test Class Name Should End With Test" resulted in wrong number of failures, expected:<1> but was:<0>
3. WrapperTypeEqualityRule::1 compare wrapper type objects without equals(com.alibaba.p3c.pmd.lang.java.rule.oop.OopRuleTest)  Time elapsed: 0.026 sec  <<< FAILURE!
java.lang.AssertionError: "compare wrapper type objects without equals" resulted in wrong number of failures, expected:<3> but was:<4>

**Comment by xuantan** [comment]
We tried the latest version of project on github，the testcases all success.
