### ISSUE TITLE
一（一）15中Enum说明不够严谨

### ISSUE THREAD

**Issue by earendil1412** [alibaba/p3c#311]
一（一）15. 【参考】枚举类名建议带上 Enum 后缀,枚举成员名称需要全大写,单词间用下划线隔开。
说明:枚举其实就是特殊的常量类,且构造方法被默认强制是私有。

java中枚举类可用于实现接口，实现单例。不单单是“常量”类如此简单。

根据effective java third edition：
page 18:
item 3--Enforce the singeleton property with a private constructor or an enum type: 
a single-element enum type is often the best way to implement a singleton.
page 176:
item 38--Enulate extensible enums with interface:
for example:
public interface Operation{
  double apply(double x, double y);
}
public enum BasicOperation implements Operation{
  PLUS("+"){
    public apply(double x, double y){return x+y}
  }
  MINUS("-"){
    public apply(double x, double y){return x-y}
  }
  private final String symbol;
  BasicOperation(String symbol){
    this.symbol=symbol;
  }
}

**Comment by xuantan** [comment]
@yangguanbao

**Comment by yangguanbao** [comment]
已经在今天下午更新的1.4.0版本里修正了这一说明，感谢你对P3C和阿里巴巴JAVA开发手册的支持！
