### ISSUE TITLE
同层服务之间不循序相互依赖，这个是否是工程设计规范。

### ISSUE THREAD

**Issue by githublaohu** [alibaba/p3c#313]
比如 分布式服务A，B ，都是基础服务，生产者。那么A不能依赖B。这种情况。

**Comment by yangguanbao** [comment]
大的模块级，同层之间可以互相依赖。
而代码层面的细粒度级的服务，不要互相依赖.

**Comment by githublaohu** [comment]
如果同层之间相互依赖，造成了依赖混乱怎么办？
