### ISSUE TITLE
不让使用行尾注释真心难以认同

### ISSUE THREAD

**Issue by Torahlzy** [alibaba/p3c#314]

**Comment by liukaiK** [comment]
感觉行尾注释真的很丑 结构差  还是不要写在行尾吧

**Comment by yangguanbao** [comment]
行尾格式很乱，对齐还是不对齐？
另外，有些人写得过于随意，导致代码与注释看起来一版混乱。
如果非得在行尾写，还不如不写。

**Comment by Torahlzy** [comment]
`int a = 1;
        if (a == 0) {//用户在线

        } else if (a == 2) {//不在线的情况
            for (int i = 0; i < a; i++) {
                //省略n行代码



                i++;
            }//end fori
        } else {//用户异常

        }`
求指教这种情况不适用行尾注释如何弄

**Comment by liu78778** [comment]
我认为行尾注释还是要保留的, 比如我用枚举, 排的整整齐齐的行尾注释, 一眼就能找到枚举项
