### ISSUE TITLE
集合处理的第七条是为什么呢

### ISSUE THREAD

**Issue by PinoZhou** [alibaba/p3c#315]
List<String> list = new ArrayList<String>();
list.add("1");
list.add("2");
for (String item : list) {
if ("1".equals(item)) {
list.remove(item);
}
}
为什么删除"1"就不会报错，删除"2"就报错呢？

**Comment by yangguanbao** [comment]
public static void main(String[] args) {
    List<String> list = new ArrayList<String>();
    list.add("a");
    list.add("b");
    list.add("c");
    for (String s : list) {
        if ("b".equals(s)) {
            list.remove(s);
        }
    }
    System.out.println(list);
}
大部分人一定会觉得，这里一定抛ConcurrentModificationException.
可实际的结果是，程序运行完成，输出[a, c].


为什么结果会和大家想象的会不一样，这就要看一下ConcurrentModificationException的具体产生原因了。
ArrayList的遍历是通过该类下的内部类Itr实现的，Itr的实现如下:
private class Itr implements Iterator<E> {
    int cursor = 0;
    int lastRet = -1;
    int expectedModCount = modCount;
    public boolean hasNext() {
           return cursor != size();
    }
    public E next() {
           checkForComodification();
        try {
        E next = get(cursor);
        lastRet = cursor++;
        return next;
        } catch (IndexOutOfBoundsException e) {
        checkForComodification();
        throw new NoSuchElementException();
        }
    }
    public void remove() {
        if (lastRet == -1)
        throw new IllegalStateException();
           checkForComodification();
 
        try {
        AbstractList.this.remove(lastRet);
        if (lastRet < cursor)
            cursor--;
        lastRet = -1;
        expectedModCount = modCount;
        } catch (IndexOutOfBoundsException e) {
        throw new ConcurrentModificationException();
        }
    }
 
    final void checkForComodification() {
        if (modCount != expectedModCount)
        throw new ConcurrentModificationException();
    }
}
可以看到，Itr类中维护了以下几个成员变量，

cursor：表示下一个要访问的元素的索引，从next()方法的具体实现就可看出
lastRet：表示上一个访问的元素的索引
expectedModCount：表示对ArrayList修改次数的期望值，它的初始值为modCount

modCount是AbstractList类中的一个成员变量，记录数组被修改的次数。

遍历时每当Itr去获取下一个元素时，就会调用checkForComodification()去检查ArrayList是否被修过，如果被修改过就会抛出ConcurrentModificationException

如下面这段ArrayList的源码所示，在调用ArrayList中的remove方法时，modCount被加1，所以会造成modCount的值与expectedModCount不相等。所以当Itr尝试去获取下一个元素时，一定会抛ConcurrentModificationException。
public boolean remove(Object o) {
    if (o == null) {
        for (int index = 0; index < size; index++)
            if (elementData[index] == null) {
                fastRemove(index);
                return true;
            }
    } else {
        for (int index = 0; index < size; index++)
            if (o.equals(elementData[index])) {
                fastRemove(index);
                return true;
            }
    }
    return false;
}


private void fastRemove(int index) {
    modCount++;
    int numMoved = size - index - 1;
    if (numMoved > 0)
        System.arraycopy(elementData, index+1, elementData, index,
                         numMoved);
    elementData[--size] = null; 
} 
那么又是为什么程序在删除"b"元素之后没有抛这个异常呢？

原因其实很简单，大家可以看一下Itr中的
public boolean hasNext() {
       return cursor != size();
}
这个方法， 当元素"b"被删除后，cursor的值正好与数组的size()相等，所以Itr的遍历任务已经结束，不再会去获取下一个元素，所以也就没有抛异常了。


当然这个情况只有在删除数组中的倒数第二个元素时才会出现，只是一个巧合现象，在我们代码规范中，还是绝对禁止在遍历list的时候直接使用list.remove()方法来删除元素的。

如果实际应用场景下有在遍历时删除元素的需求，请使用Iterator中的remove()方法，在上面的代码实现中可以看到在remove()方法中有一步 expectedModCount = modCount; 的操作，
所以在单线程情况下使用该方法是不会抛异常的。
