### ISSUE TITLE
首页下载pdf 连接无法打开

### ISSUE THREAD

**Issue by xtea** [alibaba/p3c#319]
中文版 pdf下载地址错误：
https://github.com/alibaba/p3c/blob/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E7%BA%AA%E5%BF%B5%E7%89%88%EF%BC%89.pdf

**Comment by yangguanbao** [comment]
https://github.com/alibaba/p3c/blob/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E8%AF%A6%E5%B0%BD%E7%89%88%EF%BC%89.pdf

**Comment by yangguanbao** [comment]
![image](https://user-images.githubusercontent.com/25759061/41158683-10d1eba6-6b54-11e8-882a-904c97770045.png)
链接好像稍微不同。
