### ISSUE TITLE
ubuntu 16.04LTS 安装插件后菜单显示乱码

### ISSUE THREAD

**Issue by xuchengdong** [alibaba/p3c#32]
![](http://on9hyivqv.bkt.clouddn.com/Screenshot%20from%202017-10-16%2009-37-54.png)
![](http://on9hyivqv.bkt.clouddn.com/Screenshot%20from%202017-10-16%2009-46-46.png)

**Comment by kkyflying** [comment]
+1 同样的问题
我是Ubuntu 16.04lts
Android studio 2.3.3
同样出现乱码的问题

**Comment by SeanCai** [comment]
换个字体试试，之前的反馈时遇到这种情况换个字体就OK了

**Comment by jokermonn** [comment]
字体设置问题，Appearance&Behavior->Appearance->UI Options->Name里面设置成微软雅黑（microsoft yahei light）

**Comment by kkyflying** [comment]
@jokermonn 意思目前占时不能适配其他字体？只能用微软雅黑（microsoft yahei light）吗？

**Comment by jokermonn** [comment]
@kkyflying 这个我母鸡啊，微软雅黑是能兼容的，其他系列我没试过

**Comment by l-i-h-e** [comment]
这个是IDE的锅吧，只要你给界面指定一个包含中文的字体就行了，至于具体是什么就看你的喜好了。其实他设计成英文的也就没这个毛病了。

**Comment by eumji025** [comment]
用simsun字体应该没问题

**Comment by kkyflying** [comment]
@jokermonn 我是用Comic Sans MS啊，可是本身as不会乱码，也就这个插件会而已

**Comment by jokermonn** [comment]
@kkyflying 插件本身使用的是中文，其中部分会乱码，例如状态栏中，例如鼠标刚移动到 warning 上。跟插件无关，应该是 IDEA 在部分地方中文显示不太好

**Comment by xuchengdong** [comment]
总结一下解决办法：
1.设置字体为微软雅黑，切换完可以正常显示
![](http://on9hyivqv.bkt.clouddn.com/Set%20Micro%20Hei.png)

2.切换插件的语言为英文（需要重启idea）
![](http://on9hyivqv.bkt.clouddn.com/Chinese.png)

3.如果不喜欢微软雅黑再将默认的Ubuntu字体切换回来
![](http://on9hyivqv.bkt.clouddn.com/Ubuntu.png)

4.默认字体可以正常显示英文了
![](http://on9hyivqv.bkt.clouddn.com/Switch%20language%20to%20English.png)

**Comment by SeanCai** [comment]
thx all
