### ISSUE TITLE
Allow configuration file to toggle some of the rules

### ISSUE THREAD

**Issue by TisnKu** [alibaba/p3c#324]
Most of the rules are pretty good, while some of them are not compatible with code style in our company.  Hope there is a toggle for rules in configuration file.

**Comment by xuantan** [comment]
Where's the configuration file？  p3c-pmd  or  plugin ?

**Comment by TisnKu** [comment]
Something like PMD plugin rule set. For instance, we can specify PMD rule set files in gradle like `project.pmd.ruleSetFiles = files("config/pmd-ruleSets.xml")`

**Comment by TisnKu** [comment]
Sorry, found the config on Readme.
