### ISSUE TITLE
【讨论】 接口和实现类的命名 

### ISSUE THREAD

**Issue by zmlgit** [alibaba/p3c#325]
在规约中提到:
_1）【强制】对于 Service 和 DAO 类，基于 SOA 的理念，暴露出来的服务一定是接口，内部
的实现类用 Impl 的后缀与接口区别。
正例：CacheServiceImpl 实现 CacheService 接口。_

感觉这个规约不是很合理。按照这个规约的约定，一个接口只能有一个实现，或者说一个包内只能有一个实现，因为一个包内不能出现两个相同名字的类。但是如果在项目中随便使用哪个设计模式，只要是面向接口编程，就不可能只有一个实现。所以，这种命名规范应该降级为一种推荐的规范，而不是强制的

**Comment by peterguo3019** [comment]
他只是举了一个例子,不是说一个接口只能有一个实现
比如我有一个 IPeopleService接口 但是由于某些原因如业务问题这个PeopleServiceImpl实现类我不能用了 然后我写了个StudentServiceImpl实现了IPeopleService  那么我就可以在不改变接口的情况下切换实现类
