### ISSUE TITLE
关于POJO类的理解以及和Entity, Model的对应

### ISSUE THREAD

**Issue by peterguo3019** [alibaba/p3c#326]
如果理解没有错的话
MVC中Model应该对应的时VO/DTO
Entity对应的是DO还是PO?  感觉像是DO和PO的混合
BO如果我没有理解错 应该就是我们所说的聚合/组合对象
以上,有理解错误的麻烦指出一下 不胜感激

**Comment by yangguanbao** [comment]
首先MVC中的M是指的可重用的逻辑单元，有可能指的是服务，或者应用中被复用的某个模块，与领域模型没有关系。其它的，请参考：
分层领域模型规约:
 DO(Data Object):此对象与数据库表结构一一对应，通过 DAO 层向上传输数据源对象。等同于PO
 DTO(Data Transfer Object):数据传输对象，Service 或 Manager 向外传输的对象。
 BO(Business Object):业务对象，由 Service 层输出的封装业务逻辑的对象。
 AO(ApplicationObject):应用对象，在Web层与Service层之间抽象的复用对象模型， 极为贴近展示层，复用度不高。
 VO(View Object):显示层对象，通常是 Web 向模板渲染引擎层传输的对象。
 Query:数据查询对象，各层接收上层的查询请求。注意超过 2 个参数的查询封装，禁止
使用 Map 类来传输。

**Comment by peterguo3019** [comment]
Service 或 Manager 向外传输的对象  能否使用Result来输出?  将DTO放到result 中, 因为Service 或 Manager中也会牵扯到一些逻辑的判断,在这里面进行异常抛出体验不是很好
