### ISSUE TITLE
Result是否可以由业务层返回?

### ISSUE THREAD

**Issue by peterguo3019** [alibaba/p3c#329]
业务层目前分为两种  应用业务层和基类业务层(领域服务层???  领域驱动设计刚开始看)    基类业务层就是直接对dao的操作  而应用业务层是在基类业务层的上进行具体业务的整合  比如后台用户登录  这里会牵涉到用户和角色  在user的应用业务层中就会调用角色的应用服务层(进行权限判断)和user的基础服务层(进行读写操作)    那么在应用业务层操作时我是直接使用result返回的  没有使用try catch (考虑到try catch会有开销)   这样做是否合理呢?

**Comment by peterguo3019** [comment]
考虑了一下   可行  基础服务层返回数据或boolean类型或直接操作    
基础业务层负责对调用dao对实体进行读写操作,以及一些简单的判断 如更新,删除前判断是否存在
应用业务层 组合各个业务层接口  将结果组装成DTO放入Result 然后返回给Controller   
Controller只需要对参数进行验证以及响应请求

基础业务层就是具体实体的操作 如 user, role 等 
应用业务层这里就是属于具体模块功能  如 用户模块 , 订单模块 , 广告模块,等等 ,  到后面随着网站做大模块下还可以继续划分,如 用户模块划分为  登录模块 注册模块  等等

**Comment by kerie** [comment]
@peterguo3019 这方面代码规约没有做要求，根据业务场景自己做判断吧。
