### ISSUE TITLE
可以提供一份规范化的简单易懂的dome吗?

### ISSUE THREAD

**Issue by color-sense** [alibaba/p3c#33]
包含对用户进行简单的增删改查,  完整的单元测试,以及相关的说明.以及如何利用云效平台,做代码开发跟相关测试工作,我可以这段时间可以出一个简单的dome,希望阿里的人给与指正下.共同出一份在云效平台上面使用的帮助说明.谢谢,麻烦你们的,这个要求很无理,但希望得到你们的支持跟帮助.

**Comment by xuantan** [comment]
可以到云效平台，点击右下角留言，会有专门的同学解答。
