### ISSUE TITLE
规约建议

### ISSUE THREAD

**Issue by SealinRepo** [alibaba/p3c#333]
既然规约里边单独拿出Mysql版块,是否应加入Mysql数据库查询非主键索引导致数据死锁的问题

**Comment by kerie** [comment]
@SealinRepo 你再具体描述一下，我们考虑下

**Comment by SealinRepo** [comment]
@kerie 找到个讲的比较清楚的文章,https://blog.csdn.net/wwd0501/article/details/78052149

**Comment by yangguanbao** [comment]
这一条暂时先不加了，最新的MYSQL版本里没有发现过类似问题。
