### ISSUE TITLE
(七)控制语句  避免采用取反逻辑运算符

### ISSUE THREAD

**Issue by eAhujianfeng** [alibaba/p3c#339]
`!String.equals()`
`!StringUtils.equals()`
`!List.isEmpty()`
推荐用什么写法?

**Comment by kerie** [comment]
代码规约针对多个条件的情况，建议避免使用取反逻辑。对于你上述的例子没有规定，正常写就行。

**Comment by eAhujianfeng** [comment]
谢谢答复。规约的例子，是不是应该改成多条件的例子。e.g. if ( !a.isEmpty() || !b.isEmpty()) {...}
