### ISSUE TITLE
代码没有路径复杂度计算

### ISSUE THREAD

**Issue by blackcatIan** [alibaba/p3c#343]
想问一下是否能加入路径复杂度计算，类似这样下面这样的代码
比起代码长度为80，感觉一个方法的路径复杂度才决定一段代码有多难读，并且严重影响单元逻辑覆盖可测性，请问阿里代码规范插件里不会约束检查这个么？可否加上这个功能

例如下面这样的代码
`/**
 * 
 * @author Ian
 *
 */
public class Test {
    public void test() {
        int a = 1;
        int b = 2;
        if (a == b) {
            b = a;
        } else {
            if (a == b) {
                b = a;
            } else {
                if (a == b) {
                    b = a;
                } else {
                    if (a == b) {
                        b = a;
                    } else {
                        if (a == b) {
                            b = a;
                        } else {
                            if (a == b) {
                                b = a;
                            } else {
                                if (a == b) {
                                    b = a;
                                } else {
                                    if (a == b) {
                                        b = a;
                                    } else {
                                        a = b;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }`

**Comment by xuantan** [comment]
你好，这个点上暂时不会考虑。
