### ISSUE TITLE
对于ScheduledExecutorService是否可以使用Executors？

### ISSUE THREAD

**Issue by xmtsui** [alibaba/p3c#344]
当前ScheduledThreadPoolExecutor的构造方法自身就没有设置BlockingQueue的constructor，默认是一个DelayedWorkQueue，当有需求是初始化一个ScheduledExecutorService时，用executors比较方便。
```
 ScheduledExecutorService executor = Executors.newSingleThreadScheduledExecutor(new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                return new Thread(r, "xxx");
            }
        });
```

**Comment by xmtsui** [comment]
why close my issue without any comments?

**Comment by xmtsui** [comment]
why close my issue without any comments?

**Comment by nadirvishun** [comment]
可以使用，只要是用`ScheduledThreadPoolExecutor`这个类，里面`DelayedWorkQueue`是无界的，不管怎么配置效果和`Executors`下执行没什么区别，新版也已删除关于`ScheduledThreadPoolExecutor`需要手动写的描述。
