### ISSUE TITLE
开发手册pdf中SQL五MySQl数据库（三）SQL语句3.例子问题

### ISSUE THREAD

**Issue by browncrane** [alibaba/p3c#347]
https://github.com/alibaba/p3c/blob/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E8%AF%A6%E5%B0%BD%E7%89%88%EF%BC%89.pdf

文件的 五、MySQl数据库 （三）SQL语句 3.中
> 正例：可以使用如下方式来避免 sum 的 NPE 问题： SELECT IF(ISNULL(SUM(g)) ,0, SUM(g))
> FROM table;

SUM(g))多了一个右括号，如果能完善一下就是一个更好的正例了。

**Comment by xuantan** [comment]
谢谢，check了一下没有问题。
