### ISSUE TITLE
eclipse无法自定义生效条目以及类名保留关键字

### ISSUE THREAD

**Issue by cowcomic** [alibaba/p3c#35]
用IDEA可以选择某一条条规则不生效或修改级别, 但eclipse里面只能看到条目, 无法设置单条是否生效以及调整级别

另外关于类名大驼峰的检查, 有一些领域模型的保留字, 希望这部分可以自定义添加保留字, 情景比如 : 在类名的命名上会加入公司名的缩写, 这个缩写都是全大写的

**Comment by LoveFancy** [comment]
![default](https://user-images.githubusercontent.com/3839577/35470718-897304a6-0389-11e8-9b4c-2291df4e0a6a.png)

这个namelist.properties中可以自己定义保留字，修改后，重新打包替换应该就可以吧？

**Comment by SeanCai** [comment]
@LoveFancy 是的
