### ISSUE TITLE
(4) OOP规约  21. 类成员与方法访问控制从严 和 单元测试 ?

### ISSUE THREAD

**Issue by eAhujianfeng** [alibaba/p3c#351]
需要通过成员方法依赖注入一些外部类；以及单元测试中需要通过这些方法设置这些类；在其他类中可能完全不调用这些方法。这类方法推荐用什么访问级别？

**Comment by xuantan** [comment]
@yangguanbao

**Comment by xuantan** [comment]
你好，这种问题一般交给你所使用的某类测试框架来解决。
