### ISSUE TITLE
使用lombok @Data标注的时候，提示“方法缺少@Override注解”怎么破啊？

### ISSUE THREAD

**Issue by linkiot** [alibaba/p3c#352]
使用lombok @ Data标注的时候，提示“方法缺少@Override注解”怎么破啊？

`
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.experimental.Accessors;

/**
 * 
 * @author linkiot
 *
 */
@ Data
@Accessors(chain = true)
@MappedSuperclass
public abstract class AbstractDateAuditEntity extends BaseEntity {

	private static final long serialVersionUID = 1L;

	@CreationTimestamp
	@Column(name = "created_at", nullable = false)
	@JsonProperty("createdAt")
	private Date createdAt;

	@UpdateTimestamp
	@Column(name = "updated_at", nullable = false)
	@JsonProperty("updatedAt")
	private Date updatedAt;

        // ......
}

`

**Comment by kerie** [comment]
BaseEntity的内容可以给一下吗？

**Comment by shinestmt** [comment]
我也碰到这类情况, 比如上级 类有个方法 Integer getStatus();
```
AbstractModel {
  public abstract Integer getStatus();
}
```

下级类中 lombok 根据 String name 生成 getName()
```
UserModel extends AbstractModel {
  @Getter
  private Integer status;
}
```
此时扫描就会出现这样的提示

**Comment by xuantan** [comment]
@SeanCai 看下

**Comment by zy198804065** [comment]
解决了么

**Comment by SeanCai** [comment]
@linkiot 我这边无法复现，请问使用的是什么版本的idea、以及什么版本的lombok

**Comment by lovewhll** [comment]
阿里插件检查使用 lombok报错---方法缺少 '@Override' 注解

**Comment by lovewhll** [comment]
Eclipse Oxygen Release  lombok 1.16.22

**Comment by Q10Viking** [comment]
应该是你的父类和你的子类有相同的属性，仔细检查下。或者你贴出你父类的代码`BaseEntity`
