### ISSUE TITLE
不符合UpperCamelCase命名风格不起效果

### ISSUE THREAD

**Issue by HiAscend** [alibaba/p3c#353]
idea 20173.5 X64 添加了注释不起作用，添加压制警告后没有效果。仍然后下划线警告。
@SuppressWarnings("AlibabaClassNamingShouldBeCamel")
public class TestNGTimeoutTest {
}
添加压制警告后 TestNGTimeoutTest 下面仍然有波浪线警告

**Comment by kerie** [comment]
暂时还不支持SuppressWarnings注解。

**Comment by rainbow702** [comment]
@kerie 
有计划增加对这个注解的支持吗？
