### ISSUE TITLE
规则检查能否支持自定义

### ISSUE THREAD

**Issue by myeashion** [alibaba/p3c#355]
现在默认检查规则都是打开的，能否支持自定义开启，或者调整级别。这样，执行时可以分阶段对遗留代码进行改进 。

**Comment by kerie** [comment]
参考下面文档进行配置：https://github.com/alibaba/p3c/wiki/IDEA%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E5%85%B3%E9%97%AD%E5%AE%9E%E6%97%B6%E6%A3%80%E6%B5%8B
