### ISSUE TITLE
线程池构造方法提示

### ISSUE THREAD

**Issue by szsonic** [alibaba/p3c#357]
`new ScheduledThreadPoolExecutor(100,Executors.defaultThreadFactory(),new ThreadPoolExecutor.AbortPolicy());`
用这个构造方法创建这个线程池的时候会提示“要使用带有ThreadFactory参数的ScheduledThreadPoolExecutor构造方法哦，这样你就可以方便的设置线程名字啦”，然而这个已经是带ThreadFactory参数的了，望优化

**Comment by kerie** [comment]
不建议使用Executors.defaultThreadFactory()，默认的ThreadFactory设置的线程名字含义不清晰。
