### ISSUE TITLE
最新版开启实时监测后导致IDE不停index

### ISSUE THREAD

**Issue by RainFool** [alibaba/p3c#358]
Android studio版本：3.1.3
插件版本：1.0.5

运行一段时间后，出现IDE不停在index，导致整个IDE卡住，关闭实时监测后恢复正常。
非必现

**Comment by imu2008** [comment]
@RainFool  index的提示应该是AS在正常工作，当然，插件在AS index时可能存在设计缺陷，谢谢反馈。
