### ISSUE TITLE
Eclipse扫描结束后卡死

### ISSUE THREAD

**Issue by wander2016** [alibaba/p3c#36]
Eclipse版本：Version: Neon.2 Release (4.6.2)
JDK：1.8

使用Eclipse扫描结束后，打开扫描结果直接卡死。改用IDEA后一直正常！
其他人是否有类似情况？

**Comment by riclava** [comment]
卸载JPA插件

**Comment by 78425665** [comment]
Eclipse Version: Mars.1 Release (4.5.1)
jdk: 1.8

同样的问题，卡的一匹啊

**Comment by SeanCai** [comment]
卡的同学，你们工程的代码量大吗？有没有单个文件特别大的，比如通过代码生成器生成的？

我是插件的开发同学哈，平时不怎么使用Eclipse，所以在插件方面可能会有很多欠缺的地方，希望能有Eclipse的大神加入进来

**Comment by riclava** [comment]
@SeanCai 应该是JPA的问题，跑完之后会产生一堆的JPA线程导致僵死，不过去掉JPA之后还是会有100%的CPU占用，这块还不清楚原因

**Comment by 78425665** [comment]
我的工程量一点都不大，单文件不超过500行，整体项目源代码不超过3M，应该是有东西一直在扫描，或者有用到网络请求之类的阻塞进程了

**Comment by followwwind** [comment]
同上，eclipse卡爆了

**Comment by wander2016** [comment]
@SeanCai 
小项目，源码文件大概有6M，有mybatis自动化生成的java和xml文件。
是不是插件扫描完成之后，触发了死循环的job了？

查看Eclipse的堆栈，统计(jmc统计的)信息如下：
堆栈跟踪	样本计数	百分比(%)
org.eclipse.core.internal.jobs.Worker.run()	2,511	70.455
org.eclipse.core.internal.jobs.WorkerPool.startJob(Worker)	1,036	29.068

**Comment by huaye2007** [comment]
有点像死循环 到99%就走不动了。Eclipse分配了6G内存 都消耗完了。

**Comment by huaye2007** [comment]
没法上传文件 堆栈我敲下
org.eclipse.core.internal.jobs.InternalJob.addLast(InternalJob) 99.92%
      org.eclipse.core.internal.jobs.JobManager.nextJob()           99.92%

**Comment by Ruffianjiang** [comment]
全是这个查错的线程，结束时卡死（预计大几千个线程）
JPA Project Change Event Handler (Waiting)

**Comment by NotSky** [comment]
如果项目间依赖、引用过多，建议单个项目扫描，否则很容易卡死。机器内存16G，eclipse配置-Xms512m
-Xmx1024m

**Comment by AIKKYU** [comment]
#36

**Comment by SeanCai** [comment]
@wander2016 打开扫描结果才会卡死吗？
