### ISSUE TITLE
idea多模块时，直接报无可疑代码

### ISSUE THREAD

**Issue by ganpanlin** [alibaba/p3c#361]
idea一个项目中包含两个模块，扫描项目时，只能扫到第一个模块。
对第二个模块扫描时，有扫描进度，但提示
No suspicious code found. 2,449 files processed in 'Selected files'.

maven设置了根据环境复制web.xml

**Comment by kerie** [comment]
是不是一个idea窗口导入了两个不同的工程？

**Comment by ganpanlin** [comment]
是的，idea创建一个项目（相当于eclipse的空间）后，再创建一个module，这个时候，就包含了两个模块（项目）了
![tim 20180727150914](https://user-images.githubusercontent.com/16680388/43306827-0b641762-91af-11e8-9877-d1ba282febbb.png)

**Comment by xuantan** [comment]
你好，请再提供下完整展开的目录结构截图，以便我们断定具体问题，谢谢。

**Comment by angelkang** [comment]
我也遇到同样问题，就是模块依赖另一个模块，但是扫描只能扫描当前模块

**Comment by ganpanlin** [comment]
关闭吧，可能双项目的不多。
