### ISSUE TITLE
自己创建的接口的setSomething方法误报Overridden methods are not annotated with '@Override'

### ISSUE THREAD

**Issue by pugwoo** [alibaba/p3c#363]
自己创建的接口的setSomething方法误报Overridden methods are not annotated with '@Override'

实际上这个接口没有继承任何接口，不存在需要注解@Override

**Comment by pugwoo** [comment]
更新一下，实现的方法确实没有@Override标记，但这个错误出现在接口声明上，应该出现在实现类对应的方法上

**Comment by kerie** [comment]
@pugwoo 提供一下代码和IDE版本，我们复现一下。

**Comment by ZhangZhenfang** [comment]
我也遇到了这个问题，定义的抽象方法报这样的错
