### ISSUE TITLE
这个算bug吗，所有的hashmap都提示了.....集合初始化时，指定集合初始值大小。

### ISSUE THREAD

**Issue by piglingcn** [alibaba/p3c#370]
集合初始化时，指定集合初始值大小。 说明：HashMap使用如下构造方法进行初始化，如果暂时无法确定集合大小，那么指定默认值（16）即可。

**Comment by cyberdak** [comment]
不算，这个不是提示bug，它是major。表示可以优化的点。

**Comment by kerie** [comment]
这是p3c规则扫描出结果，不是bug。
要求HashMap使用构造方法进行初始化时指定集合大小，如果暂时无法确定，那么指定默认值（16）。
