### ISSUE TITLE
如何进行更精确的分层?

### ISSUE THREAD

**Issue by dyj2012** [alibaba/p3c#375]
在分层的时候如果是大的业务模块会单独拆分出一个工程,但是如果在一个工程下要分更细的业务,是在每个技术层下再按照每个业务模块分?还是先分业务模块再在模块下建立每个技术层呢?规范里面只对技术上分层做了建议,没有对这种情况做一些建设性的意见

**Comment by xuantan** [comment]
你好，这种问题即使放在业界，也是仁者见仁智者见智，没有统一的标准答案。
