### ISSUE TITLE
关于插件和开发手册一点建议

### ISSUE THREAD

**Issue by jianxia612** [alibaba/p3c#377]
手册确实不错，插件也是一个不错的工具；个人觉得应该有个示例项目 demo_p3c_project，可以针对每一类强制条款写上相关代码，同时把相关条款注释上。这样有利于更多人推广和使用，现在虽然有了手册，个人感觉真正能够按照实际规范目前不太多吧！期望能够更进一步！

**Comment by kerie** [comment]
@yangguanbao 可以考虑一下

**Comment by jianxia612** [comment]
最近在整合部分框架，特地了解一些 **O,我看过文章 http://www.blogjava.net/vip01/archive/2013/05/25/92430.html 总结很透彻，如下图
![image](https://user-images.githubusercontent.com/10516256/44577779-7d27f780-a7c4-11e8-9f7c-ca12611d6ee8.png)
但是人们的期望的是如下的：
![image](https://user-images.githubusercontent.com/10516256/44577825-9b8df300-a7c4-11e8-9cca-65dc41239acd.png)

**Comment by yangguanbao** [comment]
https://detail.tmall.com/item.htm?spm=a230r.1.14.40.7dee7d6bwpO82U&id=575107529181&ns=1&abbucket=20

《码出高效》的源码即将1个月后公布，到时候提供这样的模板工程。

**Comment by yangguanbao** [comment]
当初没有标识PO和BO在图上的原因是层与层之间的转换，并不是惟一确定这是什么类型的O
