### ISSUE TITLE
STS自动修复【在if/else/for/while/do语句中必须使用大括号，即使只有一行代码，避免使用下面的形式：if (condition) statements;】没有效果

### ISSUE THREAD

**Issue by g1335333249** [alibaba/p3c#380]
STS版本
Spring Tool Suite 

Version: 3.9.4.RELEASE
Build Id: 201804120921
Platform: Eclipse Oxygen.3a (4.7.3a)

**Comment by g1335333249** [comment]
在单项目中是可以使用的，maven聚合工程中不能检索父工程的项目解决子项目的错误

**Comment by xuantan** [comment]
麻烦提供一下截图
