### ISSUE TITLE
建议导出代码规范检查结果

### ISSUE THREAD

**Issue by oldroot** [alibaba/p3c#381]
建议在代码插件的检查结果页，增加导出按钮，导出当前的检查结果。如果只是在插件中显示检查结果，则只是一个代码辅助工具，只能帮助开发人员提升编码能力。而检查结果报告可以在团队内流转，可用于代码质量提升和研发管理。为方便使用，可以导出多种格式的检查报告，如pdf,htm,word等。

**Comment by xuantan** [comment]
有此功能，如图：
![Uploading image.png…]()
