### ISSUE TITLE
是否是异常做流程控制，如果不用需要怎么返回值？

### ISSUE THREAD

**Issue by duzhi** [alibaba/p3c#386]
大家好：
关于异常，一个描述是“异常不要用来做流程控制”，一个是“应用内部推荐异常抛出”。
很疑惑，在 service 层中，会有各种请求参数不满足条件，或者系统不满足条件的情况，如果不用异常，怎么返回业务错误码?在 service 方法统一加参数吗
如：
public Order createOrder(..., BizError bizError){
// 由于Order 返回值无法（如果强行增加业务无关字段，是否侵入性太强）带错误信息，不用异常，如何返回错误码，是否通过增加BizError 参数来达到目的？
}

附：

二、异常日志
(一)异常处理

2. 【强制】异常不要用来做流程控制，条件控制。
说明：异常设计的初衷是解决程序运行中的各种意外情况，且异常的处理效率比条件判断方式
要低很多。

12. 【参考】对于公司外的 http/api 开放接口必须使用“错误码”；而应用内部推荐异常抛出；
跨应用间 RPC 调用优先考虑使用 Result 方式，封装 isSuccess()方法、“错误码”、“错误简
短信息”。
说明：关于 RPC 方法返回方式使用 Result 方式的理由：
1）使用抛异常返回方式，调用方如果没有捕获到就会产生运行时错误。
2）如果不加栈信息，只是 new 自定义异常，加入自己的理解的 error message，对于调用
端解决问题的帮助不会太多。如果加了栈信息，在频繁调用出错的情况下，数据序列化和传输
的性能损耗也是问题。

**Comment by xuantan** [comment]
首先，如果是应用内，不需要错误码。
如果是应用间调用，最好在业务方法的外层做异常到错误码的转化封装。

**Comment by duzhi** [comment]
@xuantan 你好，“如果是应用内，不需要错误码。”，那是用异常吗？这跟文档描述的似乎不一致。
