### ISSUE TITLE
建表规约中的 “被动更新” 如何理解？

### ISSUE THREAD

**Issue by Sun-FreePort** [alibaba/p3c#387]
> 9. 【强制】表必备三字段：id, gmt_create, gmt_modified。 
> 说明：其中id必为主键，类型为unsigned bigint、单表时自增、步长为1。gmt_create, gmt_modified的类型均为datetime类型，前者现在时表示主动创建，后者过去分词表示被动更新。

这里的主动、被动怎么理解？

感觉我现在的理解进入了误区。

举例：
 - 一款游戏，我登录后通过用户面板，手动更新了“昵称”，这算是 User 表的主动更新吧，那我该更新哪个字段呢。
 - 登录的同时，新增了一条登录日志，这算是派生的新增操作，它是被动创建出来的，似乎也不符合“主动创建”的规范。
 - 目前从语义上，我很难直接领会这两个字段的涵义区别。

常用语言：PHP、Python
常用数据库：MySQL

**Comment by xuantan** [comment]
收到，我们会将说明语句改为”.....前者现在时表示主动式创建，后者过去分词表示被动式更新。“
