### ISSUE TITLE
IDEA 插件：注解没有提示 “注释缺少@author信息”

### ISSUE THREAD

**Issue by pexcn** [alibaba/p3c#389]

**Comment by xuantan** [comment]
麻烦提供下截图

**Comment by pexcn** [comment]
### Annotation
![anno](https://user-images.githubusercontent.com/4590439/46651608-2db25500-cbd3-11e8-8e97-0d62ca983fc8.png)

### Class
![class](https://user-images.githubusercontent.com/4590439/46651609-2db25500-cbd3-11e8-832e-5dd40cc080f1.png)

**Comment by xuantan** [comment]
@kerie 看一下。

**Comment by openshell** [comment]
![image](https://user-images.githubusercontent.com/23378811/56121962-dfc44280-5fa3-11e9-9ace-67cbeb7a1817.png)
大佬们这是什么情况

**Comment by 1346735074** [comment]
@openshell 类上添加
```
/**
 * @author <作者>
 * @since <版本>
 */
```

**Comment by openshell** [comment]
> @openshell 类上添加
> 
> ```
> /**
>  * @author <作者>
>  * @since <版本>
>  */
> ```

谢谢啦 ，我知道为啥了 是因为我第一排注释星号中间多了个空格。
