### ISSUE TITLE
关于“表必备三字段”中的“单表时自增”是啥意思？

### ISSUE THREAD

**Issue by dslztx** [alibaba/p3c#393]
关于“表必备三字段”中的“单表时自增”是啥意思？谢谢

**Comment by qiaoyahao** [comment]
同问！很疑惑！“单表时“是什么意思？

**Comment by qiaoyahao** [comment]
顺便想问一下 这种自增列的主键 考虑安全性（比如：有个接口获取用户信息直接提供用户主键并不安全），提供给前端时如何处理比较合适，是不是再冗余一个uuid列？有没有其它做法

**Comment by 89376875** [comment]
我们这边使用token令牌，相当于把用户id加密一下


原始邮件
发件人:qiaoyahaonotifications@github.com
收件人:alibaba/p3cp3c@noreply.github.com
抄送:Subscribedsubscribed@noreply.github.com
发送时间:2018年10月19日(周五) 17:44
主题:Re: [alibaba/p3c] 关于“表必备三字段”中的“单表时自增”是啥意思？ (#393)


顺便想问一下 这种自增列的主键 考虑安全性（比如：有个接口获取用户信息直接提供用户主键并不安全），提供给前端时如何处理比较合适，是不是再冗余一个uuid列？有没有其它做法

**Comment by qiaoyahao** [comment]
> 我们这边使用token令牌，相当于把用户id加密一下 原始邮件 发件人:qiaoyahaonotifications@github.com 收件人:alibaba/p3cp3c@noreply.github.com 抄送:Subscribedsubscribed@noreply.github.com 发送时间:2018年10月19日(周五) 17:44 主题:Re: [alibaba/p3c] 关于“表必备三字段”中的“单表时自增”是啥意思？ (#393) 顺便想问一下 这种自增列的主键 考虑安全性（比如：有个接口获取用户信息直接提供用户主键并不安全），提供给前端时如何处理比较合适，是不是再冗余一个uuid列？有没有其它做法 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

谢谢！想进一步问问比如有个获取某一个用户的信息接口/user/{id} 你们是/user/{token}这样处理吗？

**Comment by xuantan** [comment]
这里的单表是对应阿里分库分表来说的，未进行分表的话指的就是单表。
单表时自增 指的就是单表情况下主键id自增。

**Comment by dslztx** [comment]
好的，谢谢
