### ISSUE TITLE
如何对一个包进行屏蔽检查?

### ISSUE THREAD

**Issue by DreamBroke** [alibaba/p3c#402]
我们的项目中有一个包的代码是由一个工具自动生成的，考虑到未来可能存在删掉这个包后重新自动生成的可能，因此不希望对这个包中的代码进行检查和改动。
因此请问该如何对一个包进行屏蔽检查呢？

**Comment by xuantan** [comment]
你好，对整个包进行屏蔽检查我们暂时不支持。
