### ISSUE TITLE
代码样式和代码注释模板支持idea吗？

### ISSUE THREAD

**Issue by nestingLee** [alibaba/p3c#404]
p3c-formatter目录下的eclipse-codestyle.xml和eclipse-codetemplate.xml 支持idea吗？
导入idea后，格式化变为如下格式了

`@SpringBootApplication public class AngelaApplication {

    public static void main(String[] args) {
        SpringApplication.run(AngelaApplication.class, args);
    }
}`

另外感觉注释模板 感觉跟eclipse默认的模板区别不大。

**Comment by xuantan** [comment]
你好，暂时不支持IDEA。

**Comment by gezhiwei8899** [comment]
idea无法导出模板么？

**Comment by yansheng836** [comment]
see https://github.com/alibaba/p3c/issues/507
