### ISSUE TITLE
将方法名“修改为小写驼峰命名”，结果不合理

### ISSUE THREAD

**Issue by ijliym** [alibaba/p3c#409]
比如，有个方法名为 **LowerCamelCaseMethodName**，“修改为小写驼峰命名”之后，方法名修改为 **lowercamelcasemethodname**，即全部小写。
应该添加一个判断：如果方法名的第一个字母是大写字母，则只先将第一个字母改为小写。
![image](https://user-images.githubusercontent.com/43025881/48598166-72809700-e99c-11e8-878c-fd3ca94a57fd.png)
![image](https://user-images.githubusercontent.com/43025881/48598181-83310d00-e99c-11e8-86af-1cf13c9447b2.png)

**Comment by xuantan** [comment]
@SeanCai 看下

**Comment by ijliym** [comment]
期待！

**Comment by ijliym** [comment]
谢谢！
