### ISSUE TITLE
给个选项，查出来不要报错呀

### ISSUE THREAD

**Issue by 908875137** [alibaba/p3c#412]

**Comment by xuantan** [comment]
具体问题描述和截图发一下

**Comment by 908875137** [comment]
抱歉，抱歉，之前每次插件检查出来的问题，有的直接在项目里显示的ERROR，因为有些代码是别人的，我也不能改，没法编译，我都是重启IDEA，后来找到地方可以去除这些提示了。  这个Issue可以删了。。。。
