### ISSUE TITLE
手册里面的字体蛮好的,能给大家推荐一下吗?

### ISSUE THREAD

**Issue by jliu666** [alibaba/p3c#413]
手册里面的字体蛮好的,能给大家推荐一下吗?编码的时候字体选择哪些比较好?

**Comment by yangguanbao** [comment]
感谢对于手册的支持，如果是印刷版，那是WORD的字段。至于发布在PDF上，当时，特地选择了一种版权公开的等宽字体，好像是FERI。《码出高效》彩色印刷的字体是出版社字库里的。
至于平时编程使用的是：
![image](https://user-images.githubusercontent.com/25759061/49340795-b2739980-f67f-11e8-8aa3-600863771571.png)
