### ISSUE TITLE
复杂条件语句的判断规则(AvoidComplexConditionRule)

### ISSUE THREAD

**Issue by 1993heqiang** [alibaba/p3c#417]
原规则中的XPATH:
```
private static final String XPATH = "(//IfStatement/Expression"
        + "|//ConditionalExpression[@Ternary = 'true']/PrimaryExpression)"
        + "[count(.//ConditionalAndExpression) + count(.//ConditionalOrExpression) > 1]";
```
1.为什么是count(.//ConditionalOrExpression) > 1？我觉得这里表达的意思应该是(count(.//ConditionalAndExpression) + count(.//ConditionalOrExpression)) > 1；
2. //IfStatement/Expression 这样写提示的覆盖范围并不是整个条件表达式；
例如:
本规则的第一个测试用例:
```
	public class Example {
	    public int fn1(int a, int b, int c) {
	    	if (a == 0 || (b !=0 && c > 0)) {
	    	    return 1;
	    	}
	    	return 0;
	    }

	    public int fn2(int a, int b, int c) {
	    	return (a == 0 || b != 0 && c > 0) ? 1 : 0;
	    }
	}
```
fn1方法的if判断条件，提示信息的下划线只有在a的下面有，而非整个if表达式

**Comment by fw8899** [comment]
1. 原表达式count(.//ConditionalAndExpression) + count(.//ConditionalOrExpression) > 1跟(count(.//ConditionalAndExpression) + count(.//ConditionalOrExpression)) > 1是一致的，"+"优先级高于">"
2. 划线提示的是//IfStatement/Expression节点，即if中的条件”a == 0 || (b !=0 && c > 0)“，是正常的。@1993heqiang 能提供一下具体截图吗

**Comment by 1993heqiang** [comment]
![image](https://user-images.githubusercontent.com/19889378/52998604-a74e2f80-345e-11e9-9725-0766921bc27e.png)
提示信息的下划线只有在a的下面有，而非整个if表达式 @fw8899
