### ISSUE TITLE
SONAR集成P3C，IDE使用规则生效问题

### ISSUE THREAD

**Issue by stoneljq** [alibaba/p3c#420]
老师，您好~
**目标**：在sonarQube平台上集成p3c的规则，IDE能够自动识别sonarQube配置的代码规则。
**过程**：已经在sonarQube平台上集成了p3c的规则，且项目构建后，在平台上能看到p3c扫描出来的结果。对IDE（idea、ecplise）配置连接sonarQube，代码开发阶段实时扫描代码质量
**结果**：在平台上配置了p3c和其默认的规则后，IDE只能识别到默认的规则，p3c的规则未生效，请问这是哪里配置有问题吗？

**Comment by xuantan** [comment]
你好，IDE连接sonarQube这种方式我们也没有使用过。建议直接用IDE、eclipse的P3C插件。
