### ISSUE TITLE
建议方法参数的注释换行并缩进，这样可读性更强！

### ISSUE THREAD

**Issue by Wu-Jianqiang** [alibaba/p3c#422]
建议方法参数的注释换行并缩进，这样可读性更强，需要修改的配置 如下：
&lt;setting id="org.eclipse.jdt.core.formatter.comment.indent_parameter_description" value="true"/>
&lt;setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_for_parameter" value="insert"/>

**Comment by xuantan** [comment]
@imu2008 看下

**Comment by imu2008** [comment]
@Wu-Jianqiang 非常感谢你的提议，已修复。
