### ISSUE TITLE
新建线程池的时候，支持lambda

### ISSUE THREAD

**Issue by myzhan** [alibaba/p3c#430]
用 lambda 的时候，代码规约检查有提示，用 ThreadFactory 的时候，idea 自己的检查有提示。

![image](https://user-images.githubusercontent.com/953781/49911602-f6f20700-fec1-11e8-8b46-7f15b0b8e9aa.png)

![image](https://user-images.githubusercontent.com/953781/49911653-2acd2c80-fec2-11e8-84f8-e77b57493354.png)

**Comment by kerie** [comment]
@SeanCai 帮忙看一下

**Comment by SeanCai** [comment]
@myzhan 下一版修复，建议使用 r -> {} 的形式，更简洁，目前是支持的

**Comment by STRRL** [comment]
IDEA插件版本2.0.0，即使使用 guava 的 ThreadFactoryBuilder 也是会提示这个。

也希望改进一下～
