### ISSUE TITLE
是否可以加入限制lombok @AllArgsConstructor 在对外的、应用间服务中的使用

### ISSUE THREAD

**Issue by hduyyg** [alibaba/p3c#435]
@AllArgsConstructor 会自动添加一个全参构造方法，使用用户可以通过new Object（x，y）的方式创建实例。
在应用之间的服务中，如果服务端在modle上使用了这个注解，客户端使用new的方式生成类型，服务端对model作出新增字段、调整顺序等行为时，就会迫使客户端更新原本没必要更新的代码。

我们不能指望服务端开发人员能都知道不要做出这种影响用户的修改，因此，可以考虑是否建议在编码时不要对对外的model使用@AllArgsConstructor注解

**Comment by hduyyg** [comment]
当然，对内其实也不建议使用，除非能够确保model字段不会更改。
否则一旦遇到需要增加model信息，添加字段时，就需要更改项目中使用全参构造的地方

一点浅见，望指点

**Comment by yangguanbao** [comment]
@AllArgsConstructor
会生成一个包含所有变量，同时如果变量使用了NotNull annotation ， 会进行是否为空的校验， 
全部参数的构造函数的自动生成，该注解的作用域也是只有在实体类上，参数的顺序与属性定义的顺序一致。

________
不建议使用。重载可能出现不可控的情况，构造方法可以放在文末，但是需要显式定义，况且多个构造方法，可能需要处理部分共同逻辑。
