### ISSUE TITLE
代码改了，PDF文档升级更新了吗？

### ISSUE THREAD

**Issue by diguage** [alibaba/p3c#437]
RT

**Comment by yangguanbao** [comment]
近期我们会进行PDF的更新，不过，你可以帮我们想一想版本的名字：
终极版》完美版》详尽版》？

**Comment by ljq2731** [comment]
z

> 近期我们会进行PDF的更新，不过，你可以帮我们想一想版本的名字：
> 终极版》完美版》详尽版》？

终极版第一版

**Comment by BAIRIQIYA** [comment]
> 
> 
> 近期我们会进行PDF的更新，不过，你可以帮我们想一想版本的名字：
> 终极版》完美版》详尽版》？

终极版》完美版》详尽版》究极版》超究极版

**Comment by diguage** [comment]
> 近期我们会进行PDF的更新，不过，你可以帮我们想一想版本的名字：
> 终极版》完美版》详尽版》？

这种命名办法扩展性太差了。私以为不是工业级的玩法。现在业界流行的一个版本号规范是 **“语义化版本”**。我建议遵循这个约定：

[语义化版本 2.0.0 | Semantic Versioning](https://semver.org/lang/zh-CN/)

**Comment by yangguanbao** [comment]
语义化版本一直是存在的。
![image](https://user-images.githubusercontent.com/25759061/54585450-18303980-4a55-11e9-9d76-217889fda330.png)
4.1号愚人节，我们发布一版吧。

**Comment by diguage** [comment]
> 语义化版本一直是存在的。

哪为啥前面还要标注个0、1、2…？

另外，里面的 `Java` 和 `V`，一会儿大写，一会儿小写，不够规范啊。（我太强迫症了，😜）

**Comment by yangguanbao** [comment]
这只是我的个人电脑本地文件命名。
在对外版本中，Java的J是大写
包路径的java的j是小写。
