### ISSUE TITLE
p3c-formatter里的模板导入eclipse时报错

### ISSUE THREAD

**Issue by iamfuzi** [alibaba/p3c#439]
p3c-formatter 里的模板导入eclipse的时候报错，2个模板都无法导入

**Comment by xuantan** [comment]
麻烦提供下eclipse的版本及报错信息。

**Comment by iamfuzi** [comment]
eclipse Neon.3 Release (4.6.3)
code style:
![image](https://user-images.githubusercontent.com/14269237/50941087-6f96b400-14be-11e9-957a-7667c941dc07.png)

code tempate:
![image](https://user-images.githubusercontent.com/14269237/50941129-981eae00-14be-11e9-80eb-a2c25e47bb11.png)
