### ISSUE TITLE
对数字开头的网站域名的检测，是否合理？

### ISSUE THREAD

**Issue by yemx910501** [alibaba/p3c#443]
网址：www.52test.online
由于Java包名不能以数字开始，从网上得到的建议是使用下划线开始，即：_52test。
但是阿里编码规约提示：包名【online._52test.oes.mapper】应全部为小写字母和数字组成。
请问此种情况下，如何命名包名才能检测通过呢？

**Comment by kerie** [comment]
我们这个规则初衷是为了让包名的可读性更好一些，所以不允许数字开头。
你写工程时，不一定需要严格遵循网址，也可以使用其他英文字母开头的包名。
