### ISSUE TITLE
Eclipse，代码扫描后报错：Problems occurred when invoking code from plug-in: "org.eclipse.jdt.core".

### ISSUE THREAD

**Issue by 1993heqiang** [alibaba/p3c#444]
Eclipse版本：Version: 2018-12 (4.10.0)   Build id: 20181214-0600
报错详情：
![image](https://user-images.githubusercontent.com/19889378/51007505-b8b03c00-1582-11e9-8e0c-bb009ca616dd.png)
这个错误虽然不影响使用，但是有强迫症，有报错就想解决。。。

**Comment by 1993heqiang** [comment]
![image](https://user-images.githubusercontent.com/19889378/51576538-9e1a8300-1ef1-11e9-8ba2-f1eb55385943.png)
![image](https://user-images.githubusercontent.com/19889378/51576554-b2f71680-1ef1-11e9-9c50-cbccdda7f354.png)

**Comment by imu2008** [comment]
@1993heqiang 你是使用p3c分析过一次之后删除或移动过文件么？这些错误可以直接CTRL+A，全选删除后重新构建应该就没了吧~

**Comment by 1993heqiang** [comment]
没有，只要扫描就有这些错误。。。这个只出现Version: 2018-12 (4.10.0) Build id: 20181214-0600，我用老版本没这个问题，所以不知道怎么回事

**Comment by imu2008** [comment]
@1993heqiang 那这个kotlin的插件是你自己安装的么？重装一下这个插件试试吧~

**Comment by 1993heqiang** [comment]
@imu2008 第二个应该是和Kotlin插件有关，我把Kotlin插件卸载后，第一个错误依旧存在，应该和Kotlin没关系。。。

**Comment by 1993heqiang** [comment]
你可以下一个最新的Eclipse试一下，如果你那边没什么问题，可能就是我的IDE的问题。。。

**Comment by imu2008** [comment]
@1993heqiang 我试过了，是OK的。第一个jpt那个又是什么插件。。

**Comment by 1993heqiang** [comment]
p3c/eclipse-plugin/com.alibaba.smartfox.eclipse.feature/feature.xml你看一下这个文件，那个是P3C依赖的插件
