### ISSUE TITLE
《日志规约》别字修改

### ISSUE THREAD

**Issue by yyl4ever** [alibaba/p3c#445]
《日志规约》部分，第四条，应为“建议”，截图如下：
![image](https://user-images.githubusercontent.com/23069118/51082783-f65ec180-1748-11e9-952f-10e903feb6f2.png)

**Comment by yangguanbao** [comment]
阿里巴巴内部版本已经修正，外部版本我们会短期内再出一个PDF版本。我先关掉喽。
