### ISSUE TITLE
pmd中messages_en.xml规则中英字符混杂bug

### ISSUE THREAD

**Issue by hanyidreamer** [alibaba/p3c#448]
利用pmd规则写的程序，在只支持中文的服务器对部分规则校验出现错误，系messages_en.xml中英字符混杂导致。

**Comment by kerie** [comment]
@hanyidreamer 可以提供下详细的错误信息吗？
如果你知道怎么修改，也可以欢迎提交pull request。

**Comment by hanyidreamer** [comment]
@kerie 已提交Fixed #448 pull request。

**Comment by xuantan** [comment]
已合并，Thanks!
