### ISSUE TITLE
关于枚举的字段缺少注释信息

### ISSUE THREAD

**Issue by hopana** [alibaba/p3c#449]
有些枚举字段可能没有参数，所以需要注释，比如SPRING,SUMMER, AUTUMN,WINTER等，但是有些枚举字段由于业务需要，本身已经包含name，desc, remark等参数信息，比如：SPRING(1, "春天"),SUMMER(2, "夏天"), AUTUMN(3, "秋天"),WINTER(4, "冬天")，这种还提示我加注释未免有点啰嗦，关键是枚举是用逗号分隔的，加注释的话看起来很不美观，而且由于每个人格式化可能不一样，造成一格式化，看起来乱糟糟的，所以一般我们倾向于构造函数里面添加说明字段。。。。。所以强制枚举加注释我感觉不合理，起码要看情况。

**Comment by kerie** [comment]
@yangguanbao 帮忙看一下

**Comment by wenbochang888** [comment]
这个我也同意不要强制，只做推荐。
类似如下，不加注解，也很清晰明了
`SUCCESS("200", "请求成功"),
MISSING_PARAM_EXCEPTION("400", "缺少参数"),
NETWORK_EXCEPTION("500", "网络出错")；`

**Comment by yangguanbao** [comment]
枚举类是非常严肃的类，一旦固定下来即不会修改，注释更多地说明什么样的业务场景，要注意什么，它的背景是什么。相信我，这个注释真的需要认真写一下。
