### ISSUE TITLE
代码格式页的正例代码存在缩进问题

### ISSUE THREAD

**Issue by zqq90** [alibaba/p3c#453]
https://github.com/alibaba/p3c/blame/e956b1225e5025295f5af92c9f876fd52a5672db/p3c-gitbook/%E7%BC%96%E7%A8%8B%E8%A7%84%E7%BA%A6/%E4%BB%A3%E7%A0%81%E6%A0%BC%E5%BC%8F.md#L54

这里的注释前面应该是多了一个空格, 请查证,
除此之外, 还请更正其他代码段的缩进问题

**Comment by xuantan** [comment]
感谢建议。
插件提示里的示例代码是有缩进的，gitbook文档里的缩进问题可以忽略。
