### ISSUE TITLE
HashMap版本错误

### ISSUE THREAD

**Issue by wenbochang888** [alibaba/p3c#455]
集合处理的第七条这样写道：

> 
9. 【推荐】集合初始化时，指定集合初始值大小。
说明： HashMap 使用 HashMap(int initialCapacity) 初始化，
正例： initialCapacity = (需要存储的元素个数 / 负载因子) + 1。注意负载因子（即loader
factor）默认为 0.75， 如果暂时无法确定初始值大小，请设置为 16（即默认值）。
反例： HashMap 需要放置 1024 个元素，由于没有设置容量初始大小，随着元素不断增加，容
量 7 次被迫扩大， **resize 需要重建 hash 表**，严重影响性能。
>
反例这里指出，HashMap在resize的时候需要重建hash表。
在JDK1.8之后HashMap每次resize不需要重新hash了，具体可看这边博肯
[基于JDK1.8的HashMap分析](https://www.cnblogs.com/wenbochang/p/8458756.html)
在JDK1.7之前包括1.7需要重新hash

建议标出JDK版本，或者直接去除这个建议(因为在1.8之后有很大的优化，几乎可以忽略扩容带来的性能消耗)。

**Comment by xuantan** [comment]
@yangguanbao 看下

**Comment by wenbochang888** [comment]
同样。并发处理第14条：
14. 【参考】 HashMap 在容量不够进行 resize 时由于高并发可能出现死链，导致 CPU 飙升，在
开发过程中可以使用其它数据结构或加锁来规避此风险。
JDK1.8之后不会出现cpu飙升，死循环情况
具体可看博文：[HashMap在JDK1.8中并发操作，代码测试以及源码分析](https://www.cnblogs.com/wenbochang/p/9425541.html)

**Comment by yangguanbao** [comment]
这个没有问题的，更多沟通，已经与题主邮件
