### ISSUE TITLE
现在有集成到Jenkins的插件吗

### ISSUE THREAD

**Issue by chuenfaiy** [alibaba/p3c#456]
如题，现在是有集成到Jenkins的规约插件

**Comment by xuantan** [comment]
https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F
