### ISSUE TITLE
idea-plugin”编码规约扫描“可以用自定义的inspections profile吗

### ISSUE THREAD

**Issue by TryXD** [alibaba/p3c#457]
在idea中右键使用”编码规约扫描“，或commit时勾选“Alibaba Coding Guidelines”，发现检测的是**所有**的阿里规约，显示用的是“Alibaba Coding Guidelines” Profile，貌似不能调整使用在“Editor -> Inspections“中自定义的myProfile。      

自定义的profile取消了一些Ali-Check的检查项目，通过”Analyze->Inspect Code“功能，是能用myProfile运行可以看到已选检测项的结果，但里面包含了idea其他的检核项。  

因为更偏好单纯使用阿里的规约，特别是commit前的检核，所以咨询这个问题。    
以下是两种执行结果截图，可以看到myProfile结果很少。

![image](https://user-images.githubusercontent.com/11208943/53283177-53ed2180-377d-11e9-8bef-96c4deb400fe.png)
![image](https://user-images.githubusercontent.com/11208943/53283179-5e0f2000-377d-11e9-8f84-f04d80e1e195.png)

**Comment by xuantan** [comment]
你好，目前不支持。
