### ISSUE TITLE
eclipse扫描和快速修正时报错

### ISSUE THREAD

**Issue by liuwa** [alibaba/p3c#461]

**Comment by liuwa** [comment]
![b6e53266-f96c-4f6b-94a7-3d3f7501771d](https://user-images.githubusercontent.com/32085087/53484335-9173e680-3abe-11e9-89ff-000c7be3063f.png)
在 扫描和快速修正时报如上的错误

**Comment by imu2008** [comment]
@liuwa 辛苦提供下具体的log信息，谢谢
