### ISSUE TITLE
关于 @Deprecated方法的判断

### ISSUE THREAD

**Issue by JackiePenghe** [alibaba/p3c#468]
在使用手机震动权限时，发现一个问题。该问题应该在类似的场景中都有出现。
如蓝牙BLE的搜索BLE设备的方法
```java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP) {
    bluetoothAdapter.getBluetoothLeScanner().startScan()；
} else {
    bluetoothAdapter.startLeScan()；
}
``` 

![image](https://user-images.githubusercontent.com/20922322/54248309-283caa80-4577-11e9-97f1-3111c02ea5eb.png)
像这样的API，在高版本中有改动，但低版本被@Deprecated确实又必须使用时，增加防提示注解还是会提示@Deprecated删除线。这个还是优化一下吧。

**Comment by xuantan** [comment]
在IDEA中可以直接关闭掉这条规则的检测。
