### ISSUE TITLE
如何解决重写过时方法问题？

### ISSUE THREAD

**Issue by slievrly** [alibaba/p3c#470]
![image](https://user-images.githubusercontent.com/8758457/54336788-01aa6c80-4668-11e9-9341-9ca0d07598e2.png)
![image](https://user-images.githubusercontent.com/8758457/54336985-85645900-4668-11e9-82dc-ee0b0d9af3d3.png)

![image](https://user-images.githubusercontent.com/8758457/54336810-125ae280-4668-11e9-938a-fb06c676a653.png)
如图我们需要实现jdk中的接口类，但接口类方法上标注了过时，导致我们实现此方法时报重写过时方法问题，影响了我们代码质量，希望优化规则。

**Comment by xuantan** [comment]
你好，可以在IDEA中关闭掉针对这条规则的检测。
