### ISSUE TITLE
[question]包名问题

### ISSUE THREAD

**Issue by hbwhypw** [alibaba/p3c#473]
想问一下，如果遇到包名含义是由两个单词组成的情况，如何处理？

> (一) 命名风格 
> ……
> 9. 【强制】包名统一使用小写，点分隔符之间有且仅有一个自然语义的英语单词

比如，包名是data structure，根据规范要求应该是com.xxxx.data.structure，其含义是某公司下的数据下的结构，而我想表达的是，某公司下的数据结构。

**Comment by yangguanbao** [comment]
可以参考JDK的命名：
![image](https://user-images.githubusercontent.com/25759061/54584489-7576bb80-4a52-11e9-87d2-92956af0cf57.png)
这个理解为一个原子单词即可。
但是包名不用驼峰，也不用下划线。
