### ISSUE TITLE
《阿里巴巴Java开发手册（详尽版）》数据库id生成的问题

### ISSUE THREAD

**Issue by iportman** [alibaba/p3c#480]
文档中以下部分我觉得不合理或可以改善
1. id 在分布式系统中，最好是用全局的唯一id区分，分库或做数据迁移的时候都不怕冲突，有时候定位问题也方便一点（如果生成id时，有按不同库，不同表规则区别的话）
2. gmt_create中的gmt我的理解应该是格林威治时间，不能强制使用gmt，如果只是做国内业务的话，东8时区的时间可读性更好
3. 应该使用timestamp替换datetime，节省存储空间，并且在新增和更新记录时，自动更新create和update字段
```sql
CREATE TABLE IF NOT EXISTS `demo_table` (
  `dbid` BIGINT(20) NOT NULL,
  `fid` BIGINT(20) NOT NULL,
  `name` VARCHAR(45) NULL COMMENT '演示列名称',
  `code` VARCHAR(45) NULL COMMENT '演示列编码',
  `create_time` TIMESTAMP(3) NULL DEFAULT current_timestamp(),
  `update_time` TIMESTAMP(3) NULL DEFAULT current_timestamp() ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`dbid`, `fid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_bin
COMMENT = '演示表';
```

>【强制】表必备三字段：id, gmt_create, gmt_modified。 说明： 其中 id必为 主键，类型必为 主键，类型bigint unsigned、单表时自增步长为 、单表时自增步长为 1。gmt_create, gmt_modified的类型均为 的类型均为 datetime类型，前者现在时表示主动创建后过去分词被 类型，前者现在时表示主动创建后过去分词被 动

**Comment by xuantan** [comment]
@yangguanbao 看下

**Comment by yangguanbao** [comment]
第一个问题，阿里巴巴使用TDDL的sequence强制生成全局惟一的分布式id放到各个表中。
第二个问题，仅仅是一个约定俗成。
第三个问题，因为time_stamp的时间表达限制为2037年。
