### ISSUE TITLE
请问一下，p3c-pmd如何运行测试

### ISSUE THREAD

**Issue by leotyndale** [alibaba/p3c#481]
你好，下图这些命令都尝试了一下，无法像P3c-idea的runIde一样运行测试，请问p3c-pmd有什么办法建立Demo运行测试吗

![image](https://user-images.githubusercontent.com/13491298/54666973-35810880-4b26-11e9-89b0-b9e1e65ca8a9.png)

**Comment by xuantan** [comment]
可以参考下wiki
https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F

**Comment by leotyndale** [comment]
> 可以参考下wiki
> https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F

抱歉，能看的资料都找过了，包括发布的相关视频，还是没有找到像P3c-idea的runIde一样运行测试P3C-PMD的方法，麻烦帮忙看一下这个能否像runIde一样运行测试，谢谢
