### ISSUE TITLE
常量命名问题

### ISSUE THREAD

**Issue by Bohr-H** [alibaba/p3c#483]
求教   为什么我申明的常量它一直说我不符合lower camel case风格   还是说我对常量的理解有问题
![image](https://user-images.githubusercontent.com/29001268/54888877-227e8780-4edc-11e9-9e76-b27e33c3b050.png)
![image](https://user-images.githubusercontent.com/29001268/54888940-9456d100-4edc-11e9-8453-97ea9ff275b7.png)

**Comment by xuantan** [comment]
你好，你声明的不是常量。可以写成
public static final String ADDRESS = xxxxxxx

**Comment by Bohr-H** [comment]
谢谢您的回答   看来是我对常量的理解有误吧   但我记得Java中final修饰的变量就是常量呀  加static是静态常量   这是我之前的理解  那应该是我记错了吧
在 2019年4月2日 +0800 14:17，玄坛 <notifications@github.com>，写道：

你好，你声明的不是常量。可以写成
public static final String ADDRESS = xxxxxxx
