### ISSUE TITLE
定义DO/DTO/VO等POJO类时不要设定任何属性默认值疑问

### ISSUE THREAD

**Issue by pengzai123** [alibaba/p3c#484]
业务里 某个字段新添加的 ,有多个业务dto相关,如果不能给do加默认值,那么所有相关dto都需要检查一遍维护到那个字段,但那个字段只在某一个业务里用到
其他业务dto会转换成Do 然后save进去 会导致字段为null
我们使用的jpa,我的理解:
 do应该和数据库一一对应(即:如果数据库字段是notnul并且有默认值,那么do应该也是需要有默认值的)

**Comment by xuantan** [comment]
@yangguanbao 看下

**Comment by yangguanbao** [comment]
阿里巴巴JAVA开发手册提倡的理念是宁可抛错，绝不错写数据。
默认值如果一旦上层业务出现 BUG，那么数据可能被批量修改，但是监控是未感知到的。
这是经历了事实证明的。
