### ISSUE TITLE
不要在finally块中使用return 解释说明

### ISSUE THREAD

**Issue by beckha** [alibaba/p3c#487]
【强制】不要在finally块中使用return。 
说明：finally块中的return返回后方法结束执行，不会再执行try块中的return语句。 
这里的说明似乎有些歧义，
finally块中的语句是会被最后执行的，try块中的代码块会先于finally中代码块执行。
可否换成try中的return语句返回值不能为外部使用，返回值是finally中return语句的返回值。
// test

public class Main {

    private int i = 0;

    private int f(){
        i += 1;
        return i;
    }

    private int test(){
        try {
            return f();
        } finally {
            return f();
        }
    }

    public static void main(String[] args) {
        var testObj = new Main();
        testObj.test();
        System.out.printf("%d\n", testObj.i);
    }
}

**Comment by xuantan** [comment]
你好，感谢提醒，我们在下一版本《规约》发布时会更新此条目。
