### ISSUE TITLE
`Collection#toArray` should use an empty array

### ISSUE THREAD

**Issue by alex-lx** [alibaba/p3c#491]
IDEA's inspector warned when calling `toArray` with an pre-sized array which conflicts with p3c's rule 5.4

Here's its inspection info
> There are two styles to convert a collection to an array: either using a pre-sized array (like 
c.toArray(new String[c.size()])) or using an empty array (like c.toArray(new String[0]).
In older Java versions using pre-sized array was recommended, as the reflection call which is necessary to create an array of proper size was quite slow. However since late updates of OpenJDK 6 this call was intrinsified, making the performance of the empty array version the same and sometimes even better, compared to the pre-sized version. Also passing pre-sized array is dangerous for a concurrent or synchronized collection as a data race is possible between the size and toArray call which may result in extra nulls at the end of the array, if the collection was concurrently shrunk during the operation.
This inspection allows to follow the uniform style: either using an empty array (which is recommended in modern Java) or using a pre-sized array (which might be faster in older Java versions or non-HotSpot based JVMs).

**Comment by xuantan** [comment]
你好，麻烦贴一下具体的代码。

**Comment by alex-lx** [comment]
@xuantan 
```java
        List<String> list = Arrays.asList("a", "b");
        list.toArray(new String[list.size()]);
```
IDEA version: 2018.3.6
JDK version: hutspot 1.8.0_191

**Comment by xuantan** [comment]
@yangguanbao 看下

**Comment by yangguanbao** [comment]
转数组有四种情况：
1）toArray()，泛型丢失，不推荐。
2）toArray(new T[0]) 泛型存在，并且会在copy时，动态创建与size相同的数组。
3）toArray(数组长度小于集合长度)，空间浪费，强烈不推荐。
3）toArray(list.size());  唯一的问题是高并发场景下，刚刚创建好了一个数组长度为size的数组，结果list增加了一个元素，导致空间浪费，也存在问题。
5）toArray(数组长度大于集合长度），空间浪费，而且有null值的干扰，不推荐。

综合考虑，后续《阿里巴巴JAVA开发手册》修改本条规约，参数为T[0]的数组。

**Comment by yangguanbao** [comment]
@alex-lx 你看一下有没有问题。

**Comment by alex-lx** [comment]
总结的很好 👍

有个小问题：序号 3 重复了。:-)
另外我觉得当数组小于集合时，说“空间浪费”可能会有误解，毕竟立刻会被GC掉。
还有第4点，如果能提一下，并发过程中，list减少了一个元素，也会导致数组后面的控制，能更叫明确一点。

**Comment by yangguanbao** [comment]
```
package collections;

import java.util.ArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.atomic.AtomicLong;

public class ToArrayRunTest {
    public static ArrayList<Long> a = new ArrayList<>(100000);
    public static AtomicLong sum = new AtomicLong(0);

    static {
        for (int i = 0; i < 100000; i++) {
            a.add(Long.valueOf(i));
        }
    }

    public static void main(String[] args) throws InterruptedException, ExecutionException {
        ExecutorService s = Executors.newFixedThreadPool(50);
        CountDownLatch c = new CountDownLatch(1000);
        for (int j = 0; j < 1000; j++) {
            new MyThread(c).start();
        }
        c.await();
        System.out.println(c.getCount());
        System.out.println("sum=" + sum.get()/1000000);
    }

    static class MyThread extends Thread {

        CountDownLatch c;

        public MyThread(CountDownLatch c) {
           this.c = c;
        }

        @Override
        public void run() {
            long start = System.nanoTime();
            a.toArray(new Long[0]);
            //a.toArray(new Long[a.size()]);
            for (int k = 0; k < 1000; k++) {
                a.add(Long.valueOf(1));
            }
            sum.getAndSet(System.nanoTime() - start);
            c.countDown();
        }
    }
}
```
以上代码证明new Long[0]比new Long(size)要快4.6倍。

转数组有四种情况：
1）toArray()，泛型丢失，不推荐。
2）toArray(new T[0]) 泛型存在，并且会在copy时，动态创建与size相同的数组。
3）toArray(数组长度小于集合长度)，空间浪费，即使GC是可能的，但如果是OOM的临界，比较麻烦，强烈不推荐。
4）toArray(list.size()); 唯一的问题是高并发场景下，刚刚创建好了一个数组长度为size的数组，结果list增加了一个元素，导致空间浪费，也存在问题。
5）toArray(数组长度大于集合长度），空间浪费，size()下标处有一个null值，不推荐。

综合考虑，后续《阿里巴巴JAVA开发手册》修改本条规约，参数为T[0]的数组。

**Comment by yangguanbao** [comment]
@alex-lx

**Comment by alex-lx** [comment]
看起来不错

**Comment by liulhdarks** [comment]
你这例子ArrayList得加锁吧，而且在加锁的情况下也不一定快4.6倍，就算不加锁也最多就快1倍多 @yangguanbao

**Comment by sycz** [comment]
sum.**addAndGet**(System.nanoTime() - start); ？？
