### ISSUE TITLE
IDEA 打开大文件时卡死

### ISSUE THREAD

**Issue by XiaoxiangLi** [alibaba/p3c#494]
系统环境: Ubuntu 18.04 + IDEA 2018.3 ~ 2019.01
打开一个[近 4w 行的 java 类](https://github.com/DrKLO/Telegram/blob/master/TMessagesProj/src/main/java/org/telegram/tgnet/TLRPC.java)后，ide 卡死、cpu 100%。
把插件禁用掉就好了。

**Comment by gray035** [comment]
我也是，肯定有bug

**Comment by xuantan** [comment]
你好，目前的确存在这个问题，简单的解决方案是：将实时检测关闭掉。
