### ISSUE TITLE
How to create facade over p3c-pmd?

### ISSUE THREAD

**Issue by clasnake** [alibaba/p3c#495]
Hi, we've adopted the p3c-pmd in our team but we'd love to modify/relax some rules and add our custom rules as well. Our current solution is to fork the p3c-pmd and make modifications directly in our repo. How is it possible for us to just add p3c-pmd as a dependency and add a facade layer on that? How many configurations do we support?

**Comment by xuantan** [comment]
hi，
https://github.com/alibaba/p3c/wiki/FAQ#3-eclipse-pluginidea-plugin%E5%92%8Cp3c-pmd%E4%B8%89%E4%B8%AA%E5%B7%A5%E7%A8%8B%E4%B9%8B%E9%97%B4%E7%9A%84%E5%85%B3%E7%B3%BB

https://pmd.github.io/pmd-6.13.0/

**Comment by clasnake** [comment]
@xuantan Thanks. So if we need to make customizations, your suggestion is that we still fork a version of p3c-pmd and make our own modifications?
