### ISSUE TITLE
@Transactional(readOnly = true)只读事务提示需要添加rollbackfor

### ISSUE THREAD

**Issue by languanghao** [alibaba/p3c#499]
![image](https://user-images.githubusercontent.com/3765379/56546848-1f93b700-65ae-11e9-90a2-3aa0010337af.png)

感觉在只读事务里没有必要设置rollbakfor吧，本身只读事务也无法回滚

**Comment by xuantan** [comment]
@SeanCai 看下

**Comment by SeanCai** [comment]
2.0.0 fixed this issue
