### ISSUE TITLE
重复代码检测感觉过于苛刻

### ISSUE THREAD

**Issue by scauwjh** [alibaba/p3c#500]
例如差不多的几行代码，list里面不同的对象，刚好对象对应的操作方法名和参数一样，然后就提示duplicate，感觉这种情况没必要提示重复

**Comment by HelloSimplelee** [comment]
既然是检测肯定就是通通无疏漏的，企业级代码不可疏忽。

**Comment by xuantan** [comment]
你好，这个是IDE本身提供的功能，不是我们插件提供的。
