### ISSUE TITLE
能否在左侧代码行数那加载一个警告按钮，有时候高亮可能会被忽视

### ISSUE THREAD

**Issue by hnwkz** [alibaba/p3c#505]
因为颜色的问题，有时候检测出来不规范的时候，容易被忽视，所以看看能否像Eclipse的checkstyle那样，在左侧行数那加一个警告之类的图标这样就很清楚了，谢谢

**Comment by hnwkz** [comment]
![image](https://user-images.githubusercontent.com/21251671/57510768-28b8ae00-733a-11e9-9585-38a60eda6338.png)

**Comment by xuantan** [comment]
你好，这是个IDEA显示规范的问题，没办法进行这方面的改造。
