### ISSUE TITLE
是否可以自定义方法检测的长度，想弄成20行检查，现在是80行

### ISSUE THREAD

**Issue by luck-cheng** [alibaba/p3c#506]
是否可以自定义方法检测的长度，想弄成20行检查，现在是80行。

**Comment by arache** [comment]
20行好像太严格了吧～

**Comment by zqq90** [comment]
👍 我想, 贵团队英语一定很不错, 可以给那么多方法想到合适的名字

**Comment by yangguanbao** [comment]
大数据证明20行是行不通的，除了setter/getter，绝大多数代码行数超过20行。
![image](https://user-images.githubusercontent.com/25759061/57674568-2dd76f00-7652-11e9-99bf-aa36dcc67422.png)
