### ISSUE TITLE
在idea中使用eclipse-codestyle.xml格式化注解有问题

### ISSUE THREAD

**Issue by coldplay321** [alibaba/p3c#507]
带注解的成员变量,被eclipse-codestyle.xml这个模版文件格式化后, 会导致注解与变量变成同一行.多人导入模版文件后发现这个问题,希望检查一下是不是模版有问题.

**Comment by SeanCai** [comment]
要用EclipseCodeFormatter导入，不要用Idea直接导入

**Comment by yansheng836** [comment]
> 要用EclipseCodeFormatter导入，不要用Idea直接导入

是**Eclipse Code Formatter**，中间应该有空格的。
