### ISSUE TITLE
关于抽象方法注释的疑问

### ISSUE THREAD

**Issue by Allurx** [alibaba/p3c#508]
在service层有一个接口，我在该service接口里面的每个方法上都写好了详细的javadoc，然后对应的service实现类在处理业务的时候通常会调用一个mapper，该mapper里面的接口一般都是和service一一对应的，问题在于我已经在service的接口上写好了详细的注释，还需要在mapper的每个方法上都写上大致相同的注释吗？这是不是有点重复的感觉。

**Comment by rainbow702** [comment]
有相同的疑惑

**Comment by zhyank** [comment]
显然不需要啊，不过要在实现方法上添加@Override

**Comment by rainbow702** [comment]
> 显然不需要啊，不过要在实现方法上添加@override

是 service  和 mapper ，它们不是  `implements` 的关系

**Comment by Lin-WanCheng** [comment]
@see 类#方法或{@link 类#方法}可以帮助你更快地导航到反向调用和查看对应方法的注释，重复肯定是要避免的，即使是注释

**Comment by xuantan** [comment]
@yangguanbao 看下

**Comment by yangguanbao** [comment]
第一、注释一定不会是重复的。
第二，参加上边的回复，另外，如果是实现一定要加@Override
![image](https://user-images.githubusercontent.com/25759061/66817316-163c4380-ef6e-11e9-8eda-060b355d1813.png)
