### ISSUE TITLE
如何自定义规则class文件行数不超过1000行呢？

### ISSUE THREAD

**Issue by luck-cheng** [alibaba/p3c#509]
/**
 * @author luck
 * check class length in java file
 */
public class ClassLengthTooLongRule extends AbstractAliRule {
}

// 我把github的项目弄了下来尝试自己开发自己的规则，我现在想规定class文件行数不超过1000行，在net.sourceforge.pmd.lang.java.ast包下，并没有找到能相关的，有过来的前辈能指导下吗？

**Comment by Lin-WanCheng** [comment]
如果有个规约条目并支持配置就好了，最近在反思封装时感受到包含20行以上的长逻辑方法的类应该像Go语言那样以包为单位封装，抽成包级方法放在不同的文件，否则即使限定了方法行数，理清一个文件里多个方法的关系一样会花很多时间。

**Comment by xuantan** [comment]
当前开发手册中没有对于类文件行数的限制，不过可以参考方法行数不要超过80这条规约。
