### ISSUE TITLE
希望能支持Netbeans 

### ISSUE THREAD

**Issue by blueholes** [alibaba/p3c#51]
希望能有Netbeans的插件

**Comment by lovewinner** [comment]
举个爪   希望作者开发netbeans的插件

**Comment by SeanCai** [comment]
@blueholes @lovewinner 目前项目组没有使用NetBeans的同学，所以即使能抽出时间来开发插件，也很难保证用户体验，所以希望大家能加入进来开发NetBeans插件

**Comment by qichhhhh** [comment]
同样希望支持能 Netbeans
