### ISSUE TITLE
使用代码样式配置后, 生成的重写方法 @Override注解为什么要跟方法的声明在同一行? 

### ISSUE THREAD

**Issue by biggbuddy** [alibaba/p3c#511]
使用代码样式配置后, 生成的重写方法 @Override注解为什么要跟方法的声明在同一行? 
这个跟一样的代码格式化工具推荐的方式不太一样吧? 

![image](https://user-images.githubusercontent.com/12723408/57822933-45d0ff00-77c8-11e9-8ffc-c64d1301b6fd.png)

**Comment by gundamff** [comment]
用EclipseCodeFormatter导入 不要用idea自带的导入功能
