### ISSUE TITLE
2019.1.2安装出错

### ISSUE THREAD

**Issue by fufenghua** [alibaba/p3c#512]
![image](https://user-images.githubusercontent.com/18100287/57924449-b3b81c00-78d7-11e9-83ac-245b304b8bb6.png)
Plugin Alibaba Java Coding Guidelines download or installing failed
Plugin Alibaba Java Coding Guidelines was not installed: Invalid filename returned by a server

**Comment by 610232785** [comment]
一样的问题

**Comment by chengchenrui** [comment]
我mac也是，以为是系统的问题，看来不是

**Comment by SeanCai** [comment]
最新版已经发布了，可以试试，以前的下载路径包含空格，估计跟这个有关系
@fufenghua @610232785 @chengchenrui
