### ISSUE TITLE
疑似笔误，惟一索引

### ISSUE THREAD

**Issue by xuguangwu** [alibaba/p3c#514]
路径为p3c-gitbook/MySQL数据库/索引规约.md
内容如下：
【参考】创建索引时避免有如下极端误解：
 ...
 3）抵制惟一索引。认为业务的惟一性一律需要在应用层通过“先查后插”方式解决。

这里是不是应该唯一索引以及唯一性

**Comment by yangguanbao** [comment]
感谢支持，确是需要修正，下一个版本泰山版会进行修正。
