### ISSUE TITLE
编辑 Velocity 模板时出错

### ISSUE THREAD

**Issue by ijliym** [alibaba/p3c#515]
有好几次编辑 Velocity 时出错，但不影响编辑
![image](https://user-images.githubusercontent.com/43025881/58772683-a6e03b80-85ec-11e9-8208-36bba152b7b9.png)

**Comment by SeanCai** [comment]
错误原因是因为idea inspection结果定位时，内容已经变更，导致结构不匹配。不影响使用的哈
