### ISSUE TITLE
Conflict between guidelines and codes

### ISSUE THREAD

**Issue by zhu-he** [alibaba/p3c#516]
`com.alibaba.p3c.idea.quickfix.*` does not satisfy the following rule while the word `quickfix` is not `only one English word`:

> 9. [Mandatory] A package should be named in lowercase characters. There should be only one English word after each dot. Package names are always in singular format while class names can be in plural format if necessary.

We are meeting a similar situation in our project, where the package name is not suitable to be replaced by `only one English word`. Do you have a suggestion?

**Comment by yangguanbao** [comment]
I think It's a big problem, It’s easy for coder to understand the meaning of quickfix.

**Comment by yangguanbao** [comment]
I think It's not a big problem
