### ISSUE TITLE
idea-关闭某条规则设置后不生效

### ISSUE THREAD

**Issue by 865290480** [alibaba/p3c#517]
![企业微信20190603152726](https://user-images.githubusercontent.com/5119598/58783740-377e4200-8614-11e9-8fec-3f4fdbcb70c0.png)
![企业微信20190603152831](https://user-images.githubusercontent.com/5119598/58783756-44029a80-8614-11e9-9a45-e3519527003c.png)
![企业微信20190603152920](https://user-images.githubusercontent.com/5119598/58783794-61376900-8614-11e9-939e-c36a29b63990.png)

**Comment by SeanCai** [comment]
关闭某条规则只针对实时检测，批量扫描没有影响

**Comment by 865290480** [comment]
当代码提交时检测功能，如果关闭某个规则；提交代码时仍然会因该规则不满足强行阻断的；
![image](https://user-images.githubusercontent.com/5119598/59823762-d4094980-9361-11e9-8091-f074e49d2895.png)
![image](https://user-images.githubusercontent.com/5119598/59823863-1b8fd580-9362-11e9-9c26-48b29819f8d2.png)
