### ISSUE TITLE
为什么需要在 Transactional 注解指定 rollbackFor 或者在方法中显式的 rollback？

### ISSUE THREAD

**Issue by howardwchen** [alibaba/p3c#518]
请问这条规则是有什么前提条件吗？
我们的开发语言都是 java，常用的框架的异常体系大都是 RuntimeException，我们自己也很少而且不建议自定义非运行时异常，这与 rollbackFor 的默认值等于 RuntimeException.class 是相匹配的。
如果方法中可能抛出非运行时异常，按照非运行时异常的本意，也需要程序员主动进行处理，而这个处理过程就可以把异常转为 RuntimeException，从而符合 rollbackFor 的默认值。
在极少情况下需要显式抛出非运行时异常时，制定 rollbackFor 才有意义。
**所以为什么需要指定 rollbackFor？**
我认为只有在方法中捕获了异常并自行处理没有抛出的同时又希望事务回滚，这时才需要显式地 rollback，但这一般是少数情况。
**所以为什么需要在方法中显式的 rollback？**

**Comment by xuantan** [comment]
@luyiisme 看下哈

**Comment by luyiisme** [comment]
```
5. 【强制】有try块放到了事务代码中，catch异常后，如果需要回滚事务，一定要注意手动回 滚事务。
```
这段规约只是强调”异常要注意回滚掉事务“。 没有针对 spring-tx 的注解编程方式做说明，而是在 jdbc 层面的说法，异常后需要回滚。当然有的场景是手动，有些场景借助框架aop来做 rollback （比如spring-tx）。
