### ISSUE TITLE
实时检测“手动创建线程池”部分范围过大

### ISSUE THREAD

**Issue by mmaxiaolei** [alibaba/p3c#52]
例如使用`Executors.newSingleThreadScheduledExecutor`这种没有必要手动创建吧

**Comment by yangguanbao** [comment]
根据自己的经验，可以fork出来进行相应的修改。感谢支持《阿里巴巴Java开发手册》

**Comment by yangguanbao** [comment]
在大并发场景下，由于队列的长度无限问题，存在着一定风险。
