### ISSUE TITLE
最新版为何VOS, DTOS变成不合规则了 ? 还有URL ,OAuth

### ISSUE THREAD

**Issue by leung44** [alibaba/p3c#520]
![Snipaste_2019-06-15_15-34-42](https://user-images.githubusercontent.com/30283855/59548534-55886280-8f83-11e9-9108-0f03c8270eba.png)
![Snipaste_2019-06-15_15-35-01](https://user-images.githubusercontent.com/30283855/59548535-5c16da00-8f83-11e9-8b7c-0912ae38f340.png)

**Comment by JavaAIer** [comment]
个人觉得要开放词库,业务要求必须大写的词就放到这个词库里面.

**Comment by KylinHub** [comment]
还有GPS

**Comment by BestRoach** [comment]
太困扰了,之前还好好的,现在代码一堆黄,太难受了.希望可以早点修正一下.

**Comment by FelixLiuSheng** [comment]
同上

**Comment by FelixLiuSheng** [comment]
xxDTOList、xxVOList等

**Comment by xiaoyaojc** [comment]
> xxDTOList、xxVOList等

这种倒是问题不大，变量名不带VO,DTO就是了，关键是GPS，URL那些的，简直了

**Comment by SeanCai** [comment]
VOS, DTOS 本来就不符合规则，可能是以前没有扫描到；后续版本会处理xxDTOList可以通过扫描，对于GPS、URL这种专有名词，使用小写也没有关系，如果有特殊需求可以自行构建一下哈

**Comment by lixiaoxiongs** [comment]
还有PLM、ERP、MES、SAP等等专业领域内专用缩写，这个报黄线很难受哇

**Comment by XenoAmess** [comment]
我过几天考完试 看看能不能打出来这个洞
那边本来是写死的个String
如果可以的话 我打算搞个设置页 可以设置允许的大写单词
emm不过得等我考试完。
近期不打算大修。

**Comment by XenoAmess** [comment]
暂时 姑且算是考完了。我来试试打这个洞。如果没别人想干的话。

**Comment by Yuyang105** [comment]
开放词库的需求，可以基于开源版本自行加白。
