### ISSUE TITLE
IDEA滚动条预览提示文字乱码

### ISSUE THREAD

**Issue by C500mg** [alibaba/p3c#521]
V2.0.0版本滚动条提示中文乱码
![Snipaste_2019-06-18_10-24-08](https://user-images.githubusercontent.com/38483610/59649403-3113cc80-91b5-11e9-887f-441f19cb1f0d.png)

**Comment by SeanCai** [comment]
你好 参考一下这里哈 https://github.com/alibaba/p3c/wiki/IDEA%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8%E6%96%87%E6%A1%A3#%E4%B8%AD%E6%96%87%E4%B9%B1%E7%A0%81%E8%A7%A3%E5%86%B3%E6%96%B9%E6%B3%95
