### ISSUE TITLE
getRealAddressByIP

### ISSUE THREAD

**Issue by JavaAIer** [alibaba/p3c#522]
方法名【getRealAddressByIP】不符合lowerCamelCase命名风格

建议可以在插件里面加一些约定俗成的缩略语的大写词.

**Comment by yangguanbao** [comment]
包括Gps / Url / Tcp/ Ip / 等所有名词，都是统一遵守驼峰模式，不例外。
要不然，会出现 TCPUDPList这样怪异的命名方式。

**Comment by JavaAIer** [comment]
> 包括Gps / Url / Tcp/ Ip / 等所有名词，都是统一遵守驼峰模式，不例外。
> 要不然，会出现 TCPUDPList这样怪异的命名方式。

Ok
