### ISSUE TITLE
比如说originalX，originalY这种有些名词本身只有一个字母的，在v2.0.0里面不算是遵循驼峰命名么？

### ISSUE THREAD

**Issue by JreeyButler** [alibaba/p3c#523]
比如说originalX （原始X坐标），originalY（原始Y坐标） ，mOriginalYBuffer（原始YUV的Y分量Buffer），mOriginalUBuffer（原始YUV的U分量Buffer） 等等这种一个名词本身只有一个字母的，在v2.0.0里面不算是遵循驼峰命名么？
![image](https://user-images.githubusercontent.com/19368793/59896931-0cba2900-941d-11e9-8c3b-c214baec35bd.png)
![image](https://user-images.githubusercontent.com/19368793/59896958-23608000-941d-11e9-9dba-e285834b3b28.png)

**Comment by JreeyButler** [comment]
我记得在v1.0.6版本中这种命名是符合驼峰命名的规范的

**Comment by JreeyButler** [comment]
v1.0.6是确实没有这个问题
![image](https://user-images.githubusercontent.com/19368793/59898382-0fb81800-9423-11e9-876f-98fcd0581218.png)

**Comment by ziiwee** [comment]
![image](https://user-images.githubusercontent.com/14011414/60147431-e969f200-97ff-11e9-94af-67a6fdd6163f.png)
类似的还有单字母类名，这种命名不符合UpperCamelCase吗

**Comment by jack80342** [comment]
![批注 2019-06-27 182123](https://user-images.githubusercontent.com/8936903/60258816-7bf5b880-9908-11e9-82ba-ba5ee6f42436.jpg)
![批注 2019-06-27 182248](https://user-images.githubusercontent.com/8936903/60258864-962f9680-9908-11e9-81ae-198658e1f5ed.jpg)
上面这些实际上符合规则的，却都显示需要修改。

**Comment by samotoo** [comment]
借楼问一下类似的问题，在实现一个第三方库提供的接口的时候，因为接口本身的方法名就没有遵循驼峰，所以实现类也无法遵循，但是这种情况检查还是报错了，这种应该不报错吧。

**Comment by zqq90** [comment]
@samotoo  如果是 Json 这种，我们可以通过注解来将不规范的接口字段映射到规范的字段命名上来
但是如果是不支持映射关系的序列化/反序列化确实就没办法了
也只能 配置插件来 exclude 这些默许的违规类/包

**Comment by yangguanbao** [comment]
所有的单字母结尾都是不合理的。
所有的专有名词不支持全大写，一律遵守驼峰模式。

**Comment by JreeyButler** [comment]
@yangguanbao 你说单字母结尾不行我认可，但是比如说我第一张图显示的mOriginal**Y**Buffer，mOriginal**U**Buffer，这种单字母在中间的就不行么？这种专有名词本身就只有一个单词，难道修改成mOriginal**y**Buffer、mOriginal**u**Buffer？

**Comment by JreeyButler** [comment]
而且在 https://github.com/alibaba/p3c/issues/532 也承认了近期会修改。
