### ISSUE TITLE
特殊命名识别错误

### ISSUE THREAD

**Issue by davinci2014** [alibaba/p3c#524]
如图所示，特定含义的词组未能被有效识别。
![image](https://user-images.githubusercontent.com/23135144/59915488-59b6f300-944f-11e9-9432-3db10c07ad0e.png)

插件以及IDE版本
![image](https://user-images.githubusercontent.com/23135144/59915673-c631f200-944f-11e9-8ed0-69c60713c427.png)
![image](https://user-images.githubusercontent.com/23135144/59915783-0b562400-9450-11e9-9b36-fffcd99df5e5.png)

另外希望能够提供一个配置文件，忽略特殊命名（有时公司会强制要求特殊名称）。

**Comment by Yuyang105** [comment]
你好，暂时不开放白名单，请关注未来版本变化。
