### ISSUE TITLE
当插件提示的错误和警告与自带的提示混合在一起后，我无法使用F2跳转到下一个。

### ISSUE THREAD

**Issue by xianzheTM** [alibaba/p3c#525]
RT：
当我关闭插件的实时扫描后，我可以使用F2跳转到每一个错误：
![right](https://user-images.githubusercontent.com/25103583/59977769-020fb780-9608-11e9-947f-ea58e26dd36c.gif)
当我打开实时扫描后，
![error](https://user-images.githubusercontent.com/25103583/59977810-63d02180-9608-11e9-82bc-31c63ddcbca1.gif)
可以看到，F2只跳转了插件标记的警告，略过了public部分的警告。

**Comment by xianzheTM** [comment]
我将插件标记的错误全部修改完成，只剩自带的提示后又可以用F2来跳转了。这么看来，是两种提示的标记有优先级，先跳转插件的。但是这样的体验显然不太合理。

**Comment by yangguanbao** [comment]
体验上的确有不是特别舒服的地方，但是错误总是都要修复的，而且这种避免编译型错误的情况也不太常见。
