### ISSUE TITLE
update_time 和 gmt_modified 表述不一致

### ISSUE THREAD

**Issue by yyl4ever** [alibaba/p3c#528]
华山版，创建表必备字段已经调整为 update_time，那么下面的描述也应以 update_time 为基准，而不应沿用过去的 gmt_modified 字段。
![image](https://user-images.githubusercontent.com/23069118/60099832-0e704d80-978b-11e9-82bd-2b7cb9ffa424.png)

**Comment by yangguanbao** [comment]
![image](https://user-images.githubusercontent.com/25759061/62819146-c2833780-bb83-11e9-836b-33bebc1aee59.png)
的确是这个问题，非常感谢你们的支持，下一个版本（泰山版）会进行修改，感谢支持。
