### ISSUE TITLE
新建一个类Error，任何继承该类，并在同一包的子类，都必须以Exception结尾

### ISSUE THREAD

**Issue by pengsoftdotcom** [alibaba/p3c#529]
如题，应该是跟java.lang.Error搞混了

**Comment by Yuyang105** [comment]
在下一版更新

**Comment by yangguanbao** [comment]
![image](https://user-images.githubusercontent.com/25759061/66820981-3e2ea580-ef74-11e9-83a8-6952717c4edf.png)

下一版泰山版会有更加精确的描述。
