### ISSUE TITLE
如何关闭扫描

### ISSUE THREAD

**Issue by z201** [alibaba/p3c#53]
感觉每次编译都会自动扫描。

**Comment by SeanCai** [comment]
@z201 Eclipse 还是IDEA

**Comment by z201** [comment]
IDEA

**Comment by SeanCai** [comment]
https://github.com/alibaba/p3c/blob/master/idea-plugin/README_cn.md#关闭实时检测

**Comment by mfkvfn** [comment]
1 Eclipse中怎么关闭？不想对某个不是我开发的工程进行检查和提示。
2 某些东西不我想处理（比如不允许魔法值）怎么认它不要警告？
