### ISSUE TITLE
p3c规则如何与代码质量工具SONAR集成？

### ISSUE THREAD

**Issue by hnmas** [alibaba/p3c#531]
目前网上找到的集成都是一年前个人更新的，咱们官方能出个与新版本SONAR (7.x版本)集成的功能不，这样才方便使用。

**Comment by caowenliang** [comment]
https://github.com/caowenliang/sonar-pmd-p3c  支持SonarQube7.x

**Comment by slowwalkerlcr** [comment]
https://www.jianshu.com/p/c0f42dba73b8 这里有对应的详细步骤

**Comment by huayaoyue6** [comment]
可以查看[huayaoyue6/sonar-pmd-p3c](https://github.com/huayaoyue6/sonar-pmd-p3c)
