### ISSUE TITLE
变量名【positionX】不符合lowerCamelCase命名风格

### ISSUE THREAD

**Issue by liangyongrui** [alibaba/p3c#532]
![image](https://user-images.githubusercontent.com/24314057/60267939-dfd6ac00-991d-11e9-9bdc-98b413da02bc.png)

idea 插件 版本 2.0.0

**Comment by zxyxz** [comment]
我也碰到了这个问题，我取了个codeA,然后一直提示我不符合，然后我把这个提示关闭了

**Comment by JreeyButler** [comment]
现在已经换回v1.0.6，v1.0.6没有这个问题

**Comment by imu2008** [comment]
@liangyongrui @zxyxz @JreeyButler 谢谢反馈，近期修改发布
