### ISSUE TITLE
VO DTO的定义

### ISSUE THREAD

**Issue by An0nymous0** [alibaba/p3c#536]
问题跟#7 类似。
在领域驱动（DDD）里面VO真正的定义是value object。看手册里更偏向view object。
public UserDTO getUser(UserVO userVO) 与 public UserVO getUser(UserDTO userDTO)
按照DDD里个人感觉后者更合理一些。

参考资料
https://stackoverflow.com/questions/31438286/ddd-which-layer-dto-should-be-implemented
https://enterprisecraftsmanship.com/2015/04/13/dto-vs-value-object-vs-poco/

**Comment by yangguanbao** [comment]
理解你的意思，手册的确是View Object，主要输送向展示端的数据封装。
