### ISSUE TITLE
2.0.0 lowerCamelCase 问题

### ISSUE THREAD

**Issue by ningsia** [alibaba/p3c#540]
升级到2.0.0 之前没问题，升级之后扫描结果。
对 变量名 fooBO 提示  fooBO 不符合 lowerCamelCase 规则
但是之前的版本不会报错，因为对 VO BO DTO 这几个作为后缀的变量名称，都正常。

2.0.0 版本对BO 报错，对VO、DTO等正常

**Comment by xiaoyaojc** [comment]
变量不允许带BO等后缀的吧，类名可以带，变量不能带

**Comment by Yuyang105** [comment]
你好，下个版本会加。

**Comment by xuantan** [comment]
2.0.1新版本已发布，此问题已解决。

**Comment by LeeYiua** [comment]
专有名词作为类名或者变量名的时候，代码检测会认为不符合命名规则。
`    // 比如说:
    public class JVMInfo {
        private long totalJVMMemorySize;
    }`

**Comment by XenoAmess** [comment]
@osys @jaychang9 

如果需要个性化配置 可以考虑迁移至TPM

https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

配置说明例:
https://github.com/XenoAmess/p3c/blob/xenoamess_maintain_fork/idea-plugin/README_cn.md
