### ISSUE TITLE
2.0.0 lowerCamelCase 问题

### ISSUE THREAD

**Issue by xiaoyaojc** [alibaba/p3c#542]
![image](https://user-images.githubusercontent.com/13848235/61098545-f6d6db80-a491-11e9-9313-c842541da2b2.png)
升级到2.0.0版本后，连MD5和iOS都无法写了。这个标准是不是太严格了

**Comment by jacobvv** [comment]
根据Google规范，iOS应该写为Ios，MD5应该写为Md5。

| Prose form | Correct | Incorrect |
| -- | -- | -- |
| "XML HTTP request" | XmlHttpRequest | XMLHTTPRequest |
| "new customer ID" | newCustomerId | newCustomerID |
| "inner stopwatch" | innerStopwatch | innerStopWatch |
| "supports IPv6 on iOS?" | supportsIpv6OnIos | supportsIPv6OnIOS |
| "YouTube importer" | YouTubeImporterYoutubeImporter* |  |

具体见https://google.github.io/styleguide/javaguide.html
