### ISSUE TITLE
《码出高效》第 121 页勘误

### ISSUE THREAD

**Issue by ClarkWong** [alibaba/p3c#547]
印次：2，页码：121，行数：last

(2) 修改类加载方式。类的加载模型并非强制，除 Bootstrap 外，其他的加载并非一定要引入，或者根据实际情况在某个时间点 **进行** 按需进行动态加载。

应为：

(2) 修改类加载方式。类的加载模型并非强制，除 Bootstrap 外，其他的加载并非一定要引入，或者根据实际情况在某个时间点按需进行动态加载。

**Comment by yangguanbao** [comment]
最新的印次中，此问题还依然存在的：
![image](https://user-images.githubusercontent.com/25759061/62819087-d24e4c00-bb82-11e9-90e5-cfcaff6cdac0.png)
非常感谢，下一版本中，会进行改进。
我们努力做得更好，感谢支持《码出高效》
