### ISSUE TITLE
《华山版》改良建议

### ISSUE THREAD

**Issue by ClarkWong** [alibaba/p3c#548]
文中共有 3 处示例存在【if 与括号之间未保留空格】的问题

不符合【if/for/while/switch/do 等保留字与括号之间都必须加空格】的规约

![image](https://user-images.githubusercontent.com/20752379/61352237-76ecaf00-a89f-11e9-87d9-8b7818ac7f94.png)

**Comment by eyestarrysky** [comment]
这个是反例啊，老哥

**Comment by ClarkWong** [comment]
> 这个是反例啊，老哥

反例都是有针对性的，“综合型反例”目前手册里应该没有，那样会误导读者。

所以，对于我图里的【避免在子父类的成员变量之间、或者不同代码块的局部变量之间采用完全相同的命名，使可读性降低】这一规约而言，其反例应只体现“变量命名不规范”这一点，而不应再引入其他的问题。

**Comment by yangguanbao** [comment]
已经确认，感谢你的建议，公司内部版本已经修改完成，下一个对外版本（泰山版）中会进行修正。
