### ISSUE TITLE
Eclipse上安装插件有点卡

### ISSUE THREAD

**Issue by davidyang013** [alibaba/p3c#55]
昨天晚上刚刚安装上插件，非常好用。只是Eclipse的反应速度一下子降了下来。查看了下eclipse.ini，使用的还是默认配置，内存大小是默认的，修改内存设置之后，保存重启，速度才恢复到原来的水平。是否有办法不影响使用速度？

**Comment by glenn2wang** [comment]
同感，刚刚扫描了下，直接卡的有点反应不过来了

**Comment by wonius** [comment]
你的eclipse哪个版本？我安装成功了，但是没有显示该插件

**Comment by davidyang013** [comment]
@wonius 我的应该是最新的版本， **Oxygen.1a.Release**，你可以试一下，感觉还可以的

**Comment by SeanCai** [comment]
@davidyang013 扫描理论完成后只是对代码进行了标记，理论上是不影响使用速度的，你那是不是出现了很多JPA的任务，如果是的话可以看这篇 https://github.com/alibaba/p3c/issues/28
