### ISSUE TITLE
为什么我安装完了，缺一个问题都查不出来

### ISSUE THREAD

**Issue by ccuzhangleiseven** [alibaba/p3c#550]
![image](https://user-images.githubusercontent.com/18190445/61457644-5f92ec00-a99b-11e9-99a1-6f1390cef1ee.png)
![image](https://user-images.githubusercontent.com/18190445/61457712-82250500-a99b-11e9-981c-a85382a26d8e.png)
![image](https://user-images.githubusercontent.com/18190445/61457736-8fda8a80-a99b-11e9-87f7-480c0b9d93e0.png)

**Comment by SeanCai** [comment]
右下脚有报错吗？
