### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by FRookie** [alibaba/p3c#553]
在常量定义的第四个规范推荐中：

类 A 中：public static final String YES = "yes";    
类 B 中：public static final String YES = "y";     
A.YES.equals(B.YES)，预期是 true，但实际返回为 false，导致线上问题。 

为什么期望的是TRUE呢，这明明定义的值就不一样啊，只是常量名一样而已啊！！！

**Comment by yangguanbao** [comment]
一个方法返回的是  第一个的YES
另一个方法返回的是第二个的YES
预期都是YES，但由于定义的来源不一样。
导致返回为false.
这段描述，我会好好考虑一下，如何优化。
感谢支持。
