### ISSUE TITLE
关于HeapDumpOnOutOfMemoryError注意事项

### ISSUE THREAD

**Issue by zhugw** [alibaba/p3c#555]
工作过程中遇到的一个关于HeapDumpOnOutOfMemoryError注意事项 觉得有必要在介绍`HeapDumpOnOutOfMemoryError`条目中提醒一下

在工作过程中发现 应用设置了`-XX:+HeapDumpOnOutOfMemoryError`参数后 一个进程只会dump一份文件 如果应用之后又继续抛出了`java.lang.OutOfMemoryError` 则不会再生产新的dunp文件了 

> Also please note that a heap dump is written only on the first OutOfMemoryError. If the application chooses to catch it and continues to run, the next OutOfMemoryError will never cause a heap dump to be written! 

https://wiki.scn.sap.com/wiki/pages/viewpage.action?pageId=33456

**Comment by xuantan** [comment]
你好，你的问题背景和建议能详细描述一下么?
