### ISSUE TITLE
PMD SPI requirement: Custom POJO_SUFFIX_SET & CLASS_NAMING_WHITE_LIST

### ISSUE THREAD

**Issue by zqq90** [alibaba/p3c#556]
需求：正像其他 Issue 描述的那样, 我们希望能够自定义 Pojo 后缀，以及自定义词库
see: #520 #540 

对我们可行的解决方案：**提供一个 SPI，该 SPI 可以收集自定义的 Pojo 后缀**

1. 我们注意到 Pojo 后缀目前存放在配置文件，因此是可配置的
https://github.com/alibaba/p3c/blob/master/p3c-pmd/src/main/resources/namelist.properties#L4
2. 我们正使用 `Gradle` 提供的 `pmd` 插件，因此我们能够将我们自定义的 jar 包和 `p3c-pmd`
 放置于同一 classpath， 因此 SPI 理论上是可行的

**Comment by lic2050** [comment]
同求

**Comment by zqq90** [comment]
@yangguanbao 请看看

**Comment by zqq90** [comment]
@xuantan 请看看

**Comment by SeanCai** [comment]
@zqq90 业务领域的暂不考虑，因为名词太多了，如果实在需要的话，可以修改构建上传到自己公司的repository中，然后使用哈

**Comment by zqq90** [comment]
@SeanCai 
你好，我所指的 是提供一个扩展能力，基于 `java.util.ServiceLoader`  提供扩展能力，这样我们不需要 fork 此项目来硬编码我们的字典。
我们希望这是个 开放的 可扩展的生态，而不是分而治之

希望可以重新考虑此需求

**Comment by XenoAmess** [comment]
> @SeanCai
> 你好，我所指的 是提供一个扩展能力，基于 `java.util.ServiceLoader` 提供扩展能力，这样我们不需要 fork 此项目来硬编码我们的字典。
> 我们希望这是个 开放的 可扩展的生态，而不是分而治之
> 
> 希望可以重新考虑此需求

嗯我知道你想要什么效果了。
问题是，你打算怎么让p3c-pmd知道你要加载的配置文件的路径（或者内容）？
就是说你得有个通信口子在这里，能把你在gradle的配置交给p3c对吧。
我不清楚Gradle的pmd插件有没有这么个通信口子。
然后你还得考虑这个方法必须在maven上也能用。

如果你对这个比较了解，可以教教我。

**Comment by zqq90** [comment]
@XenoAmess  

```groovy
apply plugin: 'pmd'

dependencies {
    pmd 'com.alibaba.p3c:p3c-pmd'
}
```
如上， `pmd` configuration 是会放到 PMD 的 classpath 下的，如此，可以（理论上）将自己自定义的 Service 实现塞到 `pmd`，可以是已经上传到私仓的扩展包，也可以在当前项目自定义的一个 `SourceSet`

**Comment by XenoAmess** [comment]
> @XenoAmess
> 
> ```groovy
> apply plugin: 'pmd'
> 
> dependencies {
>     pmd 'com.alibaba.p3c:p3c-pmd'
> }
> ```
> 
> 如上， `pmd` configuration 是会放到 PMD 的 classpath 下的，如此，可以（理论上）将自己自定义的 Service 实现塞到 `pmd`，可以是已经上传到私仓的扩展包，也可以在当前项目自定义的一个 `SourceSet`

你的意思是，我们去动pmd？
问题是pmd未必让我们动啊。

**Comment by zqq90** [comment]
@XenoAmess 
不需要动 PMD， 实际上只要能解决一个问题就行了，
就是 `ServiceLoader`能加载到自定义的字典实现就可以了，也就是只要能想办法把自己的实现放到和 `p3c-pmd` 同一个 classpath 就可以

下面是我自己调试自定义的 PMD规则， 折腾着玩儿的脚本：
```groovy
apply plugin: 'pmd'

dependencies {
  pmd 'com.alibaba.p3c:p3c-pmd'
  pmd 'org.jodd:jodd-json:5.0.13'
}

sourceSets.create('pmdExtra') {
  compileClasspath = configurations.pmd
  java.srcDir("${projectDir}/src/pmd-extra/java")
  resources.srcDir("${projectDir}/src/pmd-extra/resources")
}

pmdMain {
  pmdClasspath = configurations.pmd + sourceSets.pmdExtra.output
}
```

因此， 至少有三种比较简单方式让此方案生效
1. 自定义扩展包，并上传私仓， `p3c-pmd` 由你这个包作为依赖导入 （缺点：每次 `p3c-pmd` 升版本都得重新打自己的包， 不可取）(此方法理论 Maven 可用)
2. 自定义扩展包，并上传私仓， `p3c-pmd` 单独这里直接依赖
3. 新建个 `pmdExtra` 自己的 `SourceSet`, 将自己的 字典实现 放到  `${projectDir}/src/pmd-extra/resources`

以上方式， 都不需要魔改 `p3c-pmd`
**而且从目前观察，`p3c-pmd` 并不具有社区可维护性，每次似乎都是批量从阿里内网同步过来，如果强行魔改，很容易导致冲突**

**Comment by XenoAmess** [comment]
首先，你明确一个概念，【pmd】是一个语言规则框架，【p3c-pmd】是【利用pmd框架处理p3c语言规则】的一个【pmd插件】，是这么个逻辑。
pmd不是阿里的件。并且pmd很大，不好动，我没这个水平动pmd。
所以你要清楚，p3c-pmd是好动的，pmd是不好动的。


> 1. 自定义扩展包，并上传私仓， `p3c-pmd` 由你这个包作为依赖导入 （缺点：每次 `p3c-pmd` 升版本都得重新打自己的包， 不可取）(此方法理论 Maven 可用)

这个方法是前边阿里官方人推荐的办法。确实是可行的。不过要是用这个法子那也不需要这个issue了对不对。

> 2. 自定义扩展包，并上传私仓， `p3c-pmd` 单独这里直接依赖

事实上，p3c-pmd并没有作为你的项目的依赖，而是作为pmd-gradle-plugin的一个插件，就是插件的插件。所以它有没有一个依赖机制在这里，我很难说。我刚刚问你的就是有没有这个机制。
如果你写出来一个跑的通的传string的demo，我就可以给你做出来。

> 3. 新建个 `pmdExtra` 自己的 `SourceSet`, 将自己的 字典实现 放到  `${projectDir}/src/pmd-extra/resources`
这个我没听懂。因为我平常不怎么用gradle，我是maven人。抱歉。

> **而且从目前观察，`p3c-pmd` 并不具有社区可维护性，每次似乎都是批量从阿里内网同步过来，如果强行魔改，很容易导致冲突**

你这个观点的话一半对一半吧。
很容易导致冲突对的，他们的2.0.2就和我的冲了。
不具有社区可维护性不太对，因为事实上我成功维护了，虽然磕磕绊绊并且没多少人用。
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

我目前已经向pmd的人问2能不能做了。https://github.com/pmd/pmd/issues/2430
如果有兴趣可以一起来围观。

**Comment by XenoAmess** [comment]
还有 你把这个issue reopen一下吧。我记得提issue的人有权利reopen来着？
省的我过会儿忘了这事了。
谢谢。
我下楼陪老妈散步去了，
如果你跑通了demo，或者pmd的人给了相应的传参方案，那我回来就可以试试开始做。

**Comment by zqq90** [comment]
@XenoAmess

>  本质上你上面那个demo在我看来更像是做了个全新的pmd插件，而不是对p3c-pmd做了什么改动。

或许你没有理解我的意思，因为命名检查这件事情，我还是希望不动 `pmd` 也不动 `p3c-pmd`,  而且我 **不想定义新的规则**，因此，我是想 `p3c-pmd` 能有扩展能力，我做 `p3c-pmd` 的“插件”来满足这个需求

> 不具有社区可维护性

这一点可能是我们的标准是不一样的，我正是把你现在遇到的冲突问题判定为“不可维护”，也就是： 我们自然是可以 fork 的， 但是做了一些定制之后，因为冲突问题，就有一定的难度被阿里这边的官方所接受，这不是一个良性的生态

**Comment by XenoAmess** [comment]
> @XenoAmess
> 
> >  本质上你上面那个demo在我看来更像是做了个全新的pmd插件，而不是对p3c-pmd做了什么改动。
> 
> 或许你没有理解我的意思，因为命名检查这件事情，我还是希望不动 `pmd` 也不动 `p3c-pmd`,  而且我 **不想定义新的规则**，因此，我是想 `p3c-pmd` 能有扩展能力，我做 `p3c-pmd` 的“插件”来满足这个需求
> 
> > 不具有社区可维护性
> 
> 这一点可能是我们的标准是不一样的，我正是把你现在遇到的冲突问题判定为“不可维护”，也就是： 我们自然是可以 fork 的， 但是做了一些定制之后，因为冲突问题，就有一定的难度被阿里这边的官方所接受，这不是一个良性的生态
> 
> 

我明白你想做什么，我的意识是，pmd-gradle是gradle的插件，p3c-pmd是pmd的插件，现在你想做p3cpmd的插件，中间这个设置传递未必好做。当然，如果你能跑出来一个demo，都好说。

关于生态，我觉得一个更好的生态是我开一个fork版本，然后实现你要的功能，然后定期merge官方，你只管用就行。

**Comment by XenoAmess** [comment]
我刚刚学了一下pmd的文档。
如果要走pmd提供的那套口子，是可以的，但是必须让每个想改的用户重写那堆ruleset xml来配置属性
这个看起来似乎不那么能接受。
我现在正在考虑能不能 直接从指定路径读。
比方从和pom.xml的旁边新建一个指定名称的规则文件
不过我不太确定好不好摸。
我先试试吧。

**Comment by XenoAmess** [comment]
嗯我好像通过一个很奇妙的方法做到了。
不过 我打磨一下。
