### ISSUE TITLE
idea-plugin不能check和analyze test文件夹下面的测试类

### ISSUE THREAD

**Issue by kana112233** [alibaba/p3c#559]
写的测试类都没有代码检查

**Comment by yansheng836** [comment]
可以啊

**Comment by kana112233** [comment]
真的不支持Test,源码里面都写死了
第一处
```
analysisScope.isIncludeTestSource = false
```
第二处
```
private fun validScope(file: PsiFile): Boolean {
                val virtualFile = file.virtualFile
                val index = ProjectRootManager.getInstance(file.project).fileIndex
                return index.isInSource(virtualFile)
                        && !index.isInTestSourceContent(virtualFile)
                        && !index.isInLibraryClasses(virtualFile)
                        && !index.isInLibrarySource(virtualFile)
            }
```

**Comment by yansheng836** [comment]
我用的是第二版的插件，信息如下：
`Ali-CodeAnalysis	2.0.0.201906120653	com.alibaba.smartfox.eclipse.feature.feature.group	Alibaba`，
1. 我尝试了扫描整个（maven）项目，测试目录`src/test/java`下的测试文件可以扫描出存在的问题；
2. 而单独扫描该文件夹，同样也是可以扫描出来的。

如果没有更新插件，建议进行更新。

**Comment by kana112233** [comment]
我用的也是第二版，我猜你的是eclipse，我的是idea，我已经修改了源码，重新打包了 插件，可以工作了。谢谢回复。

yansheng836 <notifications@github.com> 于 2019年8月23日周五 下午5:14写道：

**Comment by yansheng836** [comment]
我的是eclipse，只是没想到功能会略有差别。那我倒是觉得这个问题可以向孤尽老师提出来，毕竟不是每个使用者都有能力去修改插件源码的。

**Comment by kana112233** [comment]
我有时间会提交pr
