### ISSUE TITLE
 Could not get unknown property 'ossrhUsername'

### ISSUE THREAD

**Issue by sunwuxiang** [alibaba/p3c#56]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/sunwuxiang/p3c-master/idea-plugin/p3c-common/build.gradle' line: 49

* What went wrong:
A problem occurred evaluating project ':p3c-common'.
> Could not get unknown property 'ossrhUsername' for object of type org.gradle.api.publication.maven.internal.deployer.DefaultGroovyMavenDeployer.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by SeanCai** [comment]
@sunwuxiang 已经解决，感谢反馈
