### ISSUE TITLE
【索引规约】第一条疑问

### ISSUE THREAD

**Issue by pugwoo** [alibaba/p3c#560]
> 1. 【强制】业务上具有唯一特性的字段，即使是多个字段的组合，也必须建成唯一索引。
说明：不要以为唯一索引影响了 insert 速度，这个速度损耗可以忽略，但提高查找速度是明显的；另外，
即使在应用层做了非常完善的校验控制，只要没有唯一索引，根据墨菲定律，必然有脏数据产生。

当有逻辑删除存在时，唯一所以难以适用。例如，表结构：
```sql
CREATE TABLE `test1`(  
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_deleted` TINYINT UNSIGNED,
  `phone` CHAR(20),
  PRIMARY KEY (`id`)
);
```

手机号是在业务上需要是唯一的。如果给phone加上唯一索引，将导致已存在的phone软删除之后，无法再写入相同phone的值。

有没有什么好的规约来解决这个问题？

**Comment by HarveyTvT** [comment]
可以考虑在软删除的手机号前加一个固定的字符

**Comment by HarveyTvT** [comment]
1. 修改is_deleted的含义, 0为未删除, 其它值为已删除
2. 建一个(phone, is_deleted)的联合索引
3. 软删除数据时, 将is_deleted值改为id的值, 保证is_deleted自增

**Comment by HarveyTvT** [comment]
mysql 5.7以上, 可以用虚拟列建一个表达式索引, 虚拟列的值为 concat(phone, is_deleted * id)

**Comment by yangguanbao** [comment]
在下一个版本泰山版中，我们会采用如下说法：
![image](https://user-images.githubusercontent.com/25759061/66818286-adee6180-ef6f-11e9-97a2-0a29360d79df.png)

**Comment by yangguanbao** [comment]
![image](https://user-images.githubusercontent.com/25759061/66818322-bc3c7d80-ef6f-11e9-84e6-12d9b6ed19e0.png)
