### ISSUE TITLE
equals调用问题，当同一个编译单元中出现以下情况时，直接返回

### ISSUE THREAD

**Issue by xiecailian1115** [alibaba/p3c#565]
public class Test{
    public void test（）{
        String str = “”；
        if("a".equals(str)){      ### 这种情况整个编译单元直接不扫描
        }
        if（str.equals("a")）{}  ### 该调用违反编码规则，不会报错
    }
}

**Comment by xuantan** [comment]
麻烦补充下IDE的版本等信息
