### ISSUE TITLE
【规约建议】百分比数据存储时保存百分比而非小数

### ISSUE THREAD

**Issue by tiggerlee2** [alibaba/p3c#566]
例如
```
58% 保存时保存 58 而非 0.58
```

原因

1. 读，写时，不需要对对象中的该字段做特别处理。展示和录入的场景基本使用百分比，很少用小数;

2. 计算时，要使用该字段计算，本身要从对象中获取，计算时除100很方便

**Comment by yangguanbao** [comment]
可以考虑在下一版泰山版中，做为推荐条目展示出来。
