### ISSUE TITLE
为什么起名字叫p3c

### ISSUE THREAD

**Issue by peigen** [alibaba/p3c#571]

**Comment by yansheng836** [comment]
网上找的，可参考：
>该插件由阿里巴巴P3C项目组研发。这个项目组是阿里巴巴开发爱好者自发组织形成的虚拟项目组，把《阿里巴巴Java开发规约》里的各种规约条目转化成自动化插件。

**Comment by yangguanbao** [comment]
P3C是反潜机代号，扫描水下隐患。感谢你支持阿里巴巴JAVA开发手册
