### ISSUE TITLE
使用MybatisGenerator 生成DOMapper 提示的UpperCamelCase

### ISSUE THREAD

**Issue by MRchao90s** [alibaba/p3c#572]
![image](https://user-images.githubusercontent.com/25077986/63518075-d420f380-c522-11e9-8778-138afe8814bf.png)

**Comment by tjgykhulj** [comment]
+1
mybatisBenerator的自动生成影响面还是很广的，建议考虑一下这种情况

**Comment by xuantan** [comment]
你好，这种情况经过项目组讨论后暂不考虑。

**Comment by tjgykhulj** [comment]
> 你好，这种情况经过项目组讨论后暂不考虑。

DAOImpl\YunOS这两个后缀都支持了，我没看出DOMapper不支持的理由啊。。
