### ISSUE TITLE
规范第五条集合处理中第11条

### ISSUE THREAD

**Issue by lazyymans** [alibaba/p3c#575]
写的是不要在foreach 循环中进行 remove/add 操作，在下认为应该写成   不要在foreach 循环中进行当前List的 remove/add 操作。有时我们可能在这个foreach 循环中进行一些其他List 的remove/add。存在一些语义的问题，虽然我们默认知道是当前List。

**Comment by yangguanbao** [comment]
正解，我们将在下一个泰山版中，进行修正。
