### ISSUE TITLE
同一maven项目明显违反规约的问题idea扫描被跳过，eclipse中正常

### ISSUE THREAD

**Issue by hrpinfzu** [alibaba/p3c#581]
尝试写入命名未驼峰、map未设置Capacity情况
![image](https://user-images.githubusercontent.com/29056300/64486549-10fa2380-d261-11e9-898f-67cb9cf5cb27.png)
右键“编码规则扫描”
检测不出任何结果

**Comment by Yuyang105** [comment]
@LQZYC 看一下

**Comment by LQZYC** [comment]
![89A3CCC7-20F3-47E8-9F51-C3B7C2B93286](https://user-images.githubusercontent.com/8571129/68280705-0917fd80-00b1-11ea-9063-6754d083bc5c.png)

**Comment by LQZYC** [comment]
![689683CC-5510-463B-911F-6E77F72DD577](https://user-images.githubusercontent.com/8571129/68280811-454b5e00-00b1-11ea-920a-d2be14a20636.png)


我这边测试是没有问题的。麻烦提供下详细的信息及使用版本
