### ISSUE TITLE
【规约】关于常量定义的讨论

### ISSUE THREAD

**Issue by shenjianeng** [alibaba/p3c#582]
> 【强制】不允许任何魔法值(即未经预先定义的常量)直接出现在代码中。

我觉的需要定义常量的地方有：
1、type，例如type，1表示 合格，2表示 优秀；应该定义常量，赋予明确的含义，方便阅读。
2、在多处使用的变量，例如 缓存key前缀，防止写错，便于一处修改。

同时，我觉得有些常量也是没有意义的，反而增加阅读成本。例如
将年单元转换为月单位
int year = 20;
int month = year * 12;
有些同学把12也定义的称量，例如
int month = year * MONTH_OF_YEAR;

**Comment by qianhangkang** [comment]
我觉得为了消除代码里的魔法值可以定义 :)

**Comment by qianhangkang** [comment]
1

**Comment by yangguanbao** [comment]
我觉得第二种即使定义了，也没有什么问题。大部分情况是懒。
另外缓存前缀是强烈建议定义出来的。
![image](https://user-images.githubusercontent.com/25759061/66816237-58648580-ef6c-11e9-9148-2bc16ebb4d47.png)
