### ISSUE TITLE
集合初始化时,指定集合初始值大小,为什么没有检测出new ArrayList<>()?

### ISSUE THREAD

**Issue by sabersword** [alibaba/p3c#583]
个人理解new ArrayList<>()也应该指定初始值大小, 但是插件没有检测出来,是因为这种情况不属于指定初始值大小吗?
使用的是插件版本是Alibaba Java Coding Guidelines-2.0.0

**Comment by yangguanbao** [comment]
目前只支持检测HashMap和ConcurrentHashMap，未来会越来越严格。
![image](https://user-images.githubusercontent.com/25759061/66817727-bf833980-ef6e-11e9-84b1-0dd50c040d7e.png)
