### ISSUE TITLE
ThreadLocal示例是否矛盾

### ISSUE THREAD

**Issue by yyl4ever** [alibaba/p3c#585]
![image](https://user-images.githubusercontent.com/23069118/65370229-08561400-dc89-11e9-8749-9ef24ba09551.png)
华山版，文中提到「必须回收自定义的 ThreadLocal 变量」，但是第 5点 例子(见截图)中的「static final .. df」又说明 ThreadLocal 变量不会被回收，那么到底这个第 5 点示例中的 ThreadLocal 变量是否需要回收呢？我理解每个线程的 ThreadMap 中都会有一个 SimpleDateFormat 实例，不清理的话会造成内存泄露吧？第 5 点和第 6 点的示例能否结合起来呢，把我看糊涂了。

**Comment by luyiisme** [comment]
嗯，这段话准确点表述是：”必须移除自定义的 ThreadLocal 变量记录的当前线程的值“。

**Comment by yangguanbao** [comment]
描述的确存在问题，下一个版本泰山版会进行修正。

必须移除自定义的 ThreadLocal 变量记录的当前线程的值。
而不是回收threadlocal的变量引用本身。

**Comment by tyrantqiao** [comment]
你好，目前泰山和嵩山版本貌似都对这个没有变更？
最终版本是要对变量进行remove 回收吗

**Comment by gujin520** [comment]
黄山版中进行了修正
