### ISSUE TITLE
在idea中编写if判断的代码时间，规约是强制性的要求，插件但是并没有自动提示

### ISSUE THREAD

**Issue by itxingqing** [alibaba/p3c#587]
if(1==1) {}
上述代码并没有自动的提示，不符合规范要求。
《java开发规范》中的原文是“【强制】if/for/while/switch/do 等保留字与括号之间都必须加空格。”
是我插件用的不对？

**Comment by Yuyang105** [comment]
这不是插件检测的范畴。
