### ISSUE TITLE
关于使用Mybatis时DAO层的定义

### ISSUE THREAD

**Issue by guyukou** [alibaba/p3c#590]
当项目中使用mybatis时，会有很多XXXMapper.java的类，这些类是直接对应规范里面的DAO对象吗？还是说DAO对象是对这个Mapper类的封装呢？

**Comment by yangguanbao** [comment]
参考 ：
![image](https://user-images.githubusercontent.com/25759061/66822013-f7da4600-ef75-11e9-9d90-2d94539caf5d.png)

![image](https://user-images.githubusercontent.com/25759061/66822056-0cb6d980-ef76-11e9-93c6-bd79483d6e36.png)
