### ISSUE TITLE
未检测“代码中的命名严禁使用拼音与英文混合的方式”

### ISSUE THREAD

**Issue by SoraYjy** [alibaba/p3c#593]
## 规约原文
2 [Mandatory] Using Chinese, Pinyin, or Pinyin-English mixed spelling in naming is strictly prohibited. 
## 问题描述
这条是如何检测的， 在源码中没有看到对应的检测方法，idae plugin 也无法检测出该问题。
## 修改建议
无

**Comment by yangguanbao** [comment]
这一块检测的难度极大，只是一个要求，暂时没有扫描规则上的实现。
感谢关注P3C
