### ISSUE TITLE
什么时候搞一个Kotlin Coding Guidelines

### ISSUE THREAD

**Issue by spencercjh** [alibaba/p3c#594]
**Describe the solution you'd like**
参考这样的[编码规范](https://www.kotlincn.net/docs/reference/coding-conventions.html)以及现有的Java代码的规范，对Kotlin代码进行规范检查。

**Describe alternatives you've considered**
我自己先研究研究……

**Additional context**
不知道阿里巴巴有没有拥抱这门优秀的JVM语言。

**Comment by tangxiangpi** [comment]
支持

**Comment by yangguanbao** [comment]
Kotlin目前阿里巴巴没有统一的硬性规范，你可以提供一份你阅读过，或者你写过的kotlin代码规范。据我了解，目前有个别的第三方工具平台有kotlin的扫描能力。

**Comment by weifeng99** [comment]
目前kotlin在阿里还没有统一规范, 如果有好的想法和实践, 可以介绍给我们, 欢迎共建.
