### ISSUE TITLE
Check Type-Alias  by Annoutations?

### ISSUE THREAD

**Issue by zhengxiaoyao0716** [alibaba/p3c#597]
**Is your feature request related to a problem? Please describe.**
As we known, Java not support Type-Alias. But this is a really useful feature to help us write the safety&correctly code.

**Describe the solution you'd like**
As the title indicated, maybe we can just add the Type-Alias lint by Annoutations. It could be removed in the runtime, only used for the linter to check is type matched, like @NonNull, @Nullable, etc.
For example:
``` java
        Map<@Alias("UserId") Long, User> users;
        Map<@Alias("ItemId") Long, Item> items;
        Map<@Alias("UserId") Long, @Alias("ItemId") Long> userItemMap;

        public User getUser(@Alias("UserId") long userId);

        public @Alias("Centigrade") double faToCe(@Alias("Fahrenheit") double value);

```

**Describe alternatives you've considered**
Even we could just implement it with comments like those:
``` java
        Map</*@Alias UserId*/Long, /*@Alias ItemId*/Long> userItemMap;
```

**Additional context**

**Comment by SeanCai** [comment]
建议在定义上面加  // UserId -> ItemId 或者字段上面 加 /** UserId -> ItemId */，更简洁方便

**Comment by zhengxiaoyao0716** [comment]
@SeanCai 我要的是IDE提示和编译时检查，不是人眼编译和检查
