### ISSUE TITLE
《阿里巴巴Java开发手册（华山版）》中的错别字

### ISSUE THREAD

**Issue by LUOrenjia** [alibaba/p3c#598]
## 规约原文
编程规约 -> 第四部分OOP 规约 -> 第8点 -> 反例 -> 注释内容“预期进入此代码快，执行其它业务逻辑”
## 问题描述
“代码快” 错别字“快”
## 修改建议
代码块

**Comment by yangguanbao** [comment]
![image](https://user-images.githubusercontent.com/25759061/67832977-4cf18c80-fb1e-11e9-9e52-3e4aec83b977.png)

将在下一个版本泰山版中修复

**Comment by yangguanbao** [comment]
感谢你的反馈，请继续关注Java开发手册

**Comment by yangguanbao** [comment]
以后保持大概半年更新一次的节奏

**Comment by yangguanbao** [comment]
https://mp.weixin.qq.com/s/-nOnyZgh2x-L9yv2VfJuuA?spm=a1z2e.8325955.0.0.50ce4f9bun06oL
嵩山版
