### ISSUE TITLE
(一) 命名风格 #13

### ISSUE THREAD

**Issue by qichuan** [alibaba/p3c#6]
`尽量不要在接口里定义变量，如果一定要定义变量，肯定是与接口方法相关，并且是整个应用的基础常量。 `这句话有歧义，既然已经说是变量(variable)了，怎么能是基础常量(constant)呢？

**Comment by 155191906** [comment]
初学者来报道

**Comment by yangguanbao** [comment]
在指令式语言中，变量通常是可变的，变量也可能是不可变（immutable）的。
