### ISSUE TITLE
建议对于英文系统环境默认采用英语

### ISSUE THREAD

**Issue by soudazhou** [alibaba/p3c#60]
人在国外，尝试在公司里推广插件

现在默认是中文，需要手动切换到英文，但是有乱码，希望能够实现对于英文环境默认英文，减少国外用户的困惑

![image](https://user-images.githubusercontent.com/3345052/31603289-93cd7086-b257-11e7-950e-9885e262d5ce.png)

**Comment by xuantan** [comment]
@SeanCai 跟进下
