### ISSUE TITLE
自己扩展p3c后，打包引入idea提示failed to load plugin descriptor from file 

### ISSUE THREAD

**Issue by zhaolibin** [alibaba/p3c#600]
能帮忙解答下这个问题么？
我是在idea-plugin路径下运行gradle clean buildPlugin打包的Alibaba Java Coding Guidelines-2.0.0.zip
在通过idea引入本地插件导入时报这个错

**Comment by SeanCai** [comment]
需要在 p3c-idea下运行，如果要在idea-plugin运行的话 需要根据gradle规范加前缀
