### ISSUE TITLE
方法注释时 要@param 与googlestyle有冲突

### ISSUE THREAD

**Issue by xiaoxiao-up** [alibaba/p3c#601]
## 规约原文
所有的抽象方法（包括接口中的方法）必须要用javadoc注释、除了返回值、参数、异常说明外，还必须指出该方法做什么事情，实现什么功能。 说明：如有实现和调用注意事项，请一并说明。
    /**
     * fetch data by rule id
     * 
     * @param ruleId rule id
     * @param page page number
     * @param jsonContext json format context
     * @return Result<XxxxDO>
     */
    Result<XxxxDO> fetchDataByRuleId(Long ruleId, Integer page, String jsonContext);

## 问题描述
与googlestyle 有冲突。googlestyle 只认大写开头的 @Param
如果只是@param 格式化得时候 googlestyle 会自动去掉@param 
## 修改建议
@param 不区分大小写

**Comment by Yuyang105** [comment]
Google style's Block tags 也是小写的
