### ISSUE TITLE
规约里漏了个字

### ISSUE THREAD

**Issue by gaohanghang** [alibaba/p3c#603]
## 规约原文

![image](https://user-images.githubusercontent.com/20310190/68208902-34491100-000d-11ea-8025-63716f1529d7.png)

五、MySQL 数据库

(一) 建表规约

第 13 条

商品类目名称使用频率高，字段长度短，名称基本一不变，可在相关联的表中冗余存储类目名 称，避免关联查询。

## 问题描述

”名称基本一不变“ 少了个成字

## 修改建议

应该是 “名称基本一成不变”

**Comment by yangguanbao** [comment]
感谢关注，我们在下一个版本泰山版中修改。

**Comment by gaohanghang** [comment]
> 感谢关注，我们在下一个版本泰山版中修改。

好的，大师球捕捉孤尽大佬 😆
