### ISSUE TITLE
lowerCamelCase检查误报

### ISSUE THREAD

**Issue by Simon-Dox** [alibaba/p3c#604]
![image](https://user-images.githubusercontent.com/18028613/68359646-93b33800-0157-11ea-879d-f57d28f43401.png)
这样的变量命名是符合lowerCamelCase规范的。

**Comment by qxo** [comment]
相同的这个规则也不适用为实现三方库中接口和继承类而必须方法
如实现io.vertx.core.eventbus.MessageCodec类而必须的systemCodecID方法
ref: https://vertx.io/docs/apidocs/io/vertx/core/eventbus/MessageCodec.html

这也是一种误报

**Comment by yangguanbao** [comment]
X, Y, Z轴的三种表示方式，我们加入白名单，预计下下周发布，感谢关注。
