### ISSUE TITLE
一直提示 @Author 信息

### ISSUE THREAD

**Issue by woniuxia** [alibaba/p3c#606]
## 规约原文

![image](https://user-images.githubusercontent.com/16383685/68732617-09fbe280-060f-11ea-98be-949345ada1ff.png)

## 问题描述
你好,我们内部代码,一般是不允许出现 @Author 信息的,但是 咱们的插件一直提示.
有办法能屏蔽掉这个提示吗.(有点小强迫症....)
感谢

**Comment by SeanCai** [comment]
你好，可以在这里关掉实时扫描，手动通过菜单触发扫描无法关闭
![image](https://user-images.githubusercontent.com/5645909/69132991-150fb080-0af0-11ea-8031-b16db91ca991.png)

**Comment by woniuxia** [comment]
已解决,感谢~
