### ISSUE TITLE
魔法值

### ISSUE THREAD

**Issue by emperor-liu** [alibaba/p3c#61]
for (int i = 0; i < 4; i++) {}
if(i>=10)
以上两种情况均可出现，纯数字的应该没必要这么校验吧，不太理解。
int length=4
for (int i = 0; i < length; i++) {}
不太懂这种区别在哪里，求大神解释！

**Comment by yangguanbao** [comment]
有可能你的length是有含义的。
比如:
limitStockCount = 4;
for(int i=0; i<limitStockCount; i++)
这样的可读性就会强很多。
与控制语句的第4条类似。
