### ISSUE TITLE
小需求，idea插件提示代码不规范的波浪线标识，能否自定义颜色？

### ISSUE THREAD

**Issue by evasnowind** [alibaba/p3c#610]
**问题描述：使用idea默认主题时，不符合规范的代码，波浪线警告不明显** 
部分团队成员反馈，idea默认主题下，目前的波浪线很不明显，导致有时会漏掉这种代码。是否能自定义调整波浪线颜色？

**个人小建议：支持自定义波浪线颜色，或是官方文档中给出如何修改颜色值教程**
- 支持自定义波浪线颜色
- 官方文档中给出修改颜色值教程，我们自己重新编译打包

附带
![image](https://user-images.githubusercontent.com/2696709/69022478-5b80e480-09f6-11ea-9788-32e6d2e7929d.png)

谢谢。

**Comment by SeanCai** [comment]
这里修改试试
![image](https://user-images.githubusercontent.com/5645909/69132559-3f14a300-0aef-11ea-95c6-7da0b6b40fc7.png)
