### ISSUE TITLE
表记录修改时间约束不一致

### ISSUE THREAD

**Issue by JackWei1996** [alibaba/p3c#611]
## 规约原文
【强制】 表必备三字段： id, create_time, update_time。
【强制】 更新数据表记录时，必须同时更新记录对应的 gmt_modified 字段值为当前时间。
## 问题描述
表的必备三字段修改时间为update_time，修改记录的时候确是gmt_modified 
## 修改建议
建议统一使用update_time
【强制】 更新数据表记录时，必须同时更新记录对应的 update_time 字段值为当前时间。

**Comment by yyl4ever** [comment]
This issue is the same as #528, and has been already replayed by the author.

**Comment by yangguanbao** [comment]
在2020年2月20日，泰山版中进行修复。

**Comment by yangguanbao** [comment]
https://mp.weixin.qq.com/s/-nOnyZgh2x-L9yv2VfJuuA?spm=a1z2e.8325955.0.0.50ce4f9bun06oL

在这个版本中彻底修复

**Comment by yangguanbao** [comment]
嵩山版
