### ISSUE TITLE
jenkins希望能引入规约扫描的插件

### ISSUE THREAD

**Issue by xiyan1120** [alibaba/p3c#616]
jenkins很多时候用于环境的部署，idea/eclipse中虽然集成了，但是，代码提交时，依然可跳过规约扫描，这就使得错误的代码很可能继续在生产环境中被使用。

**Comment by tangxiangpi** [comment]
支持命令行就可以了

**Comment by xiyan1120** [comment]
> 支持命令行就可以了

有使用方法不？我目前还在研究中（还没看到支持命令行的处理），如果您这边有相应的博客或文档的话，可否回复我下呢？我再去看下您发的相应的文档。

**Comment by tangxiangpi** [comment]
没有，我意思是它支持就满足你的需求拉。

**Comment by xiyan1120** [comment]
> 没有，我意思是它支持就满足你的需求拉。

好吧，我以为目前已经有支持了呢，如果支持命令行那也OK。

**Comment by xuantan** [comment]
https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F

**Comment by xiyan1120** [comment]
> https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F

谢谢，这个应该可以使用起来。
