### ISSUE TITLE
提交前针对提交的文件做检查

### ISSUE THREAD

**Issue by tangxiangpi** [alibaba/p3c#617]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**
现在提交前的检查实际是整个项目，因为项目中大量的代码不合符规范不可能短时间内修改完，提交前是否可以只针对提交的代码进行检查？
并且是否支持gradle脚本，那样可以轻易地集成至jenkins

**Additional context**

**Comment by xuantan** [comment]
https://github.com/alibaba/p3c/wiki/FAQ#4-%E5%A6%82%E4%BD%95%E7%9B%B4%E6%8E%A5%E4%BD%BF%E7%94%A8p3c-pmd%E6%88%96%E9%9B%86%E6%88%90%E5%9C%A8sonar%E6%88%96gradle%E6%88%96jekins%E5%8F%8A%E5%9C%A8%E7%BA%BF%E6%89%AB%E6%8F%8F
