### ISSUE TITLE
idea2019.3 安装失败

### ISSUE THREAD

**Issue by wuyingdu** [alibaba/p3c#618]
**Describe the bug**
idea 2019.3 安装p3c 2.0.0失败

 
![微信图片_20191209121734](https://user-images.githubusercontent.com/45226442/70407142-0fb5de00-1a7e-11ea-92d2-5d56378613dc.png)
![微信图片_20191209121742](https://user-images.githubusercontent.com/45226442/70407144-10e70b00-1a7e-11ea-9c4d-ec8aace53315.png)

**Comment by xuantan** [comment]
你好，直接安装2.0.1版本即可。
