### ISSUE TITLE
p3c-pmd 有没有Gradle插件？

### ISSUE THREAD

**Issue by qiujiayu** [alibaba/p3c#62]
p3c-pmd 有没有Gradle插件？

**Comment by tengzhaoyong** [comment]
p3c-pmd怎么玩？

**Comment by vnicers** [comment]
同求Gradle plugin

**Comment by pkaq** [comment]
直接应用ｐｍｄ插件稍作配置即可
参考下面　
[http://www.jianshu.com/p/274643cc9c28](http://www.jianshu.com/p/274643cc9c28)

**Comment by qiujiayu** [comment]
研究PMD插件后，小成果：
https://my.oschina.net/u/1469495/blog/1553231

**Comment by clasnake** [comment]
请问gradle插件的输出report如何切换到英文？
