### ISSUE TITLE
Check style 引入 p3c-formatter 中 eclipse-codestyle.xml 报错

### ISSUE THREAD

**Issue by JeremyWang2009** [alibaba/p3c#621]
![image](https://user-images.githubusercontent.com/12162133/70681208-944e6980-1cd5-11ea-8f16-db8f396ac608.png)
点击`+`添加 code style 文件:
![image](https://user-images.githubusercontent.com/12162133/70681235-a7f9d000-1cd5-11ea-9036-9e61782552fd.png)

**Comment by xuantan** [comment]
可以在IDE上安装下eclipse-codeformatter插件试试，这里不建议在IDEA上使用此功能。
