### ISSUE TITLE
Eclipse插件太弱，希望能与IDEA一样强大

### ISSUE THREAD

**Issue by mfkvfn** [alibaba/p3c#622]
Eclipse下功能太弱了，我看Wiki中我希望的很多功能在IDEA版中都有。希望Eclipse插件也提供这些功能。

比如

1 在某个工程上关闭检测功能（有些历史遗留项目只要不出Bug是不会动的，代码只是调试用的。有些项目不是我开发的，我只有读权限没写权限，给我提示了也没啥用）
2 可以修改某些规则的设置，比如打开或关闭某个规则（比如行尾注释、魔法值或注释掉的代码段），或者调整其提示的级别（Critical、Major等）。
3 可以设置某些规则的参数，比如单个方法总行数超过80行，这里80可以设置。

**Comment by xuantan** [comment]
Eclipse后续没有更多资源去投入，欢迎参与共建。
