### ISSUE TITLE
建议不使用double类型作为BigDecimal的构造入参

### ISSUE THREAD

**Issue by hailiangyuan** [alibaba/p3c#624]
## 问题描述
使用double作为BigDecimal的构造入参时，无任何提示；
使用compareTo 方法时会出现精度问题
![Uploading image.png…]()

## 修改建议
当开发者使用double类型作为BigDecimal的构造参数时，提醒开发者使用 string 类型
 例：new BigDecimal(31.411111) 改为  new BigDecimal(“31.411111”)

**Comment by yangguanbao** [comment]
![image](https://user-images.githubusercontent.com/25759061/72422576-b1d38f00-37bd-11ea-9498-0736d6bde6c5.png)
