### ISSUE TITLE
IDEA正则忽略文件或文件夹扫描，类似checkstyle功能

### ISSUE THREAD

**Issue by euler-king** [alibaba/p3c#625]
**IDEA正则忽略文件或文件夹扫描，类似checkstyle功能**
参考checkstyle的maven插件，可以配置exclude，忽略相应的文件或者文件夹扫描。
原因：部分文件因为是对jar文件中类的部分代码重写，所以需要保留原有的代码格式。

**Comment by yangguanbao** [comment]
我觉得所有的文件都应该规范起来了，规范是一个长期的过程，在于点点滴滴。
