### ISSUE TITLE
【VSCode 第三方插件】Java P3C Checker --By rectcircle 

### ISSUE THREAD

**Issue by Moonzzz** [alibaba/p3c#628]
VSCode 第三方插件 [https://marketplace.visualstudio.com/items?itemName=Rectcircle.vscode-p3c](url)
由@rectcircle 提供，详请看下方

**Comment by fw8899** [comment]
非常欢迎共建 :D

**Comment by rectcircle** [comment]
> 非常欢迎共建 :D

最近一个项目想做严格代码讲检查和CI/CD，想把p3c落地。

希望 命令行 和 ide 使用同一份配置，但是发现IDEA的 p3c 好像不太支持。

我是vscode深度用户，想看下VSCode是否能较好的支持。

然后发现 VSCode 的 这个扩展 可以实现 https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-pmd

配置方式：就是将 p3c-pmd 打成一个fat jar 加入 以上扩展的 classpath，然后再指明 xml 配置文件路径，基本使用没有问题。

但是存在两个问题：

* 中文乱码 （这个问题通过阅读源码已经找到解决方法了，且已经提给作者了，我没有windows pc确保没问题所以没有提pull request），可以看这个 issue https://github.com/ChuckJonas/vscode-apex-pmd/issues/74
* 保存文件/打开文件似乎无法触发（问题在于他们限制了PMD的使用 `['apex', 'visualforce']`，我也提了 issue https://github.com/ChuckJonas/vscode-apex-pmd/issues/75 但是看到历史的issue，他们似乎不愿意放开 ）

刚好我开发过VSCode的扩展，因此想基于 这个扩展开发一个 针对p3c的VSCode 扩展，https://github.com/rectcircle/vscode-p3c 今天刚启动，打算周末时间开发下。

**Comment by rectcircle** [comment]
> > 非常欢迎共建 :D
> 
> 最近一个项目想做严格代码讲检查和CI/CD，想把p3c落地。
> 
> 希望 命令行 和 ide 使用同一份配置，但是发现IDEA的 p3c 好像不太支持。
> 
> 我是vscode深度用户，想看下VSCode是否能较好的支持。
> 
> 然后发现 VSCode 的 这个扩展 可以实现 https://marketplace.visualstudio.com/items?itemName=chuckjonas.apex-pmd
> 
> 配置方式：就是将 p3c-pmd 打成一个fat jar 加入 以上扩展的 classpath，然后再指明 xml 配置文件路径，基本使用没有问题。
> 
> 但是存在两个问题：
> 
> * 中文乱码 （这个问题通过阅读源码已经找到解决方法了，且已经提给作者了，我没有windows pc确保没问题所以没有提pull request），可以看这个 issue [ChuckJonas/vscode-apex-pmd#74](https://github.com/ChuckJonas/vscode-apex-pmd/issues/74)
> * 保存文件/打开文件似乎无法触发（问题在于他们限制了PMD的使用 `['apex', 'visualforce']`，我也提了 issue [ChuckJonas/vscode-apex-pmd#75](https://github.com/ChuckJonas/vscode-apex-pmd/issues/75) 但是看到历史的issue，他们似乎不愿意放开 ）
> 
> 刚好我开发过VSCode的扩展，因此想基于 这个扩展开发一个 针对p3c的VSCode 扩展，https://github.com/rectcircle/vscode-p3c 今天刚启动，打算周末时间开发下。

中文乱码问题似乎无法重现，应该不是普遍问题，demo 可以 看这 [apex-pmd-java-test.zip](https://github.com/ChuckJonas/vscode-apex-pmd/files/4382479/apex-pmd-java-test.zip)

**Comment by byyxx128** [comment]
支持……但不要标题党吧……还有把你标题改改，不醒目。我打个样——
***
【Feature Request】Please provide an extension of VS Code
【功能需求】建议提供 VS Code 的扩展程序
***
然后内容你简单描述下即可。结果你内容里一大堆啥玩意……

**Comment by rectcircle** [comment]
非官方 P3C VSCode 扩展初版已经上线：https://marketplace.visualstudio.com/items?itemName=Rectcircle.vscode-p3c

https://github.com/alibaba/p3c/issues/513
https://github.com/alibaba/p3c/issues/498
https://github.com/alibaba/p3c/issues/194

**Comment by Moonzzz** [comment]
第一次评论 不知道咋生成了那个 我的错

**Comment by ShirleyLoveGIS** [comment]
求助：Unable to install 'rectcircle.vscode-p3c' extension because it is not compatible with the current version of VS Code (version 1.41.1).

**Comment by rectcircle** [comment]
> 求助：Unable to install 'rectcircle.vscode-p3c' extension because it is not compatible with the current version of VS Code (version 1.41.1).

请升级 VSCode 到 1.43 +

**Comment by ShirleyLoveGIS** [comment]
> > 求助：Unable to install 'rectcircle.vscode-p3c' extension because it is not compatible with the current version of VS Code (version 1.41.1).
> 
> 请升级 VSCode 到 1.43 +

fixed.   感谢🙏

**Comment by 2pc** [comment]
thx! nice work

**Comment by yangguanbao** [comment]
欢迎共建，感谢大家对于P3C的支持与热爱。
