### ISSUE TITLE
Suppress或者exclude警告,重新扫描依然存在警告

### ISSUE THREAD

**Issue by qiutianyou** [alibaba/p3c#632]
### 环境
操作系统: mac os
IDE: ultimate 2019.1.3
### 扫描结果
实现了一个第三方包的接口,扫描时提示方法名称必须遵守驼峰形式.
![image](https://user-images.githubusercontent.com/20854692/71714371-8e692580-2e48-11ea-8b50-87882ded4601.png)

### 操作1:抑制警告
方法加上了@SuppressWarnings("AlibabaLowerCamelCaseVariableNaming"),重新扫描,依然提示有违反驼峰形式
![image](https://user-images.githubusercontent.com/20854692/71714384-9f199b80-2e48-11ea-9fc1-bbb193999b8f.png)

### 操作2:排除该方法
exclude后,重新扫描,也依然提示有违反驼峰形式
![image](https://user-images.githubusercontent.com/20854692/71714395-a93b9a00-2e48-11ea-9e2a-8edad13fe997.png)

### 结论
Suppress或者exclude警告,重新扫描依然存在警告.
![image](https://user-images.githubusercontent.com/20854692/71714413-bc4e6a00-2e48-11ea-82b4-56a08cebd1d8.png)

**Comment by SeanCai** [comment]
为了尽量让大家遵循规约，插件屏蔽了SuppressWarnings @qiutianyou

**Comment by Sheng0** [comment]
git hook实测有效
