### ISSUE TITLE
单个字母的驼峰规则

### ISSUE THREAD

**Issue by Ayue2229** [alibaba/p3c#634]
## 规约原文
存在单个字母的驼峰规则
## 问题描述
类似IPage，orderC被检测出来不遵守驼峰协议
## 修改建议
有些业务场景下对变量/对象/表名的定义避免不了有单字母情况的发生，查看之前类似的问题：
https://github.com/alibaba/p3c/issues/532
https://github.com/alibaba/p3c/issues/523
一个回答会修改，一个回答不符合规范，请问这个问题会怎么处理呢？

**Comment by yangguanbao** [comment]
以此结论为主：
![image](https://user-images.githubusercontent.com/25759061/72422234-04f91200-37bd-11ea-84ba-1ec7bf812f6f.png)
