### ISSUE TITLE
DO/DTO/VO等POJO类扫描规则

### ISSUE THREAD

**Issue by BestRoach** [alibaba/p3c#637]
在Eclipse中，只有命名为结尾为DO、DTO、VO等尾缀，使用代码规范检查的时候才能按照对应的代码规范来检查。比如说：我们现在的项目代码比较陈旧，老的代码规约中要求必须使用Do，Dto，Vo这样的后缀（这样命名并不符合现有规范）。但是这样的话就无法扫描到了。
建议能否同样检查Do、Dto、Vo这样命名的文件，或者提供一个配置文件，可以针对这几个对象做相应的文件名映射。

**Comment by yangguanbao** [comment]
这个反向扫描，我们暂时不做实现。推荐大家在平时写代码时，注意POJO类的命名方式。
