### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by 643562798** [alibaba/p3c#638]
An error occurred while collecting items to be installed
session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
No repository found containing: osgi.bundle,org.apache.servicemix.bundles.aopalliance,1.0.0.3

Spring Tool Suite 4 
Version: 4.5.0.RELEASE
Build Id: 201912171052

**Comment by Yuyang105** [comment]
@imu2008 看一下哈

**Comment by imu2008** [comment]
@643562798 sts没有充分测试兼容性，可以拉个log看看，欢迎提bug给我们

**Comment by xiaobin-zhang** [comment]
@imu2008 请问这个问题解决了吗？

```

!ENTRY org.eclipse.equinox.p2.engine 4 4 2022-08-08 13:14:17.025
!MESSAGE An error occurred while collecting items to be installed
!SUBENTRY 1 org.eclipse.equinox.p2.engine 4 0 2022-08-08 13:14:17.025
!MESSAGE session context was:(profile=DefaultProfile, phase=org.eclipse.equinox.internal.p2.engine.phases.Collect, operand=, action=).
!SUBENTRY 1 org.eclipse.equinox.p2.artifact.repository 4 0 2022-08-08 13:14:17.025
!MESSAGE No repository found containing: osgi.bundle,com.sun.xml.bind,2.2.0.v201505121915

```
