### ISSUE TITLE
有没有对应的kotlin规约啊

### ISSUE THREAD

**Issue by TomatoYang** [alibaba/p3c#639]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TomatoYang** [comment]
希望出一个Kotlin的规约

**Comment by yangguanbao** [comment]
目前没有，如果谁有现有的规约，也可以发送邮件给我们项目组，一起共同建设。

**Comment by yangguanbao** [comment]
guanbao.yanggb@taobao.com
