### ISSUE TITLE
eclipse使用4个空格代替tab

### ISSUE THREAD

**Issue by JohnnyLeo** [alibaba/p3c#642]
## 规约原文
【强制】采用 4 个空格缩进，禁止使用 tab 字符。
说明：如果使用 tab 缩进，必须设置 1 个 tab 为 4 个空格。IDEA 设置 tab 为 4 个空格时，请勿勾选 Use tab character；而在 eclipse 中，必须勾选 insert spaces for tabs。

## 问题描述
在eclipse中仅仅勾选 insert spaces for tabs 依然不够，也有可能会出现一个tab的情况。

## 修改建议
【强制】采用 4 个空格缩进，禁止使用 tab 字符。
说明：如果使用 tab 缩进，必须设置 1 个 tab 为 4 个空格。IDEA 设置 tab 为 4 个空格时，请勿勾选 Use tab character；而在 eclipse 中，必须勾选 insert spaces for tabs，**并且在 Preferences > Java > Code Style > Formatter > Edit... > Indentation >>> Tab policy: Spaces Only；Tab size: 4。**

**Comment by yangguanbao** [comment]
在嵩山版中会进行修改。

**Comment by gujin520** [comment]
黄山版中已经修正
