### ISSUE TITLE
java 13 switch增强型功能在代码规约检测中显示异常

### ISSUE THREAD

**Issue by verguenza** [alibaba/p3c#646]
switch (a) {
                    case 1-> xxx;
                    case 2 -> yyy;
                    default -> zzz;
                }
这种写法会显示缺少default语句

**Comment by XenoAmess** [comment]
我怀疑是官方用的PMD版本太老了。他们用的6.15.0
但是我升级的时候卡在6.17.0升6.18.0的地方出bug了
嗯然后对这个switch的支持好像在6.22.0才有。
所以你等吧。搞定了的话我再来喊你。

**Comment by XenoAmess** [comment]
emm我想办法把pmd更新到6.22了
好消息是 不会再报缺default错了
坏消息是 真的缺default也不会报错
因为似乎 现在的检测器的语法 并没支持13的switch
如果要改可能得重写
com.alibaba.p3c.pmd.lang.java.rule.flowcontrol.SwitchStatementRule
你可以自己动手试试
我 不太想写这个 因为我不用新switch。。。抱歉。

**Comment by verguenza** [comment]
好的。

**Comment by XenoAmess** [comment]
> 好的。

唉 手不自觉地动了起来
做好了
你急用吗
不急的话我明天看看14的那个switch能不能一起做了 然后发

**Comment by verguenza** [comment]
> > 好的。
> 
> 唉 手不自觉地动了起来
> 做好了
> 你急用吗
> 不急的话我明天看看14的那个switch能不能一起做了 然后发

不急用。
团队这边暂时忽略了这个提醒。
同学你辛苦了。

**Comment by XenoAmess** [comment]
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/update/84365
送审了。审核过了应该就可以。

**Comment by Yuyang105** [comment]
感谢反馈，我们研究下pmd版本升级计划。
