### ISSUE TITLE
dao层采用mybatis的注解方式, 对接口的javadoc验证一定要有吗? 还有service层?

### ISSUE THREAD

**Issue by jinl2011** [alibaba/p3c#651]
## 规约原文
Ali-Check | 所有的抽象方法（包括接口中的方法）必须要用javadoc注释、除了返回值、参数、异常说明外，还必须指出该方法做什么事情，实现什么功能。
## 问题描述
问题1: 我们公司代码dao层用的是mybatis注解, 在这层也要加javadoc吗, 为什么呢?
问题2: service层的接口也要加javadoc吗, 我们没用rmi之类的调用, 还有即便用了, 为什么一定要加javadoc呢?
## 修改建议
我们公司就是写业务代码的, 没有java开源项目也, 而且我相信中国百分之九十九的公司都是这样, 业务代码如果需要javadoc来进一步描述, 这跟给代码加注释一样, 就像代码简洁之道上说的, 很少有人会维护注释. 所以我觉得对于业务代码应该去掉javadoc以及这个规范验证.

**Comment by XenoAmess** [comment]
我觉得你们要考虑的不是修改规范，而是考虑你们需不需要完全执行这套规范。
就我所知，这个规范的maven插件中有exclude功能，可以用于exclude掉你们不想囊括的类。
有关使用案例，可以到这个项目的p3d-pmd的pom里找，他们自己也有exclude掉一些特定的类的。

**Comment by XenoAmess** [comment]
另外，严格执行一套规范有的时候并不是合理的。
更极端的情况甚至是不可能的。
比方说sonarcloud的code smell check的规范中强制要求每个标注@Deprecated的function的javadoc中必须也包含@deprecated注解。
但是maven-javadoc-plugin的规范中强制要求任何标注@Deprecated的function的javadoc中必须不能包含@deprecated注解。
所以当我试图同时遵循这两条规则的时候我就必须做点选择。
我说这个的意思就是，语法规范这种东西，不要强求，应该按照实际需要以及project manager的喜好来决定。

**Comment by jinl2011** [comment]
> 我觉得你们要考虑的不是修改规范，而是考虑你们需不需要完全执行这套规范。
> 就我所知，这个规范的maven插件中有exclude功能，可以用于exclude掉你们不想囊括的类。
> 有关使用案例，可以到这个项目的p3d-pmd的pom里找，他们自己也有exclude掉一些特定的类的。

多谢指点

**Comment by jinl2011** [comment]
> 另外，严格执行一套规范有的时候并不是合理的。
> 更极端的情况甚至是不可能的。
> 比方说sonarcloud的code smell check的规范中强制要求每个标注@deprecated的function的javadoc中必须也包含@deprecated注解。
> 但是maven-javadoc-plugin的规范中强制要求任何标注@deprecated的function的javadoc中必须不能包含@deprecated注解。
> 所以当我试图同时遵循这两条规则的时候我就必须做点选择。
> 我说这个的意思就是，语法规范这种东西，不要强求，应该按照实际需要以及project manager的喜好来决定。

很有道理
