### ISSUE TITLE
SuppressWarnings and noinspection broken in idea plugin.

### ISSUE THREAD

**Issue by XenoAmess** [alibaba/p3c#656]
**Describe the bug**
in your idea plugin:

`@SuppressWarnings("AlibabaMethodTooLong")` broken.
`//noinspection AlibabaAvoidComplexCondition` broken.

**To Reproduce**
1.download and open project https://github.com/cyanpotion/x8l/tree/53dae927017eef3dc16dfb59d53022940e60933b
using idea 2020.1 beta
2. run Analyse/Inspect Code

**Expected behavior**
I shall never see those error in Ali-check as I already add the @SuppressWarnings / noinspection 

**Screenshots**
![idea64_2020-03-27_17-08-52](https://user-images.githubusercontent.com/17455337/77740248-debde100-704d-11ea-92fe-cae2ea148a2d.png)
![2020-03-27_17-08-59](https://user-images.githubusercontent.com/17455337/77740335-044aea80-704e-11ea-984c-8a80e057548b.png)
![idea64_2020-03-27_17-09-39](https://user-images.githubusercontent.com/17455337/77740253-df567780-704d-11ea-8076-1478883cfbd0.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser chrome (why you need know this?)
 - Version 2.0.1

**Comment by yangguanbao** [comment]
I don't agree with you. As our initial plan, the p3c not allow users to suppress any rule checking. sorry, but you are grateful to test our plugin.
