### ISSUE TITLE
修改提示级别不生效

### ISSUE THREAD

**Issue by wangzhi2015** [alibaba/p3c#657]
我在IDEA中把if语句不加大括号的提示级别由原先的Blocker改为Major，并且重启了IDEA，如下图：
![image](https://user-images.githubusercontent.com/16057923/78626541-a75afa00-78c1-11ea-98ea-f925c5ed25b8.png)
但是扫描之后的结果中，发现并未生效，if语句的错误级别还是Blocker
![image](https://user-images.githubusercontent.com/16057923/78626646-f4d76700-78c1-11ea-9842-55fe662b45c3.png)

**Comment by SeanCai** [comment]
@wang
这里修改只对实时扫描的提示生效哈
