### ISSUE TITLE
请问有哪个开源项目是根据此规约开发的？参考一下？

### ISSUE THREAD

**Issue by jierui001** [alibaba/p3c#658]
## 规约原文
请问有哪个开源项目是根据此规约开发的？参考一下？
## 问题描述
请问有哪个开源项目是根据此规约开发的？参考一下？
## 修改建议
请问有哪个开源项目是根据此规约开发的？参考一下？

**Comment by byyxx128** [comment]
求人不如求己……这个本来是阿里自用的项目，然后放出来造福大家，所以遵守最好的当然是阿里自己的项目……因为阿里的项目应该是要求强制遵守了。

**Comment by XenoAmess** [comment]
阿里的所有项目【理论上】强制使用这个协议 所以可以 去找 https://github.com/alibaba
此外一般没人严格执行这玩意
至少我个人的项目是拿这玩意做个代码检查器 跟sonar一样用 并不严格要求全过。

**Comment by yangguanbao** [comment]
阿里巴巴内部目前90%以上的同学都是安装了此插件，进行规范的拉齐。随着华山版，泰山版的不断发布，以及我们P3C项目组的不断精进，业界符合此规约的开源项目越来越多。
