### ISSUE TITLE
接口中方法提示没有使用Override注解

### ISSUE THREAD

**Issue by zlp1992** [alibaba/p3c#659]
如图，接口方法提示没有使用Override
![image](https://user-images.githubusercontent.com/11548492/78887536-9ad9cb80-7a92-11ea-8911-58ef1d0781ce.png)

ide版本：
IntelliJ IDEA 2018.1.1 (Ultimate Edition)

**Comment by XenoAmess** [comment]
你去看

你的同一个项目下
    用了你这个接口的实现的类
        的这个函数的重载函数

有没有加Override
有的话加上 就行了

**Comment by SeanCai** [comment]
@zlp1992 如 @XenoAmess 所说
