### ISSUE TITLE
Scan the content after git commit

### ISSUE THREAD

**Issue by jmilktea** [alibaba/p3c#661]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
**Whether to support scanning the content of this submission after git submission, which is very helpful for code review**

**Describe alternatives you've considered**

**Additional context**

**Comment by XenoAmess** [comment]
usually we do scan the git commit BEFORE it is made, but not AFTER.
you can achieve this using idea like this:
![2020-04-11_21-57-22](https://user-images.githubusercontent.com/17455337/79045804-93a3f080-7c3f-11ea-9f0d-638d99f47955.png)
troggle the checkbox "perform code analysis" and then you click commit, it will pump up a hint like the screenshot shown.
click the blue [Review] button then the codes will be analysed.

**Comment by jmilktea** [comment]
> usually we do scan the git commit BEFORE it is made, but not AFTER.
> you can achieve this using idea like this:
> ![2020-04-11_21-57-22](https://user-images.githubusercontent.com/17455337/79045804-93a3f080-7c3f-11ea-9f0d-638d99f47955.png)
> troggle the checkbox "perform code analysis" and then you click commit, it will pump up a hint like the screenshot shown.
> click the blue [Review] button then the codes will be analysed.

Scanning after submission is sometimes very useful, for example, when looking at the branch code submitted by someone else, I want to see if the code he submitted this time meets the specifications

**Comment by Yuyang105** [comment]
流程机制不放在idea插件体系中，可以考虑自己集成在CI体系中
