### ISSUE TITLE
规则插件与文档的规则数目不匹配

### ISSUE THREAD

**Issue by slowwalkerlcr** [alibaba/p3c#662]

**Comment by XenoAmess** [comment]
因为有的不好做
并且没人做
（或者阿里自己其实有只是没放出来给我们用？哈哈不大可能其实）
其实非常欢迎你去实现规则 如果没问题的话我会考虑merge进我TPM那边

**Comment by yangguanbao** [comment]
文档的规则数肯定大于实现的规则数，有些规则是很难实现扫描的。
阿里巴巴内外的插件功能基本相似。
当然新上线的扫描，阿里内部会先试用 。
