### ISSUE TITLE
what is com.intellij.velocity in plugin.xml in idea plugin?

### ISSUE THREAD

**Issue by XenoAmess** [alibaba/p3c#665]
https://github.com/alibaba/p3c/blob/master/idea-plugin/p3c-idea/src/main/resources/META-INF/plugin.xml#L75

I looked through idea's modules and cannot find such a module.
besides, you seems have no config with this.
so shall we just delete this line?

**Comment by SeanCai** [comment]
com.alibaba.p3c.pmd.lang.vm.rule.other.UseQuietReferenceNotationRule

**Comment by XenoAmess** [comment]
No. 
as far as I learened
`    <depends optional="true">com.intellij.velocity</depends>`
is totally useless here.
suggest deleting it.
