### ISSUE TITLE
I found the reason why I cannot upgrade pmd to 6.19.0

### ISSUE THREAD

**Issue by XenoAmess** [alibaba/p3c#669]
This is a complicated thing and I speak poor english so I will try my best to make it clear.
1. you want to use net.sourceforge.pmd.SourceCodeProcessor
2. you want to change some behavior of net.sourceforge.pmd.SourceCodeProcessor(using google cache instead of its original cache)
3. net.sourceforge.pmd.SourceCodeProcessor write it private the function you wanna change, so you cannot change it.
4. you fork net.sourceforge.pmd.SourceCodeProcessor to com.alibaba.p3c.idea.pmd.SourceCodeProcessor, and apply your logic there.
5. pmd 6.19.0 changed some logic in net.sourceforge.pmd.SourceCodeProcessor.
6. I upgrade pmd to 6.19.0 and I did not change com.alibaba.p3c.idea.pmd.SourceCodeProcessor to follow pmd's change.
7. crash.

So, as we known about this, we can take action.
I CAN try to make the change com.alibaba.p3c.idea.pmd.SourceCodeProcessor  need , to coorperate with pmd 6.19.0
But I think we'd better persuade pmd guys about changing the funcions in pmd.SourceCodeProcessor form private to protected, thus we can avoid tons of troubles.

**Comment by yangguanbao** [comment]
l already contacted you by email, and I close the issue firstly.
