### ISSUE TITLE
pmd包和common包有什么用能解释下么

### ISSUE THREAD

**Issue by Springs-wu** [alibaba/p3c#67]
一定要依赖吗？

**Comment by SeanCai** [comment]
p3c-pmd是pmd规则的实现，如果你们的系统用到pmd，可以依赖这个包进行集成，具体集成方式请阅读pmd官方文档

common包是指p3c-common吗？这个包是IDEA插件中规则检测实现的提取部分，我们内部也会依赖这个包，尽量内外保持一致
