### ISSUE TITLE
能否忽略指定的包不进行扫描？

### ISSUE THREAD

**Issue by jearton** [alibaba/p3c#670]

**Comment by XenoAmess** [comment]
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/update/84765
https://github.com/XenoAmess/p3c/blob/xenoamess_maintain_fork/idea-plugin/README_cn.md
我TPM那边现在有加一套黑名单机制
嗯指定的包可能不太好做，因为PMD读包名比较麻烦（我不会）
现在有类名黑名单，规则黑名单，类-规则pair黑名单
勉强应该能用

**Comment by jearton** [comment]
@XenoAmess 这个是你自己扩展的吧，官方的没有这个能力吗？还有你这个支持类名通配符吗？比如*Mapper，表示所有以Mapper结尾的类。

**Comment by XenoAmess** [comment]
> @XenoAmess 这个是你自己扩展的吧，
是
> 官方的没有这个能力吗？
阿里人才济济，我更倾向于认为“官方没有这个意愿”
> 还有你这个支持类名通配符吗？比如*Mapper，表示所有以Mapper结尾的类。
不支持。因为不希望黑名单过多的类。
