### ISSUE TITLE
新版将会出现的问题

### ISSUE THREAD

**Issue by ijliym** [alibaba/p3c#674]
## 规约原文
如图
![image](https://user-images.githubusercontent.com/43025881/80070303-5875bb80-8575-11ea-9617-713b6ded5250.png)

## 问题描述
`阿里巴巴Java开发手册（泰山版）` 上图中的地方将会少一个空格。
## 修改建议
你知道的。

**Comment by ijliym** [comment]
![image](https://user-images.githubusercontent.com/43025881/80071247-dbe3dc80-8576-11ea-9c69-d2ec12f60f9d.png)

**Comment by XenoAmess** [comment]
您就是github列文虎克？

这个要修的话得等他们上传了泰山版再说2333

https://github.com/alibaba/p3c/pull/671

**Comment by ijliym** [comment]
不是，不是。

**Comment by yangguanbao** [comment]
嵩山版本中修复

**Comment by XenoAmess** [comment]
> 嵩山版本中修复
等等，是孤尽？不管了先膜再说

**Comment by yangguanbao** [comment]
感谢大家对于手册的支持，我从头到尾全部REVIEW，同类问题全部修复，静待嵩山。
