### ISSUE TITLE
适配部分自定义Doc注释

### ISSUE THREAD

**Issue by HaceraI** [alibaba/p3c#678]
我拥有着一套专属自己的Doc文档模板，当它和编码规约扫描时就会发生如下情况：
![image](https://user-images.githubusercontent.com/48341368/80337651-fecf0300-888c-11ea-9489-bbeeec0cff99.png)
如果我不想让它提示，我可以选择：
  1). 增加@author.
  2). 关闭实时检测功能.
当前，在我认为以上这两种都不是最佳解决方案, 能否在规范检查中适配一下关键字?
Thank.

**Comment by XenoAmess** [comment]
嗯我那边的TPM已经做好配置模块了。
https://github.com/XenoAmess/p3c/blob/xenoamess_maintain_fork/idea-plugin/README_cn.md
只是现在不是jetbrains工作日所以得等审核。
你如果用TPM的话，到时候把ClassMustHaveAuthorRule加进黑名单就行了。
你急用吗，不急用就等idea审核，会放心点。
急用我过会儿把binary传到github。

**Comment by HaceraI** [comment]
好的，感谢

**Comment by XenoAmess** [comment]
好了 审核过了
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/update/84765
首先创建文件p3c_config.x8l于你的项目根目录
然后填写内容
`<com.alibaba.p3c.pmd.config version=0.0.1><rule_class_pair_blacklist><IntMax>ClassMustHaveAuthorRule>>>`
目测应该这样就行了

**Comment by HaceraI** [comment]
好像仍然存在问题:
这是我下载的插件：
![image](https://user-images.githubusercontent.com/48341368/80455126-c6e3c080-895d-11ea-8497-9cc9dfc744db.png)
这是我配置的x8l：
![image](https://user-images.githubusercontent.com/48341368/80455293-0ca08900-895e-11ea-9a6f-4b0082fbc363.png)
Result:
![image](https://user-images.githubusercontent.com/48341368/80455373-348fec80-895e-11ea-8cb0-184f00da1e4e.png)
另外，我还有几个疑问：
1). 如果项目结构是多模块的，x8l文件是只要存放在root根目录下即可还是每个模块的根目录下都需要存放;

**Comment by XenoAmess** [comment]
> 好像仍然存在问题:
> 这是我下载的插件：
> ![image](https://user-images.githubusercontent.com/48341368/80455126-c6e3c080-895d-11ea-8497-9cc9dfc744db.png)
> 这是我配置的x8l：
> ![image](https://user-images.githubusercontent.com/48341368/80455293-0ca08900-895e-11ea-9a6f-4b0082fbc363.png)
> Result:
> ![image](https://user-images.githubusercontent.com/48341368/80455373-348fec80-895e-11ea-8cb0-184f00da1e4e.png)
> 另外，我还有几个疑问：
> 1). 如果项目结构是多模块的，x8l文件是只要存放在root根目录下即可还是每个模块的根目录下都需要存放;
1.例子
https://github.com/XenoAmess/demo_p3c_20200428
2.目前 我们只做了:
(1)对于在idea中使用插件p3c-idea-plugin, 在检测的时候（运行Tools->Alibaba Code Guidelines->Alibaba Code Guidelines Analyze，或者右键点击文件夹/代码，选择Alibaba Code Guidelines Analyze，或者Analyze Inspect Code）的结果集中运用黑名单
(2)对于在maven中使用p3c-pmd,对在maven plugin 的 maven-pmd-plugin中使用p3c-pmd运用黑名单。

对于在idea中使用插件p3c-idea-plugin来说，当前对于一个idea project，是直接检测project根文件夹下的p3c_config.x8l的。当前没支持对于一个project下多个maven项目的分别做黑名单（抱歉，那个有点难讲真）

对于在maven中使用p3c-pmd来说，当前是在运行maven的时候读取mvn运行目录下的p3c_config.x8l。

3.是的，参考在1.中的例子的话，现在可以做到扫描的时候结果中不出现该错误，但是直接看代码的时候还是会被标注错误。
emm因为我自己用的时候一般只关心扫出来的结果，然后对着结果列表一个个找/修，所以忘了还得把错误显示也屏蔽掉这回事了。。。抱歉
我晚点去看看有没有个合适的地方可以插入这个检测机制。

**Comment by XenoAmess** [comment]
修了 现在（2.0.2.4x） 会同时屏蔽掉idea窗体中的错误代码highlight
相关使用demo的话 在
https://github.com/XenoAmess/demo_p3c_20200428
有bug的话及时反馈嗷。谢谢。
