### ISSUE TITLE
文件名修改后,之前的规约问题还是显示,且关不掉

### ISSUE THREAD

**Issue by JavaAIer** [alibaba/p3c#679]
**Describe the bug**
我下了一个代码<Spring MVC+MYBatis企业应用实战>配套代码,里面有些类不符合驼峰式命名,我就把它改成了规范要求的样子(文件名,类名,被引用的代码等).
然后eclipse里面,刷新后,编译什么的都正常了,但是规约上面这个错误就不知道怎么清除,我重新在项目的根目录上和打开的类文件上分别点击了分析代码(阿里编码规范扫描),都不行.

**To Reproduce**
see above

**Expected behavior**
能扫描出哪些文件已经不存在了,并清除依赖于这些文件的规约提示.

**Screenshots**
![image](https://user-images.githubusercontent.com/44077290/80469923-d4a44080-8973-11ea-87dd-571a1832509a.png)

**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser  Eclipse IDE for Enterprise Java Developers.
 - Version: 2020-03 (4.15.0)
Build id: 20200313-1211

**Comment by yansheng836** [comment]
这个插件没有自动刷新功能的，修改后需要重新扫描（好像不会关不掉啊）。

**Comment by JavaAIer** [comment]
> 这个插件没有自动刷新功能的，修改后需要重新扫描（好像不会关不掉啊）。

我是把eclipse关掉后,再打开,再扫描才行的.
