### ISSUE TITLE
使用spring  tool suite 无法进行阿里编码规约扫描

### ISSUE THREAD

**Issue by JavaAIer** [alibaba/p3c#680]
**Describe the bug**
同样一个项目,在eclipse里面能扫出问题,在spring tool suite里面扫描结果是空
**To Reproduce**
see above

**Expected behavior**
spring tool suite能正常使用p3c工具
**Screenshots**
无
**Desktop (please complete the following information):**
 - OS: windows 10 
 - Browser spring tool suite
 - Version sts-4.5.1.RELEASE

**Comment by imu2008** [comment]
@JavaAIer 必现问题么？可以试试在eclipse里面装sts插件

**Comment by JavaAIer** [comment]
> @JavaAIer 必现问题么？可以试试在eclipse里面装sts插件

这个没问题,只是直接用sts就不能用p3c插件.
