### ISSUE TITLE
常量字符串被当成魔法值

### ISSUE THREAD

**Issue by JavaAIer** [alibaba/p3c#682]
**Describe the bug**
比如一个表中一些字段，写在这个表的相关操作类中被当作魔法值

**To Reproduce**
如上
**Expected behavior**
魔法值应该不要限制字符串常量， 或者可以添加开关来决定是否需要扫描这个文件中的魔法值
**Screenshots**

![image](https://user-images.githubusercontent.com/44077290/80536732-65f7cf00-89d5-11ea-9e69-e47d84cb4089.png)

**Comment by XenoAmess** [comment]
可是你这个就是标准的魔法值啊。
你这种本来就应该单独建一个Util或者Data类，然后这些字符串作为public  static final常量，然后去引。
你要说这都不是魔法值那天底下就没啥魔法值了好吧？

**Comment by JavaAIer** [comment]
> 可是你这个就是标准的魔法值啊。
> 你这种本来就应该单独建一个Util或者Data类，然后这些字符串作为public static final常量，然后去引。
> 你要说这都不是魔法值那天底下就没啥魔法值了好吧？

可是这样,这个代码就写得极其臃肿了啊,可读性可能还不如直接在引号里面写上字段名.

**Comment by XenoAmess** [comment]
> > 可是你这个就是标准的魔法值啊。
> > 你这种本来就应该单独建一个Util或者Data类，然后这些字符串作为public static final常量，然后去引。
> > 你要说这都不是魔法值那天底下就没啥魔法值了好吧？
> 
> 可是这样,这个代码就写得极其臃肿了啊,可读性可能还不如直接在引号里面写上字段名.

有这个规定的目的就是1.避免typo导致bug。2.让人知道这个常量是干嘛的。
怎么说呢所有规定都有利有弊。
你要实在看不下去这个规定可以考虑把他屏蔽掉。

**Comment by JavaAIer** [comment]
> > > 可是你这个就是标准的魔法值啊。
> > > 你这种本来就应该单独建一个Util或者Data类，然后这些字符串作为public static final常量，然后去引。
> > > 你要说这都不是魔法值那天底下就没啥魔法值了好吧？
> > 
> > 
> > 可是这样,这个代码就写得极其臃肿了啊,可读性可能还不如直接在引号里面写上字段名.
> 
> 有这个规定的目的就是1.避免typo导致bug。2.让人知道这个常量是干嘛的。
> 怎么说呢所有规定都有利有弊。
> 你要实在看不下去这个规定可以考虑把他屏蔽掉。
> 或者修改黑名单，把你不想转常量的字符串都加进去。

所以我的预期是:魔法值应该不要限制字符串常量， 或者可以添加开关来决定是否需要扫描这个文件中的魔法值,对于有些生成的java文件,就不要扫描了.

**Comment by Yuyang105** [comment]
暂时不支持白名单

**Comment by JavaAIer** [comment]
> 暂时不支持白名单

好叭,只是字符串常量的用途确实广泛,希望官方后期考虑一下,谢谢啦!
