### ISSUE TITLE
在idea中对相同代码重复扫描，结果不一致

### ISSUE THREAD

**Issue by xiongyh** [alibaba/p3c#683]
**Describe the bug**
在idea中对相同代码重复扫描，结果不一致。blocker/critical/major结果不一致

**To Reproduce**
1. 选择我的gz-index包
2. 右键选择“编码规约扫描”
3. 扫描结束查看结果（见下图的3次扫描结果）

环境：win10 IDEA2018.3.6
![gz-index3](https://user-images.githubusercontent.com/15508208/80586348-6630b280-8a47-11ea-9f47-e9c0b7cf51d0.png)
![gz-index2](https://user-images.githubusercontent.com/15508208/80586352-6761df80-8a47-11ea-971e-2bdd12f0c934.png)
![gz-index1](https://user-images.githubusercontent.com/15508208/80586353-68930c80-8a47-11ea-8022-2c3fb7f7abe5.png)

**Comment by XenoAmess** [comment]
有一说一确实
好像项目过大以后是会这样。
不知道他们哪里写错了

**Comment by cnlinjie** [comment]
刚想提，真的是有点想喷饭。。
刚在给团队演示怎么怎么规范，
”你看，要这样，点击模块，右键，然后点击「编码规约扫码」，他就会提示你哪里不规范了。“
”你看，这边有3个问题，我们按照规范改下，然后在扫描一遍。只剩下两个了，对不对？“
”好，我们再改一下，再扫描一遍看看效果。“
”卧槽，卧槽，怎么回事，6个？没事，我们再来一遍，你看，只剩下3个了吧“
”卧槽，刚刚不是2个？没事，再来！再扫描，卧槽，4个？“
”再来！6个！再来，4个！，再来，2个！，再来，3个！”
“？？？ 掷骰子么？“
”没事，先不用吧，你们继续写代码，写规范一点。我去研究下“

**Comment by cnlinjie** [comment]
一个项目，没有改动任何代码的情况下，扫描了三次：
![image](https://user-images.githubusercontent.com/3601638/81144808-71d02c00-8fa7-11ea-991d-428aeaac5302.png)

![image](https://user-images.githubusercontent.com/3601638/81144814-7694e000-8fa7-11ea-8ceb-ee506757de5b.png)


![image](https://user-images.githubusercontent.com/3601638/81144802-6e3ca500-8fa7-11ea-9d97-206b09773a13.png)

**Comment by xiongyh** [comment]
希望快一点解决哦，确实很影响使用

**Comment by xiongyh** [comment]
> 刚想提，真的是有点想喷饭。。
> 刚在给团队演示怎么怎么规范，
> ”你看，要这样，点击模块，右键，然后点击「编码规约扫码」，他就会提示你哪里不规范了。“
> ”你看，这边有3个问题，我们按照规范改下，�然后在扫描一遍。只剩下两个了，对不对？“
> ”好，我们再改一下，再扫描一遍看看效果。“
> ”卧槽，卧槽，怎么回事，6个？没事，我们再来一遍，你看，只剩下3个了吧“
> ”卧槽，刚刚不是2个？没事，再来！再扫描，卧槽，4个？“
> ”再来！6个！再来，4个！，再来，2个！，再来，3个！”
> “？？？ 掷骰子么？“
> ”没事，先不用吧，你们继续写代码，写规范一点。我去研究下“

哥，你的描述太有画面感了

**Comment by XenoAmess** [comment]
有一说一，最开始我还以为是我改炸了。
后来切了原版才发现 这个bug原版就有
这就很尴尬2333
只要你的代码到了几万行 这个bug几乎必定触发

**Comment by Yuyang105** [comment]
@SeanCai 麻烦看一下

**Comment by zysparrow** [comment]
问题 +1

**Comment by shel-li** [comment]
问题 +1

**Comment by MinaAndLuoXia** [comment]
2020/10/09 问题依然存在

**Comment by LuffyGao** [comment]
更新到2.1.0 版本

**Comment by CCNaive** [comment]
更新到2.1.0 问题就解决了吗

**Comment by CCNaive** [comment]
> 
更新到2.1.0 问题就解决了吗

**Comment by MinaAndLuoXia** [comment]
马俊男（Rorschach）邮件已收到！
