### ISSUE TITLE
开发手册的最新版本的中文版是从这个项目里下载的吗？没找着最新版的入口在哪呢。。

### ISSUE THREAD

**Issue by OrdinaryYZH** [alibaba/p3c#685]
RT

**Comment by XenoAmess** [comment]
https://github.com/alibaba/p3c/raw/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E6%B3%B0%E5%B1%B1%E7%89%88%EF%BC%89.pdf
