### ISSUE TITLE
对单个字母的类名提示：不符合UpperCamelCase 命名风格

### ISSUE THREAD

**Issue by cnlinjie** [alibaba/p3c#686]
**Describe the bug**
不知道是Bug还是正常的，项目中偶尔会有单个类名的类，比如常用的：
R 
return R.ok();
但是提示：不符合UpperCamelCase 命名风格
我忽略掉后，在commit 提交时，还是会扫描到，有点烦恼。

**To Reproduce**

**Expected behavior**
对于单个类名，希望是符合规约的，不会提示。

**Screenshots**
![image](https://user-images.githubusercontent.com/3601638/81137195-83f2a000-8f90-11ea-9215-4f1223eb6422.png)

**Smartphone (please complete the following information):**
 - Device:  Macbook pro 
 - OS:  MacOS 10.14.5 
 - IDE:  Intellij Idea 2020.1  

** Plugins Version**
2.0.2 

**Additional context**

**Comment by XenoAmess** [comment]
为什么会有单个字母的类？
类名R是否能完全说明其用途？

**Comment by cnlinjie** [comment]
@XenoAmess   这个类大意就是 ReturnModel 或者 ReturnObject  ，在Rest API  用来转载对象，返回json 
比如：
 ```java
  @GetMapping("/test")
    public R test() {
        return R.ok();
    }
```
类的全定义如下：
```java
public class R extends HashMap<String, Object> {
	private static final long serialVersionUID = 1L;
	
	public R() {
		put("code", 0);
		put("msg", "success");
	}
	
	public static R error() {
		return error(500, "ERROR");
	}
	
	public static R error(String msg) {
		return error(500, msg);
	}
	
	public static R error(int code, String msg) {
		R r = new R();
		r.put("code", code);
		r.put("msg", msg);
		return r;
	}

	public static R ok(String msg) {
		R r = new R();
		r.put("msg", msg);
		return r;
	}
	
	public static R ok(Map<String, Object> map) {
		R r = new R();
		r.putAll(map);
		return r;
	}
	
	public static R ok() {
		return new R();
	}

	@Override
	public R put(String key, Object value) {
		super.put(key, value);
		return this;
	}
}
```

**Comment by XenoAmess** [comment]
那你那个类就应该叫ReturnModule或者ReturnObject啊。
你不会真觉得这么个类该叫R吧

**Comment by cnlinjie** [comment]
@XenoAmess    行吧，，那能否忽略呢，目前在类那边忽略了可以，但是git commit 时，检测还是会检测到。

**Comment by XenoAmess** [comment]
那你要是真想要黑名单机制的话只能换TPM了。
官方版似乎没有做黑名单的打算（目前看来）。
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
装好以后
然后 给你个例子
https://github.com/XenoAmess/demo_p3c_20200506
你可以clone下来这个demo自己调试
如果这个效果是你想要的话
去把p3c_config.x8l复制到你的idea项目根目录就行了。
重新执行扫描应该就不会爆这个了。

**Comment by cnlinjie** [comment]
@XenoAmess  应该还是那个扫描不准确的bug，那个解决了这个应该也解决了。

**Comment by XenoAmess** [comment]
> @XenoAmess 应该还是那个扫描不准确的bug，那个解决了这个应该也解决了。

我说了我做了黑名单机制可以解决你这个问题。
你要想用可以去用。
你要是坚定阿里主义者的话可以等官方。他们平均一年更新四次。

**Comment by Yuyang105** [comment]
@XenoAmess 感谢回复
