### ISSUE TITLE
方法内部单行注释，为什么要在被注释语句上方另起一行？

### ISSUE THREAD

**Issue by JueLance** [alibaba/p3c#687]
## 规约原文
第4条【强制】 方法内部单行注释，在被注释语句上方另起一行，使用//注释。方法内部多行注释使
用/* */注释，注意与代码对齐
## 问题描述
rt, 方法内部单行注释，为什么要在被注释语句上方另起一行？
## 修改建议
1. 手册只说了强制，并没有给出原因。之前看过很多代码，很多也是写在语句的后面。这样强制的目的是什么？
2. 建议有些强制的建议给出原因。而非”【强制】“就完了。

**Comment by XenoAmess** [comment]
如果涉及局部变量定义的话 写在上边一行 很多编辑器会把该注释视为对该局部变量的说明。
别的情况我也不太理解为什么要强制。

**Comment by yangguanbao** [comment]
1）行尾有长有短。
2）另外，一行长度不能超过120字符，容易超出。

**Comment by baiqiantao** [comment]
> 1）行尾有长有短。
> 2）另外，一行长度不能超过120字符，容易超出。

既然"有长有短"、"容易超出"，那就不能"强制"呀！
我一行只有十几个字符的时候，为什么也不可以呢？
