### ISSUE TITLE
Map/Set的key为自定义对象时，必须重写hashCode和equals。

### ISSUE THREAD

**Issue by kentkwan** [alibaba/p3c#69]
Class对象非自定义对象，并且全局唯一，没有必要重写hashCode和equals。

**Comment by looly** [comment]
我也遇到相同问题。希望解决

**Comment by fudax** [comment]
只要key不是jdk原生基础类型，都要重写，好像是这么说的

**Comment by ZuessYang** [comment]
也遇到相同问题，部分数据是protobuf生成的，也一直在报这个提示

**Comment by folochina** [comment]
Set<byte[]> 也是一样不允许

**Comment by xuantan** [comment]
@kentkwan 能否提供下具体代码片段？

**Comment by SeanCai** [comment]
https://github.com/alibaba/p3c/issues/58
