### ISSUE TITLE
集合转数组的说明有误

### ISSUE THREAD

**Issue by Kevan807680925** [alibaba/p3c#690]
## 规约原文
![image](https://user-images.githubusercontent.com/16112348/81390754-931f4c80-914e-11ea-85ba-b6d9510141fd.png)

## 问题描述
说明当中的2有疑问，jdk8中参数数组长度等于0和小于size应该是同样的逻辑

**Comment by Kevan807680925** [comment]
![image](https://user-images.githubusercontent.com/16112348/81391227-5011a900-914f-11ea-8598-e00ec433cafe.png)
补充jdk8 ArrayList的toArray方法截图

**Comment by XenoAmess** [comment]
是，但是创建一个长度为0的数组明显更快（一般认为）。

**Comment by yangguanbao** [comment]
这个没有歧义，因为new String[1]；分配了空间，有点浪费。
进入toArray逻辑的确是一样的。

**Comment by Kevan807680925** [comment]
@yangguanbao 秒懂，谢谢大佬
