### ISSUE TITLE
规约中应用分层箭头关系问题，是否为数据流向关系，而非直接依赖关系？

### ISSUE THREAD

**Issue by JL-Code** [alibaba/p3c#700]
## 问题描述
![image](https://user-images.githubusercontent.com/14163944/82984666-331d1700-a025-11ea-97e9-c85c5d1b81e9.png)

**Comment by yangguanbao** [comment]
这个描述，我们在嵩山版中进行修复，感谢支持阿里巴巴Java开发手册。

**Comment by yangguanbao** [comment]
https://mp.weixin.qq.com/s/-nOnyZgh2x-L9yv2VfJuuA?spm=a1z2e.8325955.0.0.50ce4f9bun06oL
嵩山版中已经修复，敬请关注，感谢对《Java开发手册》的一贯支持。
