### ISSUE TITLE
如何使用注解屏蔽掉某些代码块的扫描

### ISSUE THREAD

**Issue by wenPKtalk** [alibaba/p3c#703]
因为历史原因，某些代码块并不想参与到扫描中。添加了@SuppressWarnings("ALL")在类上，没起作用

**Comment by XenoAmess** [comment]
> 因为历史原因，某些代码块并不想参与到扫描中。添加了@SuppressWarnings("ALL")在类上，没起作用

我问过作者了，他们考虑过，但是最终决定不提供屏蔽扫描方法（出于一些考量）。

如果你真的需要屏蔽，那么可以考虑TPM。
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

屏蔽相关说明：
https://github.com/XenoAmess/p3c/blob/xenoamess_maintain_fork/idea-plugin/README_cn.md
