### ISSUE TITLE
CPU占用率飙升

### ISSUE THREAD

**Issue by qzyu92** [alibaba/p3c#705]
对代码进行编辑后，插件cpu占用率飙升。

![微信图片_20200602101117](https://user-images.githubusercontent.com/44388998/83472487-ef5d5e00-a4b9-11ea-91e4-834afc56f1e2.png)

**OS Version:** Windows 10
**Idea Version:** 2020.1
**Plugin Version:** 2.0.2

**Comment by Yuyang105** [comment]
@SeanCai 看一下哈

**Comment by mr3** [comment]
https://github.com/alibaba/p3c/issues/672#issuecomment-651574526

**Comment by LuffyGao** [comment]
最新版本 2.1.0 更新最新版本
