### ISSUE TITLE
如何修改 所有的类都必须添加创建者信息的模版

### ISSUE THREAD

**Issue by lyai007** [alibaba/p3c#707]
## 规约原文
类名没有增加 @author信息会有提示"所有的类都必须添加创建者信息"
![image](https://user-images.githubusercontent.com/4646685/83704798-b81bb800-a645-11ea-87e2-669c810290c9.png)
## 问题描述
![image](https://user-images.githubusercontent.com/4646685/83704816-c79b0100-a645-11ea-87c9-888e0e478b7d.png)
类名没有增加 @ahthor信息会有提示"所有的类都必须添加创建者信息",点fix 后 会自动 增加@author信息,但是我想自定义author的模版
## 修改建议
我想增加日期和描述,我看了官方的文档中有说明,可以通过修改模版来解决,但是我在
File->Setting->Editor->FIle and Code Templates->File header 中,修改了模版但是无没有效果

**Comment by Yuyang105** [comment]
是希望使用IDEA自动修复时，采用自定义模板吗？具体希望支持什么样的写法？

**Comment by Destiny-HLP** [comment]
是希望使用IDEA自动修复时，采用自定义模板吗？具体希望支持什么样的写法？
/**
  * @description ${description}
  * @author Liping Huo
  * @date ${YEAR}-${MONTH}-${DAY} ${HOUR}:${MINUTE}
  */
