### ISSUE TITLE
如何在sonarqube:7.8或8.3中使用P3C

### ISSUE THREAD

**Issue by kervin521** [alibaba/p3c#709]

**Comment by Yuyang105** [comment]
参考这个依赖版本，解决方法： 要么把p3c 依赖的pmd升级掉， 要么用老一点的sonar版本。

**Comment by Yuyang105** [comment]
https://github.com/jensgerdes/sonar-pmd

参考这个依赖版本，解决方法： 
1. 升级p3c依赖的pmd版本，但是会引入一些兼容问题，我们短期内无计划升级，可以自行升级。2. 可以使用老版本的sonar

**Comment by kervin521** [comment]
这个里面没有p3c

**Comment by slin1972** [comment]
对 这个要自己加进去，请问要怎么加呢
