### ISSUE TITLE
pdf手册（1.3.0）排版有很多问题，尤其是代码部分

### ISSUE THREAD

**Issue by XIJINIAN** [alibaba/p3c#71]
行尾风格的“}”没有与对应的代码对齐，缩进的四个空格显示不准确等。我觉得既然是“规范”，应该更精益求精些。

**Comment by yangguanbao** [comment]
除了右}对齐问题，其它问题，欢迎再贴出来。

**Comment by XIJINIAN** [comment]
太多啦，随意翻一下，譬如第10页第7点中的反例，if中的"f"与上行哪个字符都不对齐：
![](https://ws2.sinaimg.cn/large/006tNc79ly1fklj6ev66fj30cb05w749.jpg)

14页最下面的代码段缩进问题多多：
![](https://ws2.sinaimg.cn/large/006tNc79ly1fklj5bq0omj30ce07hq2x.jpg)

等等等

**Comment by 1994** [comment]
为什么不考虑用markdown编写这份文档呢 @yangguanbao

**Comment by xuantan** [comment]
@XIJINIAN 我们后续会改为Github在线维护，并做修正

**Comment by yangguanbao** [comment]
仔细查看了一下，发现WORD转PDF时候出现的问题，后续使用MD文件直接push在github上。感谢你对《阿里巴巴Java开发手册》的支持。
