### ISSUE TITLE
Windows  idea2019.3.4  格式化 注释会合并到一行

### ISSUE THREAD

**Issue by ChengJiangT** [alibaba/p3c#714]
/**
* Description: TODO
* @author: aaaa
* Date: 2020/6/23 17:27
* Param: []
* Return: java.lang.String
/
格式化之后就这样了
/*
* Description: TODO
*
* @author: aaaa Date: 2020/6/23 17:27 Param: [] Return: java.lang.String
*/

**Comment by Yuyang105** [comment]
@ChengJiangT 我们代码库里的是Eclipse style，导入idea建议装一个转换插件 Eclipse code formatter
