### ISSUE TITLE
打包idea-plugin一直报错 Could not download ideaIC-145.258.11.zip

### ISSUE THREAD

**Issue by Tellsea** [alibaba/p3c#716]
## 打包idea-plugin时，一直报错

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':p3c-common'.
> Could not resolve all files for configuration ':p3c-common:detachedConfiguration3'.
   > Could not download ideaIC-145.258.11.zip (com.jetbrains.intellij.idea:ideaIC:145.258.11)
      > Could not get resource 'https://cache-redirector.jetbrains.com/www.jetbrains.com/intellij-repository/releases/com/jetbrains/intellij/idea/ideaIC/145.258.11
/ideaIC-145.258.11.zip'.
         > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.5/userguide/command_line_interface.html#sec:command_line_warnings

请问这个怎么解决？最新版

**Comment by Yuyang105** [comment]
@Tellsea 麻烦确定下是不是网络问题
