### ISSUE TITLE
阿里巴巴Java开发手册（泰山版）一个排版错误的问题

### ISSUE THREAD

**Issue by wanghaocun** [alibaba/p3c#717]
**如题见下图**
> 第51页  《附 2：专有名词解释》  `CAS`

![p3c](https://user-images.githubusercontent.com/25606300/86207438-2306d300-bba1-11ea-8b35-a4c03772b7d8.png)

**Comment by yangguanbao** [comment]
8月3日会发布嵩山版，修复这个错误。
