### ISSUE TITLE
类名驼峰检查中对专有名词缩写检查问题

### ISSUE THREAD

**Issue by looly** [alibaba/p3c#72]
我有个类叫做LRUCache，LRU专有名词，被检查不符合驼峰规范。此处理应正确

**Comment by riclava** [comment]
是有这个问题，比如HTTP，TCP前缀等

**Comment by kentkwan** [comment]
使用redis api的时候 HGetCommand HSetCommand 也被检查为不符合驼峰规范 我也很无语

**Comment by qiujiayu** [comment]
CORS 也被检查为不符合驼峰规范

**Comment by Ryoui** [comment]
这个功能确实应该添加

**Comment by xuantan** [comment]
建议大家改成驼峰式，看多了就习惯了 ：）

**Comment by piumnl** [comment]
求同存异，是否可以添加一个自定义专有名词的过滤配置？
