### ISSUE TITLE
(七) 并发处理 第2条 中的 Thread 构造方法

### ISSUE THREAD

**Issue by hc24** [alibaba/p3c#721]
**Describe the bug**
java.lang.Thread 中不存在5个参数的构造方法: 

`Thread thread = new Thread(null, task, name, 0, false);`

![image](https://user-images.githubusercontent.com/9858863/86749799-19351200-c070-11ea-9d48-1b06035fd4e5.png)

**Comment by Yuyang105** [comment]
@yangguanbao 看一下哈

**Comment by LuffyGao** [comment]
jdk 13以上有五个参数的方法

**Comment by yangguanbao** [comment]
* @since 9
     */
    public Thread(ThreadGroup group, Runnable target, String name,
                  long stackSize, boolean inheritThreadLocals) {
        this(group, target, name, stackSize, null, inheritThreadLocals);
    }
