### ISSUE TITLE
MAC新系统下 idea开启了这个插件 CPU占用400%

### ISSUE THREAD

**Issue by zsc2010520** [alibaba/p3c#722]
关闭插件后CPU占用正常
开启插件后打字的时候CPU占用高，idea卡顿
MacBook Pro 13
系统 10.15.5 (19F101)

**Comment by Yuyang105** [comment]
@zsc2010520 本月将发布新版，麻烦再观察下是否有改善。

**Comment by LuffyGao** [comment]
新版已修复。
