### ISSUE TITLE
eclipse的使用教程

### ISSUE THREAD

**Issue by kkomge** [alibaba/p3c#73]
eclipse安装阿里巴巴Java开发规约插件Alibaba Java Coding Guidelines
https://www.yuanjilu.xyz/article/369.html

**Comment by javait90** [comment]
扫描之后一对major问题， 打开源码， 一堆 下划的蓝色波浪线 ， 怎么禁用扫描的效果 ? 我暂时不想改代码，都是加注释.

**Comment by SeanCai** [comment]
https://github.com/alibaba/p3c/blob/master/eclipse-plugin/README_cn.md
