### ISSUE TITLE
idea-plugin:PmdGlobalInspectionContextImpl这个类中com.intellij.openapi.project.ProjectUtilCore哪里有

### ISSUE THREAD

**Issue by zhenjia001** [alibaba/p3c#730]
idea-plugin:PmdGlobalInspectionContextImpl这个类中com.intellij.openapi.project.ProjectUtilCore哪里有？
我直接引用了自己idea 2019.2.3版本的openapi.jar仍然报错
Error:(26, 37) Kotlin: Unresolved reference: ProjectUtilCore
有哪位大侠遇到过，或者帮忙指导一下这个com.intellij.openapi.project.ProjectUtilCore在哪里

**Comment by LuffyGao** [comment]
@SeanCai

**Comment by XenoAmess** [comment]
@zhenjia001 应该是在很古老的版本的idea库中有，现代版本应该已经没了吧？
因为他们一直基于145构建，所以。。。
不过上个更新他们把使用的idea版本提了一下，这个应该已经修掉了吧？
你看看他他们最新的master，如果已经替换掉了就close一下。

**Comment by zhenjia001** [comment]
@XenoAmess 感谢，我在老版本里找到放上，现在能打包了
稍后我用新版本试一下

**Comment by XenoAmess** [comment]
> @XenoAmess 感谢，我在老版本里找到放上，现在能打包了
> 稍后我用新版本试一下

@zhenjia001 是的 那边 印象里 是几个static函数 copy过来就行
不过我确实不明白为何之前的写法到了新版本竟然不会炸。。。（或许会？）
总之jetbrains其实 他们自己的库 很多东西改来改去 想要支持很多版本的话 真的很难
