### ISSUE TITLE
maven校验插件

### ISSUE THREAD

**Issue by penglingfeng1995** [alibaba/p3c#732]
提供对格式和规范进行校验的maven插件，绑定进maven的生命周期，不通过校验则无法编译，绑定进cicd流程，强制团队遵守规范

**Comment by LuffyGao** [comment]
![image](https://user-images.githubusercontent.com/6856883/90616898-9a232400-e240-11ea-9ae9-faa529845bbf.png)

可以看下我们的pom https://github.com/alibaba/p3c/blob/master/p3c-pmd/pom.xml

**Comment by penglingfeng1995** [comment]
> ![image](https://user-images.githubusercontent.com/6856883/90616898-9a232400-e240-11ea-9ae9-faa529845bbf.png)
> 
> 可以看下我们的pom https://github.com/alibaba/p3c/blob/master/p3c-pmd/pom.xml

我试了下这个插件， 执行完后日志会打印错误，target中也会有pmd.xml查看错误，但是只会校验p3c的规范，不会校验代码格式 @LuffyGao

**Comment by smiler158** [comment]
目前我们没有强制校验代码风格，您这边可以看下mvn checkstype插件能不能满足你的需求。 参考 https://maven.apache.org/plugins/maven-checkstyle-plugin/usage.html
