### ISSUE TITLE
求助, 上传插件到JetBrains仓库的一些问题

### ISSUE THREAD

**Issue by godfather1103** [alibaba/p3c#734]
各位大佬，小弟写了一个插件想上传到JetBrains的仓库中，JetBrains发邮件给我说，要我提供插件的英文描述信息，以及正确的开发商(vendor)信息，我这边已经提供了相关英文说明，但是JetBrains还是回复同样的内容给我。请问谁清楚该如何处理吗？谢谢了
![0b850ffd058e32db458b85e30449fb8](https://user-images.githubusercontent.com/11797964/89364230-a5386900-d704-11ea-8d47-8841d53ca60f.png)
![3b4800c486856c4c1cf7e96fb68d135](https://user-images.githubusercontent.com/11797964/89364234-a79ac300-d704-11ea-9298-1951f920ffa3.png)

**Comment by godfather1103** [comment]
插件地址如下：https://plugins.jetbrains.com/plugin/14804-git-commit-template-check/

**Comment by godfather1103** [comment]
Albert Ishmukhametov (Plugin Repository)
Aug 4, 2020, 8:10 PM GMT+2

您好,

麻烦请提供插件的英文描述信息，以及正确的开发商(vendor)信息。您可以通过 plugins.xml 来进行更新(https://www.jetbrains.org/intellij/sdk/docs/basics/plugin_structure/plugin_configuration_file.html)，并且重新将档案上传到插件库( plugins repository)。
在收到更新的信息后，我们将批准发布插件并将其公开给使用者。

谢谢您提交插件！我们非常期待将其批准并公开发布到插件库中。

Best regards,
Albert Ishmukhametov
JetBrains

JetBrains (Plugin Repository)
Aug 3, 2020, 4:30 AM GMT+2

Dear Jack Chu,

Thank you for submitting a 1.7.3 version of Git Commit Template Check plugin, it has been successfully uploaded to the plugins repository and now pending JetBrains' review and approval in order to be publicly available.

All new updates are normally reviewed within two business days. You will receive a notification as soon as status of this review changes.

In the meantime, you can always access your update via direct link: https://plugins.jetbrains.com/plugin/14804-git-commit-template-check/versions/stable/93623, but please note that it won't be publicly available (e.g. in search results and in the product) until approved by JetBrains.

If you would like to provide more information to us, feel free to add a comment by replying to this email. Please do not change the e-mail subject or the recipient.

Best regards,
JetBrains Marketplace Team

**Comment by godfather1103** [comment]
上面是JetBrains回复的邮件内容

**Comment by XenoAmess** [comment]
你代码呢？

**Comment by godfather1103** [comment]
原来的插件删了，把中英文说明的顺序换了一下就审核通过了，所以我就关了
https://plugins.jetbrains.com/plugin/14822-git-commit-template-check

**Comment by godfather1103** [comment]
插件源码在这里https://github.com/godfather1103/commit-template-check-plugin
