### ISSUE TITLE
p3c如何集成到Sonarqube

### ISSUE THREAD

**Issue by Michael-Guo** [alibaba/p3c#736]
## 修改建议
请问各位，p3c最新的规则如何集成到sonar中，对sonar版本有何要求，大家分享下自己的最佳实践经验啦

**Comment by mll120110** [comment]
可以参考：
https://my.oschina.net/u/4327212/blog/3209285

**Comment by LuffyGao** [comment]
@mll120110 感谢回答。 @Michael-Guo 可以参考这个来解决

**Comment by slin1972** [comment]
这个版本也太老了吧，有没有新版本的
