### ISSUE TITLE
README.md 里面的“中文版: 阿里巴巴Java开发手册“打开页面404

### ISSUE THREAD

**Issue by xiaozhiliaoo** [alibaba/p3c#737]
**Describe the bug**
README.md 里面的“中文版: 阿里巴巴Java开发手册“打开url是“阿里巴巴Java开发手册（泰山版）.pdf“，实际仓库的pdf是“Java开发手册（嵩山版）.pdf“

**Comment by yangguanbao** [comment]
已经修复，感谢关注Java开发手册
