### ISSUE TITLE
对于某些规范有不同意见怎么处理

### ISSUE THREAD

**Issue by EasonDongH** [alibaba/p3c#738]
如题，现团队期望通过规范插件来规约提交的代码规范，但对于某些规范我们可能有自己的看法。所以希望可以指定某些文件保持自己的规范，并且希望插件扫描时忽略这些文件。不知道现有插件是否能做到？

**Comment by yangguanbao** [comment]
1）你们可以fork出来
2）现在打算去掉supress warning。
3）忽略文件，可以我们就提供这个功能。

**Comment by XenoAmess** [comment]
@EasonDongH 那你可以 考虑试试这个 https://github.com/XenoAmess/p3c
