### ISSUE TITLE
《嵩山版》过时语句“前者现在时表示主动式创建，后者过去分词表示被动式更新。”

### ISSUE THREAD

**Issue by Licheng-Xu** [alibaba/p3c#739]
## 规约原文
五、MySQL 数据库 / (一) 建表规约 / 第9条

> create_time, update_time 的类型均为 datetime 类型，前者现在时表示主动式创建，后者过去分词表示被动式更新。

## 问题描述
这里之前的版本要求添加的字段是 gmt_create, gmt_modified，有现在时和过去分词之分，新版里并无时态问题。

## 修改建议
删除 “前者现在时表示主动式创建，后者过去分词表示被动式更新。”

**Comment by yangguanbao** [comment]
在下一个版本恒山版中修复，感谢你的关注。
