### ISSUE TITLE
please upgrade pmd version to latest

### ISSUE THREAD

**Issue by liaoguode** [alibaba/p3c#742]
**Is your feature request related to a problem? Please describe.**
please upgrade pmd version to latest

**Describe the solution you'd like**
the pmd latest version is 6.26.0, but p3c use 6.15.0.please upgrade pmd version to use new feature

**Comment by LuffyGao** [comment]
@imu2008

**Comment by imu2008** [comment]
@liaoguode OK，we will assess the necessity for an upgrade and  do it as soon as possible，tks

**Comment by XenoAmess** [comment]
@liaoguode 
That is not as easy as click an update button...
Some rules have changed in new version of pmd.
Just, be careful.
If need any help I'm glad to share.

**Comment by imu2008** [comment]
@XenoAmess  it is wonderful for you can commit  a MR about this feature

**Comment by XenoAmess** [comment]
@imu2008 I created a pr several months ago...
well, I admit I change too many things and it is a little difficult to discover what are you needed...
https://github.com/alibaba/p3c/pull/660

**Comment by liaoguode** [comment]
@imu2008 thank you, I think this is a good idea.

**Comment by XenoAmess** [comment]
> @imu2008 thank you, I think this is a good idea.

yes, it is.
upgrading to 6.22 can bring new features about java 14 new grammar (for example, switch).
what I wanna say is, it is not easy, and will take tons of time to do so.
(and consider about in this repo they do never use any deprecated functions and the update will bring many many deprecated functions...)

**Comment by liaoguode** [comment]
> @liaoguode
> 
> > I think this is a good idea.
> 
> yes, it is.
> upgrading to 6.22 can bring new features about java 14 new grammar (for example, switch).
> it is really useful for some people.
> 
> what I wanna say is, it is not easy, and will take tons of time to do so.
> (and consider about in this repo they do never use any deprecated functions, and the update will bring many many deprecated functions...)

@XenoAmess 
yes ,it is.
I have find 300+ deprecated functions when I upgrade to 6.26.0, upgrade to latest version will spend a lot of time, maybe need  large number of people to work it.
we will use p3c to be our static java code analysis, we will work it, want p3c is better.

**Comment by XenoAmess** [comment]
> > @liaoguode
> > > I think this is a good idea.
> > 
> > 
> > yes, it is.
> > upgrading to 6.22 can bring new features about java 14 new grammar (for example, switch).
> > it is really useful for some people.
> > what I wanna say is, it is not easy, and will take tons of time to do so.
> > (and consider about in this repo they do never use any deprecated functions, and the update will bring many many deprecated functions...)
> 
> @XenoAmess
> yes ,it is.
> I have find 300+ deprecated functions when I upgrade to 6.26.0, upgrade to latest version will spend a lot of time, maybe need large number of people to work it.
> we will use p3c to be our static java code analysis, we will work it, want p3c is better.

(sigh) In my tpm at https://github.com/XenoAmess/p3c I can only make sure it can works on 6.22.0
But for removing all deprecated functions...
Forgive me, that is toooo much work to do, I just give up.

**Comment by liaoguode** [comment]
@XenoAmess I find upgrade pmd version can not fix the all deprecated functions. the 6.26.0 only have less  replace function for deprecated functions. The pmd version 7.0.0 will give the most replace function, maybe upgrade to 7.0.0 is better.

**Comment by XenoAmess** [comment]
> @XenoAmess I find upgrade pmd version can not fix the all deprecated functions. the 6.26.0 only have less replace function for deprecated functions. The pmd version 7.0.0 will give the most replace function, maybe upgrade to 7.0.0 is better.

Maybe it is better to deprecate the Rule that forbid us using all deprecated functions, just like what I did :)
