### ISSUE TITLE
The results of each scan are inconsistent,Right-click scanning will miss some detections

### ISSUE THREAD

**Issue by Anteoy** [alibaba/p3c#744]
**Describe the bug**
By the same file to check, The results of each scan are inconsistent,Right-click scanning will miss some detections.

**To Reproduce**
The java file to check:
```
package com.allocmem.check;

import lombok.Data;

import java.io.Serializable;

@Data
public class AppDDO implements Serializable {

    private Long id; // bigint(20) NOT NULL
    private Integer xiId; // int(11) DEFAULT NULL
    private String xiName; // varchar(100) CHARACTER SET utf8
    private Double a; // double DEFAULT NULL COMMENT
    private Double l; // double DEFAULT NULL COMMENT
    private Double o; // double DEFAULT NULL COMMENT
    private Double ox; // double DEFAULT NULL COMMENT
    private Integer d; // int(11) DEFAULT NULL COMMENT
    private Integer or; // int(11) DEFAULT NULL COMMENT
    private Integer dd; // int(11) DEFAULT NULL COMMENT

}
```
Then, Click the right mouse button to test 3 times or more.

**Expected behavior**
The result should be consistent.

**Screenshots**
![image](https://user-images.githubusercontent.com/17495446/90486681-eea89f80-e16b-11ea-986d-a3fe6d0f9d32.png)
![image](https://user-images.githubusercontent.com/17495446/90486706-f5cfad80-e16b-11ea-91a3-f80589986e73.png)
The result is inconsistent.

**Desktop (please complete the following information):**
 - OS:  macos 10.15.4
 - idea version: 2020.1.4 and 2019.3
 - plugin version: 2.0.2

Any ideas?

**Comment by LuffyGao** [comment]
本周发布的新版本将解决这个问题。

**Comment by XenoAmess** [comment]
@LuffyGao 
> 本周发布的新版本将解决这个问题。

Many thanks!
