### ISSUE TITLE
以形容词作为接口名称的例子不合适

### ISSUE THREAD

**Issue by kirinboy** [alibaba/p3c#745]
## 规约原文
接口和实现类的命名有两套规则:
1)【强制】对于 Service 和 DAO 类，基于 SOA 的理念，暴露出来的服务一定是接口，内部的实现类用
Impl 的后缀与接口区别。
正例:`CacheServiceImpl` 实现 `CacheService` 接口。
2)【推荐】如果是形容能力的接口名称，取对应的形容词为接口名(通常是–able 的形容词)。 
**_正例:`AbstractTranslator` 实现 `Translatable` 接口。_**
## 问题描述
`AbstractTranslator` 实现 `Translatable` 接口的例子不合适。
`Translatable`是指可被翻译的类，而`Translator`是指进行翻译工作的类，两者不是一码事。
类比：`String`类实现了`Serializable`，但`String`不是一个`Serializer`。
## 修改建议
正例: 接口名称 `Serializable`、`Comparable`、`Cloneable`、`Translatable`等。

**Comment by yangguanbao** [comment]
我觉得没啥问题。
