### ISSUE TITLE
任何货币金额，均以最小货币单位且整型类型来进行存储。 金额为什么是整型而不是BigDecimal？

### ISSUE THREAD

**Issue by GZHua** [alibaba/p3c#748]
## 规约原文
嵩山版
OOP
8.【强制】任何货币金额，均以最小货币单位且整型类型来进行存储
## 问题描述
 货币金额存储为什么是整型而不是BigDecimal类型

**Comment by XenoAmess** [comment]
@GZHua 因为精度问题。
BigDecimal精度设不好会出事情的。
如果钱实在多，可以考虑上BigInteger

**Comment by gclsoft** [comment]
给前端的要传分还是元?
