### ISSUE TITLE
关于局部变量使用基本数据类型问题

### ISSUE THREAD

**Issue by a601942905git** [alibaba/p3c#749]
## 规约原文
13.1 【强制】所有的 POJO 类属性必须使用包装数据类型。
13.3【推荐】所有的局部变量使用基本数据类型。
## 问题描述
POJO中属性强制使用包装数据类型，这个没有疑问。假如有一个Order对象，里面有一个private Long orderId这样一个属性，那么在业务方法中需要使用到orderId,示例如下：

示例1：
```java
public void xxx(Long orderId){

}
```

示例2：
```java
public void xxx(long orderId){

}
```

示例3：
```java
public void xxx(Order order){
    Long orderId = order.getOrderId;
}
```

示例4：
```java
public void xxx(Order order){
    long orderId = order.getOrderId;
}
```
对于示例2、示例4如果使用基本数据类型，就会存在拆箱的问题，需要判断是否为null，如果直接用包装类型的话就不存在NPE问题。是不是说针对包装类型的接收，可以直接定义包装类型；针对方法中新定义的变量使用基本数据类型？

**Comment by XenoAmess** [comment]
个人观点。
有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。

**Comment by a601942905git** [comment]
> 个人观点。
> 有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。

如果是示例1的话就不需要装箱，但是就不符合手册上局部变量使用基本数据类型

**Comment by XenoAmess** [comment]
> > 个人观点。
> > 有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。
> 
> 如果是示例1的话就不需要装箱，但是就不符合手册上局部变量使用基本数据类型

java里有个东西叫自动装箱。

**Comment by a601942905git** [comment]
> > > 个人观点。
> > > 有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。
> > 
> > 
> > 如果是示例1的话就不需要装箱，但是就不符合手册上局部变量使用基本数据类型
> 
> java里有个东西叫自动装箱。

没搞懂你术术说的，示例1都是包装类型，为啥会自动装箱？
```java
int a = 1;
Integer b = a; // 这里才会自动装箱
```

**Comment by XenoAmess** [comment]
> > > > 个人观点。
> > > > 有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。
> > > 
> > > 
> > > 如果是示例1的话就不需要装箱，但是就不符合手册上局部变量使用基本数据类型
> > 
> > 
> > java里有个东西叫自动装箱。
> 
> 没搞懂你说的，示例1都是包装类型，为啥会自动装箱？
> 
> ```java
> int a = 1;
> Integer b = a; // 这里才会自动装箱
> ```

举个例子。
```
public class IntegerPojo {
    private Integer value;

    public Integer getValue() {
        return value;
    }

    public void setValue(Integer value) {
        this.value = value;
    }
}
```

这个是pojo。
在外部，用如下类操作该pojo的时候。

```
public class IntegerPojoHandler {
    public static Integer DEFAULT = 0;
    public static void setValue(IntegerPojo integerPojo, int newIntegerValue) {
         integerPojo.setValue(newIntegerValue);
    }
    public static void multiply(IntegerPojo integerPojo, int multiplyTo) {
        final Integer integerValue = integerPojo.getValue();
        if (integerValue == null) {
            integerPojo.setValue(DEFAULT * multiplyTo);
        } else {
            integerPojo.setValue(integerValue * multiplyTo);
        }
    }
}
```
注意 13.3【推荐】所有的局部变量使用基本数据类型。
【推荐】而不是【强制】 是因为有些逻辑 必须用包装类才能处理，比如上述的multiply(IntegerPojo integerPojo, int multiplyTo)
但是 如果你确认 不需要上包装类就能处理，那么就不要上包装类，因为反正要装箱的话不如扔去pojo装，比如上述的setValue(IntegerPojo integerPojo, int newIntegerValue)
当然如果你全套逻辑都是用包装类去做 至少 给你IntegerPojoHandler的对接 也都是包装类的话 完全可以无视13.3，毕竟是推荐不是强制。
嗯我是这么理解的，对不对我不知道。

**Comment by a601942905git** [comment]
> > > > > 个人观点。
> > > > > 有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。
> > > > 
> > > > 
> > > > 如果是示例1的话就不需要装箱，但是就不符合手册上局部变量使用基本数据类型
> > > 
> > > 
> > > java里有个东西叫自动装箱。
> > 
> > 
> > 没搞懂你说的，示例1都是包装类型，为啥会自动装箱？
> > ```java
> > int a = 1;
> > Integer b = a; // 这里才会自动装箱
> > ```
> 
> 举个例子。
> 
> ```
> public class IntegerPojo {
>     private Integer value;
> 
>     public Integer getValue() {
>         return value;
>     }
> 
>     public void setValue(Integer value) {
>         this.value = value;
>     }
> }
> ```
> 
> 这个是pojo。
> 在外部，用如下类操作该pojo的时候。
> 
> ```
> public class IntegerPojoHandler {
>     public static Integer DEFAULT = 0;
>     public static void setValue(IntegerPojo integerPojo, int newIntegerValue) {
>          integerPojo.setValue(newIntegerValue);
>     }
>     public static void multiply(IntegerPojo integerPojo, int multiplyTo) {
>         final Integer integerValue = integerPojo.getValue();
>         if (integerValue == null) {
>             integerPojo.setValue(DEFAULT * multiplyTo);
>         } else {
>             integerPojo.setValue(integerValue * multiplyTo);
>         }
>     }
> }
> ```
> 
> 注意 13.3【推荐】所有的局部变量使用基本数据类型。
> 【推荐】而不是【强制】 是因为有些逻辑 必须用包装类才能处理，比如上述的multiply(IntegerPojo integerPojo, int multiplyTo)
> 但是 如果你确认 不需要上包装类就能处理，那么就不要上包装类，因为反正要装箱的话不如扔去pojo装，比如上述的setValue(IntegerPojo integerPojo, int newIntegerValue)
> 当然如果你全套逻辑都是用包装类去做 至少 给你IntegerPojoHandler的对接 也都是包装类的话 完全可以无视13.3，毕竟是推荐不是强制。
> 嗯我是这么理解的，对不对我不知道。

**Comment by a601942905git** [comment]
> > > > > > 个人观点。
> > > > > > 有示例1了就不需要示例2，因为反正你得装箱，在别的函数装还是专门找个函数装没区别。
> > > > > 
> > > > > 
> > > > > 如果是示例1的话就不需要装箱，但是就不符合手册上局部变量使用基本数据类型
> > > > 
> > > > 
> > > > java里有个东西叫自动装箱。
> > > 
> > > 
> > > 没搞懂你说的，示例1都是包装类型，为啥会自动装箱？
> > > ```java
> > > int a = 1;
> > > Integer b = a; // 这里才会自动装箱
> > > ```
> > 
> > 
> > 举个例子。
> > ```
> > public class IntegerPojo {
> >     private Integer value;
> > 
> >     public Integer getValue() {
> >         return value;
> >     }
> > 
> >     public void setValue(Integer value) {
> >         this.value = value;
> >     }
> > }
> > ```
> > 
> > 
> > 这个是pojo。
> > 在外部，用如下类操作该pojo的时候。
> > ```
> > public class IntegerPojoHandler {
> >     public static Integer DEFAULT = 0;
> >     public static void setValue(IntegerPojo integerPojo, int newIntegerValue) {
> >          integerPojo.setValue(newIntegerValue);
> >     }
> >     public static void multiply(IntegerPojo integerPojo, int multiplyTo) {
> >         final Integer integerValue = integerPojo.getValue();
> >         if (integerValue == null) {
> >             integerPojo.setValue(DEFAULT * multiplyTo);
> >         } else {
> >             integerPojo.setValue(integerValue * multiplyTo);
> >         }
> >     }
> > }
> > ```
> > 
> > 
> > 注意 13.3【推荐】所有的局部变量使用基本数据类型。
> > 【推荐】而不是【强制】 是因为有些逻辑 必须用包装类才能处理，比如上述的multiply(IntegerPojo integerPojo, int multiplyTo)
> > 但是 如果你确认 不需要上包装类就能处理，那么就不要上包装类，因为反正要装箱的话不如扔去pojo装，比如上述的setValue(IntegerPojo integerPojo, int newIntegerValue)
> > 当然如果你全套逻辑都是用包装类去做 至少 给你IntegerPojoHandler的对接 也都是包装类的话 完全可以无视13.3，毕竟是推荐不是强制。
> > 嗯我是这么理解的，对不对我不知道。

应该是这个样子，毕竟是【推荐】而不是【强制】
