### ISSUE TITLE
if语句里面只有一行代码，也必须要加大括号？

### ISSUE THREAD

**Issue by git-xuhao** [alibaba/p3c#75]
这个是提示：

在if/else/for/while/do语句中必须使用大括号，即使只有一行代码，避免使用下面的形式：if (condition) statements; 
            
    if(flag) {
        System.out.println("hello world");
    }

只有一句代码的时候不加大括号看起来简洁一些啊！

**Comment by youngxhui** [comment]
以后更改的时候方便

**Comment by Anddd7** [comment]
写多了过后可能会看串行 (:逃

**Comment by xuantan** [comment]
@git-xuhao 必须加。
