### ISSUE TITLE
扩展XML功能

### ISSUE THREAD

**Issue by guxiaonian** [alibaba/p3c#750]
我想拓展Java层代码的基础上，拓展XML清单文件的相关规则。基于PMD好像实现不了，是否是要在p3c内自己集成Android Lint工具？

**Comment by XenoAmess** [comment]
@guxiaonian 
详细说说你在用pmd实现的途中遇到了什么困难。
https://github.com/pmd/pmd/tree/master/pmd-xml

**Comment by xuantan** [comment]
基于PMD扫描引擎可以扩展针对XML文件的扫描规则。
