### ISSUE TITLE
《Java开发手册（嵩山版）》5.1.3 表名不使用复数名词 有疑问

### ISSUE THREAD

**Issue by hellozjf** [alibaba/p3c#752]
## 规约原文

【强制】 表名不使用复数名词。
说明：表名应该仅仅表示表里面的实体内容，不应该表示实体数量，对应于 DO 类名也是单数形式，符合
表达习惯。

## 问题描述

我看到Spring Security的源码里面有很多表都是使用复数形式，例如用户表是users、权限表authorities……（在`org.springframework.security.provisioning.JdbcUserDetailsManager`可以看到），记住我持久化令牌表persistent_logins（在`org.springframework.security.web.authentication.rememberme.JdbcTokenRepositoryImpl`可以看到）

所以感觉这条规约并不需要强制，可以修改为推荐

## 修改建议

规约5.1.3从强制更改为推荐

**Comment by nuhhh** [comment]
Hello Jingfeng Zhou,

I am Nuh. I have worked as a 3DEXPERIENCE consultant for 2 years. I have seen your code and wanted to ask you some questions about "emxCommonDownload_mxJPO.java" and "emxCommonDownloadBase_mxJPO.java" . I have a huge data and wanted to download them by seperating their types with the last their revisions. I want to learn what is the syntax that I could in MQL?

/**** Sample Scenario Start :
/*exec prog DeleteObjectsByOwner -type <TYPE> -user <USERNAME> [-name <NAME>] [-state <STATE>] 
/*                                           [- vault <vault>] [-checkMode <boolean>]
/*
/* I am going to delete a data from MQL ;
/* There is a jpo which name is Delete_Objects.jpo that makes deletion by MQL

MQL>insert program E:\DeleteObjects_mxJPO.java
MQL>exec program DeleteObjects -user admin_platform -type CATPart -checkMode true; /* Delete Catparts which created by admin_platform */
MQL>exec program DeleteObjects -user nuh -type CatPart -checkMode true; /*Delete CatPtoducts which created by nuh */
 

/* That's all.
/*      -type = Business type of objects to delete.(e.g. 'Part')
/*      -user = UserName of owner of objects.(e.g. 'Test Everything')
/*      -name = [Optional] Name of object to search.(e.g. 'ABC*')
/*              Defaults to '*'.
/*     -state = [Optional] State of object to search.(e.g. 'In Work')
/*              A single state excepted. Does not except comma delimited list.
/*     -vault = [Optional] Vault where objects are stored.(e.g. 'eService Production')
/*              Defaults to 'eService Production'.
/* -checkMode = [Optional] Defaults to 'false'.
/*              If set to true, objects will not be deleted.
/*              Instead, objects to be deleted are written to log file for verification.
/* -h or -help = Print usage

/**** Sample Scenario End

Thus, I wanted to make real a scenario which Download the objects not delete. For example to download all Catparts with last revisions as CatParts or CatProducts with last revisions as CatProducts (like from Web Interface to click download button) in the 3DEXPERIENCE . Does this java class make it? What is the syntax of MQL for this (exec prog emxCommonDownloadBase ...etc....)?

Thank you for your understanding and collaboration,

Thanks in advance,

Kind Regards.

**Comment by yangguanbao** [comment]
【强制】 表名不使用复数名词。
习惯了就好。
