### ISSUE TITLE
请教一下：阿里内部java类型转换圆括号右边外侧要加空格还是没有空格？

### ISSUE THREAD

**Issue by qxo** [alibaba/p3c#754]
https://github.com/alibaba/p3c/blob/2261fddea9f78a7e960b34450b7004e2483067dc/p3c-formatter/eclipse-codestyle.xml#L326

这个codestye表明java类型转换圆括号右边外侧不能加空格的
但[从开源出来的项目](https://github.com/search?q=org%3Aalibaba+filename%3Acheckstyle.xml+WhitespaceAfter&type=Code)看，checkstyle.xml定义却是加空格的？两都以哪个为准?

https://github.com/alibaba/innodb-java-reader/blob/5f5556960fcbeab6b451fe0f17381a317192f1bd/tools/maven/checkstyle.xml#L110

https://github.com/alibaba/nacos/blob/1a22ae4c476dfb09a55d208f879404ee1c330a0a/style/NacosCheckStyle.xml#L151

另外据我所知网上大部分的checkstyle和codestyle采用都是google规则一致规则， 要加一个空格？
此处先择不加空格有特别的用意没？

**Comment by tongluyang** [comment]
个人感觉需要加一个空格
因为在IDEA的默认设置下，cast以及castvar补全出来的代码就是带空格的
去掉空格反而需要额外的操作

**Comment by mll120110** [comment]
我也发现这个问题，使用checkstyle校验会提示，我也同意带上空格。
我想知道怎么避免这个格式化，不然，checkstyle校验与阿里插件格式化不一致，造成麻烦

**Comment by yangguanbao** [comment]
【强制】在进行类型强制转换时，右括号与被强制转换的值之间不需要任何空格隔开。
正例：

long first = 1000000000000L;
int second = (int)first + 2;

**Comment by ysanimals** [comment]
阿里巴巴泰山版开发手册

**Comment by haitaoss** [comment]
> 我也发现这个问题，使用checkstyle校验会提示，我也同意带上空格。 我想知道怎么避免这个格式化，不然，checkstyle校验与阿里插件格式化不一致，造成麻烦

大佬，我也遇到了这个问题，请问你修改好IDEA个格式化了吗

**Comment by Micro-LHX** [comment]
Spaces 下面有一个在类型转换之后,可以格式化强制类型转换后面不要空格
