### ISSUE TITLE
Android studio如何做到检测有问题时不让提交代码库

### ISSUE THREAD

**Issue by vagrant1991** [alibaba/p3c#755]

**Comment by XenoAmess** [comment]
又防不住人家直接走git提交，有什么意义？

**Comment by wertycn** [comment]
将P3C-PMD集成到GIT hook 检查不通过不允许提交到远程仓库

**Comment by XenoAmess** [comment]
> 将P3C-PMD集成到GIT hook 检查不通过不允许提交到远程仓库

啊这。。。未曾设想的道路.jpg
确实 这种检测 真要做的话 只能做在server侧
githook启sonarqube
sonarqube插pmd
pmd插p3c
应该 能做 但是 怪怪的Q_Q

或者 干脆上一套ci，然后把p3c-pmd插在pom里，然后 只有ci pass的时候才让提交？（感觉这个是正道）

**Comment by wertycn** [comment]
> 
> 
> > 将P3C-PMD集成到GIT hook 检查不通过不允许提交到远程仓库
> 
> 啊这。。。未曾设想的道路.jpg
> 确实 这种检测 真要做的话 只能做在server侧
> githook启sonarqube
> sonarqube插pmd
> pmd插p3c
> 应该 能做 但是 怪怪的Q_Q
> 
> 或者 干脆上一套ci，然后把p3c-pmd插在pom里，然后 只有pr的ci pass的时候才让merge？（感觉这个是正道）

目前给团队的新项目检查就是直接在git hook里干的，如果每次提交都触发CI 的话， 是差不多，但很多情况，提交代码的次数是比CI多的，通过CI去拦截， 不规范的代码还是合到了代码库，已经构成既定事实了，再去修补总会有各种原因不愿意改，所以从可控的源头就是远程仓库里不能出现任何不规范的代码

**Comment by AnsuzTrent** [comment]
AS 没这个吗？
![图片](https://user-images.githubusercontent.com/57950736/92920976-cb6cc980-f465-11ea-91f7-6aea7fc1f86f.png)

**Comment by wertycn** [comment]
> 
> 
> AS 没这个吗？
> ![图片](https://user-images.githubusercontent.com/57950736/92920976-cb6cc980-f465-11ea-91f7-6aea7fc1f86f.png)

这个工具是什么？

**Comment by xuantan** [comment]
需要有个单独的客户端工具进行把控，类似研发流程卡点问题不在这个开源工程里讨论了。
