### ISSUE TITLE
在switch的enhance版本中

### ISSUE THREAD

**Issue by LoveYou3000** [alibaba/p3c#757]
**Describe the bug**
在switch的enhance版本中,无法检测到default块

**To Reproduce**
1. 编写switch的enhance版本,如下
switch (sortType) {
    case 0-> {
        ...
    }
    case 1-> {
        ...
    }
    default -> {
        ...
    }
}
2. 编码规约扫描
3. 提示switch块缺少default语句

**Expected behavior**
扫描通过

**Screenshots**
![image](https://user-images.githubusercontent.com/50392741/92993011-5068e900-f521-11ea-9214-38bcc938c4f8.png)

**Desktop (please complete the following information):**
 - OS: [Windows10]

**Comment by LuffyGao** [comment]
@fw8899

**Comment by liukeshao** [comment]
全部枚举都case的时候 不需要default

**Comment by XenoAmess** [comment]
已于TPM修复，请考虑换用TPM
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/versions/stable/129152
请等待最多2天的jetbrains审核

**Comment by xuantan** [comment]
@fw8899 看下

**Comment by XenoAmess** [comment]
> @fw8899 看下

@xuantan 
没法看下。
如果要修就要升级pmd版本。
如果升级pmd版本，有些东西就会@Deprecated
如果@Deprecated，就会被p3c的**禁止使用Deprecated**规则干掉，不让你编译。
GG

最搞笑的在于，pmd Deprecate某些类，是计划在7.0的时候废掉，现在还没有替代。
hhh

所以我强烈建议你们也跟我一样把禁止使用Deprecated这条垃圾规则给摘了强制吧，这种东西，扔去可选规则就行了

**Comment by fw8899** [comment]
P3C暂不支持Java 11以上语法特性，后续升级Java兼容版本时统一考虑。
