### ISSUE TITLE
为什么ScheduledThreadPool从并发处理-4线程池里面的限制去掉了

### ISSUE THREAD

**Issue by meloLeeAnthony** [alibaba/p3c#759]
## 规约原文
线程池不允许使用Executors去创建，而是通过ThreadPoolExecutor的方式，这样的处理方式让写的同学更加明确线程池的运行规则，规避资源耗尽的风险。 说明：Executors返回的线程池对象的弊端如下： 1） FixedThreadPool和SingleThreadPool： 允许的请求队列长度为Integer.MAX_VALUE，可能会堆积大量的请求，从而导致OOM。 2） CachedThreadPool： 允许的创建线程数量为Integer.MAX_VALUE，可能会创建大量的线程，从而导致OOM

## 问题描述
为什么ScheduledThreadPool从限制中去掉了，看源码最大线程数还是Integer.MAX_VALUE，依然有可能OOM

**Comment by yangguanbao** [comment]
没有办法可以更有效地解决，所以去掉这一条。
