### ISSUE TITLE
请问P3C-PMD如何使用？

### ISSUE THREAD

**Issue by tengzhaoyong** [alibaba/p3c#76]
如题，内容中有P3C-PMD，eclipse插件教程，idea插件教程
但P3C-PMD 这个使用方式介绍比较少，请问是如何使用的？

**Comment by SeanCai** [comment]
P3C-PMD 是一个pmd规则实现jar包，可以使用maven或者gradle直接依赖。具体集成方面可参考PMD官方网站

**Comment by michael-ancestor** [comment]
@SeanCai maven集成p3c-pmd后，插件可以检测出的一些错误，而maven方式检测不出来(比如if不写{})
