### ISSUE TITLE
关于异常处理的的编码规约

### ISSUE THREAD

**Issue by kkzfl22** [alibaba/p3c#760]
## Rule content
【参考】对于公司外的 http/api 开放接口必须使用“错误码”；而应用内部推荐异常抛出； 跨应用间 RPC 调用优先考虑使用 Result 方式，封装 isSuccess()方法、“错误码”、“错误简 短信息”。 说明：关于 RPC 方法返回方式使用 Result 方式的理由：
  1）使用抛异常返回方式，调用方如果没有捕获到就会产生运行时错误。  
2）如果不加栈信息，只是 new 自定义异常，加入自己的理解的 error message，对于调用 端解决问题的帮助不会太多。如果加了栈信息，在频繁调用出错的情况下，数据序列化和传输 的性能损耗也是问题。 

## Problem description
应用内部推荐异常抛出，接口的中参数的校验，是属于这个范围，应用内部推荐异常抛出，这样子推荐会被乱用，我发现有同事就是使用此种规则来处理的API层的接口参数校验。在接口参数校验后，不是直接返回错误码，而抛出一个异常。在异常中包含错误码及错误信息。在《effective Java》关于异常我觉得有比较好的推荐。再者接口参数校验正常的功能的代码，不推荐这样子抛出异常。
## Advice
应用内部推荐异常抛出，这个我觉得不应该这样推荐，只有在明确是异常的情况，才使用异常抛出，将异常与错误码分开推荐，我觉得这样子才更合理。这样子的推荐会对开发人员产生一个误导。应用内部不管什么都是抛异常。这是不合理的

**Comment by LuffyGao** [comment]
@yangguanbao

**Comment by Yuyang105** [comment]
你好，感谢支持，下一版本--《黄山版》针对这个情况说明。
