### ISSUE TITLE
priority属性应该紧跟在在description属性的后面

### ISSUE THREAD

**Issue by bonaluo** [alibaba/p3c#763]
## Rule content
ali-concurrent.xml#AvoidCallStaticSimpleDateFormatRule
## Problem description
priority属性应该紧跟在description属性的后面
## Advice
将priority属性移动到description属性的后面而不是example属性的后面

**Comment by LuffyGao** [comment]
@SeanCai

**Comment by SeanCai** [comment]
fixed. thx
