### ISSUE TITLE
关于分层领域模型规约 DTO、BO区别，VO、Query疑惑

### ISSUE THREAD

**Issue by zhangyq233** [alibaba/p3c#767]
## 规约原文
3. 【参考】分层领域模型规约：
 DO（Data Object）：此对象与数据库表结构一一对应，通过 DAO 层向上传输数据源对象。
 DTO（Data Transfer Object）：数据传输对象，Service 或 Manager 向外传输的对象。
 BO（Business Object）：业务对象，由 Service 层输出的封装业务逻辑的对象。
 AO（Application Object）：应用对象，在 Web 层与 Service 层之间抽象的复用对象模型，
极为贴近展示层，复用度不高。
 VO（View Object）：显示层对象，通常是 Web 向模板渲染引擎层传输的对象。
 Query：数据查询对象，各层接收上层的查询请求。注意超过 2 个参数的查询封装，禁止
使用 Map 类来传输。

## 问题描述
DTO与BO的区别是？ DTO是用于开放接口，BO是用于Web层？

VO疑惑，Web层响应给前端用VO，那Web层接收前端的参数也是VO？

Query疑惑，Service层接收Web层传递的参数用Query，那Web层接收前端的也是用Query还是VO？

**Comment by LuffyGao** [comment]
@yangguanbao

**Comment by LuoYingxiong** [comment]
本人也有相同的疑惑。阿里的分层领域模型规约缺少Demo

**Comment by LuoYingxiong** [comment]
本人也有相同的疑惑。阿里的分层领域模型规约缺少Demo ,我现在是在Controller用VO接收前端参数、主要是新增、编辑场景的。用Query类接收各种查询参数 @zhangyq233 。但不确定是否合理

**Comment by Yuyang105** [comment]
![image](https://user-images.githubusercontent.com/12386416/105827368-dc753c00-5ffc-11eb-810a-2a9253ee69af.png)
1. DTO与BO和Web无关，BO在DTO之上，用来组装更加复杂的业务单元，比如多个DTO的若干属性可以用BO封装；
2. 接受传输请求可以复用VO，如果是明确的查询请求用Query；
3. Service层接收的一定是Query。

**Comment by LuoYingxiong** [comment]
@Yuyang105 谢谢你的解答，我觉得你们公司的规约，如果能附上一个针对各种领域模型的简单的Demo最好了。寥寥几句话还真是让人困惑。更主要是我在网上一搜DO、DTO、BO、AO、VO、Query。通篇都是复制你们规约原文的内容。根本搜不到更详细的解释

**Comment by zhangyq233** [comment]
@Yuyang105 谢谢你的解答。我看之前华山版有AO的介绍，后续就没了，为什么废弃的？   前端发起一个保存数据的请求，用@RequestBody接收，创一个saveAO对象用于接收，这种方式将请求跟响应区分开了，是不是挺不错的。

**Comment by zhangyq233** [comment]
@Yuyang105 你们有没有关于规范的钉钉群或者之类其他的demo之类的可以供大家一起探讨一起研究？  主要是想让公司的小伙伴更好的规范写代码。

**Comment by zqq90** [comment]
+1
