### ISSUE TITLE
关于多行if...else...注释的问题

### ISSUE THREAD

**Issue by ccpwcn** [alibaba/p3c#768]
## 规约原文
插件是不推荐使用行尾注释的。

## 问题描述
对于多行的if...else if...else if...的注释应该怎么写才是最佳实践呢？示例代码：
```
// 如果是1
if (a == 1) {
    System.out.println('一');
} else if (a == 2) {  // 如果是2
    System.out.println('二');
} else if (a == 3) {  // 如果是3
    System.out.println('三');
} else if (a == 4) {  // 如果是4
    System.out.println('四');
}
```

## 修改建议
上述示例代码的注释，看上去不优雅，也不符合“不使用行尾注释”的约定，那么，这4行注释应该怎么写为好呢？

**Comment by zhangyq233** [comment]
同问

**Comment by yangguanbao** [comment]
// 如果是1
if (a == 1) {
    System.out.println('一');
// 如果是2
} else if (a == 2) {  
    System.out.println('二');
// 如果是3
} else if (a == 3) {  
    System.out.println('三');
// 如果是4
} else if (a == 4) {  
    System.out.println('四');
}

大胆的加在else if上方。

**Comment by yangguanbao** [comment]
// 如果是1
if (a == 1) {
    System.out.println('一');
} else if (a == 2) {
    // 如果是2
    System.out.println('二');
} else if (a == 3) {
    // 如果是3
    System.out.println('三');
} else if (a == 4) {
    // 如果是4
    System.out.println('四');
}

大胆的加在else if上方。

**Comment by yangguanbao** [comment]
// 如果是1
if (a == 1) {
System.out.println('一');
} else if (a == 2) {
// 如果是2
System.out.println('二');
} else if (a == 3) {
// 如果是3
System.out.println('三');
} else if (a == 4) {
// 如果是4
System.out.println('四');
}
