### ISSUE TITLE
定义DO/DTO/VO等POJO类时不要设定任何属性默认值反例疑问

### ISSUE THREAD

**Issue by MetaRunning** [alibaba/p3c#769]
关于如下规则
【强制】定义 DO / DTO / VO 等 POJO 类时，不要设定任何属性默认值。
反例： POJO 类的 gmtCreate 默认值为 new Date();
但是这个属性在数据提取时并没有置入具体值，在更新其它字段时又附带更新了此字段，导致创建时间被修改成当前时间。

我写了一个测试用例，例如Student这个类
@Data
public class Student {
    private Integer age;
    private Date curDate = new Date();
}
    @Test
    public void test1() throws InterruptedException {
        Student student = new Student();
        System.out.println(System.currentTimeMillis());
        Thread.sleep(2000);
        student.setAge(34);
        System.out.println(student.getCurDate().getTime());
    }
我对比了两次时间戳，发现时间是相同的，说明student中的curDate的时间没有发生变化。
不太规约中反例的含义，谁能给一个更加清晰的反例用例吗？

**Comment by yangguanbao** [comment]
public class Student {
private Integer age;
private Date create_date = new Date();
}

select age from table;  给这个对象。
这里并没有提取到Date，
age=新值时，更新时，new Date() 把create_date也更新了
