### ISSUE TITLE
插件运行后卡的要死

### ISSUE THREAD

**Issue by penweizgx** [alibaba/p3c#77]
安装插件后，执行分析代码后（包含分析完），电脑就变得异常卡顿，macOS 10.12.4,Eclipse4.5

**Comment by charleskoo** [comment]
未分析前正常，分析之后卡得只能重启 win10, Eclipse4.7

**Comment by xiaochunping** [comment]
表示我运行插件eclipse就卡死，代码多的项目根本不能玩

**Comment by i-kindle** [comment]
idea加 i5 7500 + 8g + 256g ssd 没感觉

**Comment by Gonjan** [comment]
看来卡顿现象只存在于eclipse

**Comment by battlesteed** [comment]
eclipseneon和目前最新的eclipseoxygn都不行;,jpa插件已经卸载了,不是jpa循环调用bug

**Comment by zy117** [comment]
JPA已卸载，代码一多就eclipse未响应，只能一个文件一个文件的查

**Comment by SeanCai** [comment]
@zy117 扫描完成后 会出现 cpu 100%的情况吗

**Comment by ccpwcn** [comment]
不是的，我的IDEA开了这个插件之后，如果开一个IDEA，感觉没啥，开三个的时候，IDEA就非常卡顿，就连编辑功能都明显受影响。我断定和硬件配置没关系，下面贴一下我的硬件配置：
_处理器	英特尔 Core i7-6700HQ @ 2.60GHz 四核
主板	戴尔 0N7TVV
内存	32 GB ( 三星 DDR4 2133MHz )
主硬盘	闪迪 SD8SN8U512G1122 ( 512 GB / 固态硬盘 )_
最后，还是建议使用GPU加速，这样效能会更好一些。
