### ISSUE TITLE
CompletableFuture异步执行规范

### ISSUE THREAD

**Issue by Qianlu5110** [alibaba/p3c#773]
大部分同事，在使用CompletableFuture开启异步线程执行任务时，只是简单开启异步线程没有合理使用CompletableFuture，导致异步线程程序出错时，不输出堆栈日志，程序报错。

@Test
public void test0() throws InterruptedException {
  CompletableFuture
      .runAsync(() -> {
          log.info("start async");
          // 抛出异常
          int num = 1 / 0;
          log.info("end async");         
      });
  Thread.sleep(5000L);
  log.info("test0 end");
}
 

这种场景下，异常堆栈不会打印出来。

@Test
public void test0() throws InterruptedException {
  CompletableFuture
      .runAsync(() -> {
        log.info("start async");
        int num = 1 / 0;
        log.info("end async");
      })
      .exceptionally(e -> {
        e.printStackTrace();
        return null;
      });
  Thread.sleep(5000L);
  log.info("test0 end");
}
我觉得可以集成在规范组件中，进行错误提醒。

**Comment by Qianlu5110** [comment]
> 大部分同事，在使用CompletableFuture开启异步线程执行任务时，只是简单开启异步线程没有合理使用CompletableFuture，导致异步线程程序出错时，不输出堆栈日志，程序报错。
> 
> @test
> public void test0() throws InterruptedException {
> CompletableFuture
> .runAsync(() -> {
> log.info("start async");
> // 抛出异常
> int num = 1 / 0;
> log.info("end async");
> });
> Thread.sleep(5000L);
> log.info("test0 end");
> }
> 
> 这种场景下，异常堆栈不会打印出来。
> 
> @test
> public void test0() throws InterruptedException {
> CompletableFuture
> .runAsync(() -> {
> log.info("start async");
> int num = 1 / 0;
> log.info("end async");
> })
> .exceptionally(e -> {
> e.printStackTrace();
> return null;
> });
> Thread.sleep(5000L);
> log.info("test0 end");
> }
> 我觉得可以集成在规范组件中，进行错误提醒。

**Comment by LuffyGao** [comment]
@yangguanbao

**Comment by Qianlu5110** [comment]
会采纳吗

**Comment by Yuyang105** [comment]
你好，感谢支持。我们将在下一版--《黄山版》考虑增加相应规则。
