### ISSUE TITLE
日志文件把保存日期放在拓展名前面，便于系统识别文件类型

### ISSUE THREAD

**Issue by LinWanCen** [alibaba/p3c#774]
## 规约原文

2. 【强制】所有日志文件至少保存 15 天，因为有些异常具备以“周”为频次发生的特点。对于当天日志，以“应用名.log”来保存，保存在/home/admin/应用名/logs/目录下，过往日志格式为: {logname}.log.{保存日期}，日期格式：yyyy-MM-dd
正例：以 aap 应用为例，日志保存在/home/admin/aapserver/logs/aap.log，历史日志名称为 aap.log.2016-08-01

## 问题描述

统一以文件类型拓展名 log 结尾，便于系统识别文件类型。

~这里的 admin 显得突兀，参考之前在工商银行的风格，用/home/logs/应用名目录（工商银行是 Docker 部署）~
解压的软件和开发的应用软件应该放在/opt目录，日志放在接近的位置方便查看

日志压缩比例非常高，可以极大地减少磁盘空间压力，下载也更快，用 vi 等命令可以也直接查看不影响体验

## 修改建议

2. 【强制】所有日志文件至少保存 15 天，因为有些异常具备以“周”为频次发生的特点。对于当天日志，以“应用名.log”来保存，保存在/opt/logs/应用名/目录下，过往日志 格式为: {logname}.{保存日期}.log.gz，日期格式：yyyy-MM-dd
正例：以 aap 应用为例，日志保存在/opt/logs/aapserver/aap.log，历史日志名称为 aap.2016-08-01.log.gz

**Comment by smiler158** [comment]
@yangguanbao

**Comment by Yuyang105** [comment]
你好，感谢支持。压缩方式在下一个版本--《黄山版》考虑作为推荐方式说明。
