### ISSUE TITLE
代码格式添加对应的checkstyle的配置文件

### ISSUE THREAD

**Issue by penglingfeng1995** [alibaba/p3c#775]
虽然大家统一使用了对应的eclipse_codeformatter.xml，但是开发过程中，部分人员有的配置可能没生效，或者提交代码前，没有进行格式化

希望有格式化对应的checkstyle的xml配置文件，能够使用checkstyle插件进行格式化校验，最好是能让checkstyle官方插件能自带ali的配置，目前官方只有sun_checks和google_checks，希望有一天能看见 alibaba_checks.xml

**Comment by smiler158** [comment]
https://github.com/alibaba/p3c/blob/master/p3c-formatter/eclipse-codestyle.xml 参考这个
