### ISSUE TITLE
五MySQL数据库 (三)SQL 语句第三条的正例的IFNULL函数建议改为COALESCE

### ISSUE THREAD

**Issue by erlanp** [alibaba/p3c#776]
## 规约原文
3. 【强制】当某一列的值全是 NULL 时，count(col)的返回结果为 0，但 sum(col)的返回结果为
NULL，因此使用 sum()时需注意 NPE 问题。
正例：可以使用如下方式来避免 sum 的 NPE 问题：SELECT IFNULL(SUM(column), 0) FROM table;

## 问题描述
SELECT IFNULL(SUM(column), 0) FROM table;
IFNULL函数只能在mysql数据库的实现中使用， 不是mysql标准

## 修改建议
改用 COALESCE做示例

**Comment by Yuyang105** [comment]
你好，谢谢支持，我们将在下一版本--《黄山版》中增加coalesce对应说明。
