### ISSUE TITLE
类行数很大的时候CPU飙升，禁用插件后恢复正常

### ISSUE THREAD

**Issue by itning** [alibaba/p3c#779]
什么时候解决下CPU飙升问题

**Comment by LuffyGao** [comment]
辛苦给下操作系统和对应的开发工具，已经使用的版本

**Comment by itning** [comment]
> 辛苦给下操作系统和对应的开发工具，以及使用的版本

操作系统：Microsoft Windows 10 专业版 (BUILD:19041) (64 位)
CPU信息：Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
步进：3 型号：E 系列：6 扩展型号：5E 扩展系列：6
主板信息：Notebook () N15_17RF
内存信息：16.0 GB (8.0 GB / 8.0 GB / )
显卡信息：NVIDIA GeForce GTX 965M
Intel(R) HD Graphics 530

硬盘信息：HGST HTS721010A9E630 (1.0 TB)
WDC WD10SPZX-22Z10T0 (1.0 TB)
KIOXIA-EXCERIA SSD (500.0 GB)

网卡信息：Realtek PCIe GbE Family Controller (以太网)
Intel(R) Dual Band Wireless-AC 3165 (WLAN)
Bluetooth Device (Personal Area Network) (蓝牙网络连接)

声卡信息：NVIDIA High Definition Audio
英特尔(R) 显示器音频
Realtek High Definition Audio

显示设备：冠捷 AOC Q2790 [AOC2790] 27.2英寸
三星 Samsung [SDC4852] 15.3英寸

IntelliJ IDEA 2020.2.3 (Ultimate Edition)
Build #IU-202.7660.26, built on October 6, 2020

**Comment by smiler158** [comment]
> > 辛苦给下操作系统和对应的开发工具，以及使用的版本
> 
> 操作系统：Microsoft Windows 10 专业版 (BUILD:19041) (64 位)
> CPU信息：Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
> 步进：3 型号：E 系列：6 扩展型号：5E 扩展系列：6
> 主板信息：Notebook () N15_17RF
> 内存信息：16.0 GB (8.0 GB / 8.0 GB / )
> 显卡信息：NVIDIA GeForce GTX 965M
> Intel(R) HD Graphics 530
> 
> 硬盘信息：HGST HTS721010A9E630 (1.0 TB)
> WDC WD10SPZX-22Z10T0 (1.0 TB)
> KIOXIA-EXCERIA SSD (500.0 GB)
> 
> 网卡信息：Realtek PCIe GbE Family Controller (以太网)
> Intel(R) Dual Band Wireless-AC 3165 (WLAN)
> Bluetooth Device (Personal Area Network) (蓝牙网络连接)
> 
> 声卡信息：NVIDIA High Definition Audio
> 英特尔(R) 显示器音频
> Realtek High Definition Audio
> 
> 显示设备：冠捷 AOC Q2790 [AOC2790] 27.2英寸
> 三星 Samsung [SDC4852] 15.3英寸
> 
> IntelliJ IDEA 2020.2.3 (Ultimate Edition)
> Build #IU-202.7660.26, built on October 6, 2020
帮给下p3c插件版本

**Comment by itning** [comment]
> 帮给下p3c插件版本
> 
> > > 辛苦给下操作系统和对应的开发工具，以及使用的版本
> > 
> > 
> > 操作系统：Microsoft Windows 10 专业版 (BUILD:19041) (64 位)
> > CPU信息：Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
> > 步进：3 型号：E 系列：6 扩展型号：5E 扩展系列：6
> > 主板信息：Notebook () N15_17RF
> > 内存信息：16.0 GB (8.0 GB / 8.0 GB / )
> > 显卡信息：NVIDIA GeForce GTX 965M
> > Intel(R) HD Graphics 530
> > 硬盘信息：HGST HTS721010A9E630 (1.0 TB)
> > WDC WD10SPZX-22Z10T0 (1.0 TB)
> > KIOXIA-EXCERIA SSD (500.0 GB)
> > 网卡信息：Realtek PCIe GbE Family Controller (以太网)
> > Intel(R) Dual Band Wireless-AC 3165 (WLAN)
> > Bluetooth Device (Personal Area Network) (蓝牙网络连接)
> > 声卡信息：NVIDIA High Definition Audio
> > 英特尔(R) 显示器音频
> > Realtek High Definition Audio
> > 显示设备：冠捷 AOC Q2790 [AOC2790] 27.2英寸
> > 三星 Samsung [SDC4852] 15.3英寸
> > IntelliJ IDEA 2020.2.3 (Ultimate Edition)
> > Build #IU-202.7660.26, built on October 6, 2020

2.1.0

**Comment by xuantan** [comment]
可以下载最新版本插件试试。
