### ISSUE TITLE
idea插件和sonar插件扫描出来的问题有差异，sonar上扫描出来的问题数量要少很多

### ISSUE THREAD

**Issue by assilzm** [alibaba/p3c#780]
## 问题描述
     idea插件和sonar插件扫描出来的问题有差异，sonar上扫描出来的问题数量要少很多
     
idea插件扫描结果
![QQ截图20201112164949](https://user-images.githubusercontent.com/1506245/98917333-3179d980-2507-11eb-8ee5-f9a6d741a84b.jpg)

sonar插件扫描结果
![QQ截图20201112165010](https://user-images.githubusercontent.com/1506245/98917343-350d6080-2507-11eb-85a8-da01b90ec297.jpg)

可以从图上看出："所有的包装类对象之间值的比较，全部使用equals方法比较。"以及“所有的覆写方法，必须加@Override注解。”都没扫描到结果，查看源代码，发现源代码的确存在上诉问题。

p3c版本2.1.1 sonarqube版本7.8

**Comment by yansheng836** [comment]
额，其实他们各自的依据标准不一样，所以扫描出的问题有所差异好像也无可厚非吧？

而且有很多都是建议性的，并没有要求你一定要遵守，就像你是否会使用这些插件一样，都是个人的选择，除非你们公司有规定……

**Comment by smiler158** [comment]
所有的覆写方法，必须加@override注解这条规则=》idea端跟sonar端是单独实现的，sonar需要开启本身的override规则。

**Comment by slin1972** [comment]
@assilzm 请问你的plugin的包是自己构建的吗，方便提供给我吗，我在网上看到的都是一些老版本
