### ISSUE TITLE
MySQL数据库——SQL语句第13条，个人认为说法不严谨

### ISSUE THREAD

**Issue by xianwdong** [alibaba/p3c#781]
## 规约原文
说明：TRUNCATE TABLE 在功能上与不带 WHERE 子句的 DELETE 语句相同。
## 问题描述
TRUNCATE TABLE会导致自增id计数从0开始，但是DELETE不会
## 修改建议
建议加上关于自增id区别的说明

**Comment by Yuyang105** [comment]
@xianwdong 感谢指出，我们将在下一版--《黄山版》增加说明
