### ISSUE TITLE
禁止使用构造方法BigDecimal(double)的方式把double值转化为BigDecimal对象 检测错误

### ISSUE THREAD

**Issue by freshgeek** [alibaba/p3c#782]
**Describe the bug**

>             BigDecimal ztpjAllScore = new BigDecimal(Double.toString(0.0)) ;

禁止使用构造方法BigDecimal(double)的方式把double值转化为BigDecimal对象 

检测错误

此处使用的是 2.1.0 版本插件 ， IDEA 版本如下：

![image](https://user-images.githubusercontent.com/20513615/102220667-1a6e4300-3f1c-11eb-81e7-582cb79a670a.png)
![image](https://user-images.githubusercontent.com/20513615/102220703-24904180-3f1c-11eb-9e56-115ce66dd4dd.png)

**To Reproduce**
1. 随意在src.main.java 下创建一个类 
2.  加入其中代码后，
3. 右键点击编码规约扫描

**Expected behavior**

检测错误

禁止使用构造方法BigDecimal(double)的方式把double值转化为BigDecimal对象 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by XenoAmess** [comment]
我在TPM里修复了。
相关commit https://github.com/XenoAmess/p3c/commit/3ce4d0395fcd3132db7abdffe665a960519ac074
已经submit了
应该两天内能过idea审核
总之欢迎使用TPM

**Comment by freshgeek** [comment]
> 我在TPM里修复了。
> 相关commit [XenoAmess@3ce4d03](https://github.com/XenoAmess/p3c/commit/3ce4d0395fcd3132db7abdffe665a960519ac074)
> 已经submit了
> 应该两天内能过idea审核
> 总之欢迎使用TPM
> 
> https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

Ok ，Thanks

**Comment by XenoAmess** [comment]
> > 我在TPM里修复了。
> > 相关commit [XenoAmess@3ce4d03](https://github.com/XenoAmess/p3c/commit/3ce4d0395fcd3132db7abdffe665a960519ac074)
> > 已经submit了
> > 应该两天内能过idea审核
> > 总之欢迎使用TPM
> > https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-
> 
> Ok ，Thanks

https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-/versions/stable/105548 已过审核。感谢。
