### ISSUE TITLE
static final 属性并不都是常量

### ISSUE THREAD

**Issue by cn-src** [alibaba/p3c#783]
## 规约原文

常量命名应该全部大写，单词间用下划线隔开，力求语义表达完整清楚，不要嫌名字长 
            
    public class ConstantNameDemo {

    /**
    * max stock count
    */
    public static final Long MAX_STOCK_COUNT = 50000L;
            
        
 
## 问题描述
static final 属性并不都是常量，这没什么好说的。

## 修改建议
除非是明确的不可变类型，否则都不应该提示全部大写。

我觉得p3c还是太死板了，应该可自定义配置，比如可配置哪些类型可以作为常量。

**Comment by cn-src** [comment]
要不是需要遵循基本的约定，我根本就不想用全大写，小写都不怎么认识，大写更是懵逼:joy:。

**Comment by Yuyang105** [comment]
你好，谢谢，暂时不做修改，形成统一的规范有利于代码的可读性。

**Comment by zacker330** [comment]
常量要大写。这是一个规范。但是那明显不是常量，不应该大写。然而，p3c对这个帖的回复又是要形成统一规范。这个“规范”是哪个规范？
这个逻辑不对吧。
