### ISSUE TITLE
UserCase拼写错误[7.设计规约--第二条]

### ISSUE THREAD

**Issue by likai-hust** [alibaba/p3c#784]
### 七、设计规约
……
2. 【强制】在需求分析阶段，如果与系统交互的User超过一类并且相关的 `User Case` 超过5个
……
## 问题描述
`User Case` 拼写错误
## 修改建议
`User Case`修改为**Use Case**

**Comment by Yuyang105** [comment]
好的，感谢支持！我们在最新版本--黄山版，进行修正。
