### ISSUE TITLE
DTO、DAO、PO、等专用名称在方法名中间的情况下会报lowerCamelCase

### ISSUE THREAD

**Issue by imwulv** [alibaba/p3c#785]
## 规约原文
方法名、参数名、成员变量、局部变量都统一使用lowerCamelCase，必须遵从驼峰形式
## 问题描述

`public void queryxxxDAOByName(){
       // Do Something
}`

类似上述情况，会报Critical检查项异常。但是实际工作中会经常出现上述情况。检查结果会对研发造成一些困扰。
你们是否建议将queryxxxDAOByName()改成queryxxxDaoByName()这种形式呢？
但是在编程规约中又明确约定了反例：
![image](https://user-images.githubusercontent.com/22405655/102958445-da105580-4517-11eb-8cc5-0390f15abea7.png)

## 修改建议
能否添加排除项，若中间问题项中出现DTO、DAO之类的领域名称不计入异常？

**Comment by mghio** [comment]
是不是不推荐在`方法名`、`成员变量`、`参数名`、`局部变量` 中间使用专用名称？

**Comment by LamGC** [comment]
同意这个建议，能否在内置专用名称大小写排除列表的同时，再添加一个项目级别的自定义专用名称缩写排除列表呢？

**Comment by YeautyYE** [comment]
+1

**Comment by xuantan** [comment]
你好，当前的解决方案是自行维护专用名词列表，然后重新打包构建此插件。
