### ISSUE TITLE
自定义@Transactional注解提示异常

### ISSUE THREAD

**Issue by ws657455522** [alibaba/p3c#787]
环境：springboot、win10
描述：自定义@Transactional注解(非spring，只是名字和spring的命名相同)会提示“方法【method】需要在Transactional注解指定rollbackFor或者在方法中显式的rollback。 ”

**Comment by XenoAmess** [comment]
@ws657455522 这个区分拿pmd似乎不太好做……可以考虑拿一些其他库去联合使用，比如qdox
孤尽老哥怎么看？

**Comment by ws657455522** [comment]
我发现TransactionMustHaveRollbackRule.visit中name.getImage()的值为Transactional（可能这块可以取到全类名比较好），导致条件判断出现这样的问题。
我感觉目前的判断方式也有一定的道理，不知道@XenoAmess怎么看

**Comment by XenoAmess** [comment]
> 我发现TransactionMustHaveRollbackRule.visit中name.getImage()的值为Transactional（可能这块可以取到全类名比较好），导致条件判断出现这样的问题。
> 我感觉目前的判断方式也有一定的道理，不知道@XenoAmess怎么看

@ws657455522 我不是给你说了，p3c底层调用的是pmd，pmd就是这个样子，它不给全名，阿里人能有什么办法。
我也提供方法了，就是用别的库，比如qdox，然后加上一些链接性的机制，让pmd的每个class能关联到qdox解析的文件/class，然后qdox能拿到全名。
