### ISSUE TITLE
mybatis注解SQl格式化问题

### ISSUE THREAD

**Issue by jinghongdaxiong** [alibaba/p3c#791]
@Select("SELECT\n" + "  epr.pr_id,\n" + "  epr.pr_name,\n" + "epr.pr_pid,\n" + "epr.pr_client_type,\n"
        + "epr.sort,\n" + "  (etmr.id is not null) AS 'selected'\n" + "FROM\n" + "  edu_permission_resources epr\n"
        + "LEFT JOIN edu_tag_menu_rel etmr ON etmr.pr_id = epr.pr_id\n" + "where epr.pr_pid = #{prPid}\n")

以上为sql格式化后的代码，但理解不清晰，如何避免格式化mybatis注解方式实现的sql查询？

**Comment by xuantan** [comment]
你好，这不是插件可以解决的问题。
