### ISSUE TITLE
在使用Java8 stream特性时，开启实时检测功能，非常卡，甚至IDEA死掉。关掉恢复正常

### ISSUE THREAD

**Issue by shengulong** [alibaba/p3c#792]
环境：
1. Mac Big Sur 11.1
2. IDEA 2020.3.1

之前都没有问题，实时检测一直开启。最近处理大量复杂数据，便使用了Java8的新特性Stream，然后就遇到如题问题。关闭实时检测，问题解决

`
private List<List<String>> getData(
      Map<String, Set<String>> stringSetMap, ArrayList<CheckData> checkDataList) {

    List<List<String>> list = new ArrayList<>();
    checkDataList.forEach(
        checkData -> {
          List<String> data = new ArrayList<>();
          data.add(checkData.getInstanceId());
          data.add(checkData.getInstanceName());
          data.add(checkData.getInstanceIp());
          data.add(checkData.getUpdatedTime().toString());
          data.add(checkData.getArea());
          stringSetMap
              .keySet()
              .forEach(
                  key -> {
                    JSONArray jsonArray = checkData.getData().getJSONArray(key);
                    Set<String> stringSet = stringSetMap.get(key);
                    stringSet.forEach(
                        s1 -> {
                          AtomicBoolean flag = new AtomicBoolean(true);
                          jsonArray.forEach(
                              o1 -> {
                                JSONObject jsonObject = (JSONObject) o1;
                                jsonObject.forEach(
                                    (key1, value) -> {
                                      if (key1.equals(s1)) {
                                        data.add((String) value);
                                        flag.set(false);
                                        # 此处操作几次，就会卡死
                                      }
                                    });
                              });
                          if (flag.get()) {
                            data.add("Null");
                          }
                        });
                  });
          list.add(data);
        });
    return list;}

`

**Comment by l619534951** [comment]
我也很卡呀，我以为是七代i5太垃圾了，然后卡分析一看，是这个插件的锅，如果能优化下就好了，我现在已经暂时关了。
我用快捷键跳转各个方法也会卡，不用快捷键会好一点。

**Comment by xuantan** [comment]
@SeanCai 看下

**Comment by SeanCai** [comment]
初步判断是当forEach嵌套过深的情况下，敲击新的字符会导致PMD解析语法树的时候会卡在 add_error_token节点。 使用PMD命令行需要大概20秒钟才能返回，IDEA中时间更长。 我们研究一下如何以最小的代价避免或者减少对IDEA自身性能造成影响。
![image](https://user-images.githubusercontent.com/5645909/105933256-1429c580-6089-11eb-8c17-5ed3106e324d.png)
如果遇到这种情况，建议大家先关闭实时扫描

**Comment by l619534951** [comment]
> 我也很卡呀，我以为是七代i5太垃圾了，然后卡，分析一看，是这个插件的锅，如果能优化下就好了，我现在已经暂时关了。
> 我用快捷键跳转各个方法也会卡，不用快捷键会好一点。

我现在解决了，换了个10400，一切都好起来了

**Comment by XenoAmess** [comment]
只能说 拒绝流式，避免低性能代码，人人有责
