### ISSUE TITLE
inspection settings not effort

### ISSUE THREAD

**Issue by zonghai** [alibaba/p3c#797]
问题描述：
1.在idea的preference的inspections中设置Ali-check ，list中的选项去掉和页面右侧Severity进行修改都不生效。
修改后重启idea和不重启都是一样的，不生效。
<img width="977" alt="a" src="https://user-images.githubusercontent.com/1704786/105476672-e1c04700-5cdb-11eb-8692-d34e0c089931.png">
<img width="682" alt="b" src="https://user-images.githubusercontent.com/1704786/105476786-fef51580-5cdb-11eb-92c6-6e4500f8463b.png">

macbook idea 2018.3.3和2020.3都进行设置，没有生效。
插件版本：现在最新的版本-2.1.0。

**Comment by smiler158** [comment]
这里修改生效后只涉及实时扫描结果， 请问下您这边期望生效的范围是指？

**Comment by xuantan** [comment]
你好，修改生效后只涉及实时扫描结果，不涉及手动扫描操作。
