### ISSUE TITLE
使用命令行能否指定输出文件目录

### ISSUE THREAD

**Issue by MicroKibaco** [alibaba/p3c#798]
运行了 `java -cp /xxx/xxx/xxx/p3c-pmd-2.1.0.jar  net.sourceforge.pmd.PMD -d /xxx/xxx/xxx -R /xxx/xxx/xxx/p3c-p3c-pmd-2.1.0/p3c-pmd/src/main/resources/rulesets/java/ali-comment.xml  -f html -b tinybin.html` 

能否指定输出文件目录,已经解决了 谢谢🙏

**Comment by MicroKibaco** [comment]
找到原因了 谢谢🙏

**Comment by smiler158** [comment]
ok

**Comment by MicroKibaco** [comment]
无法生成最新版本的 flat.jar
