### ISSUE TITLE
希望有风格设置文件

### ISSUE THREAD

**Issue by Lin-WangCheng** [alibaba/p3c#8]
手动遵守不如在IDE设置好，我按着这个规约和谷歌HTML CSS双空格等规范设置了一个，不过总觉得没有官方出的好，希望官方出设置导出文件。

**Comment by geekerview** [comment]
有了风格设置文件，就可以集成进CD里面做代码自动化检查了。

**Comment by xuantan** [comment]
见这里  https://github.com/alibaba/p3c/tree/master/p3c-formatter
