### ISSUE TITLE
如何将扫描结果，文档化显示

### ISSUE THREAD

**Issue by xiaogangfan** [alibaba/p3c#801]
背景：我们在做codereview，需要引入一个机制，察看团队的执行情况，即新增的代码有没有按照规范在编码
期望：
    输入：代码的git地址
    输出：严重、建议、参考的数量，便于统计大家的改进情况

**Comment by XenoAmess** [comment]
以maven plugin的形式使用这玩意。
看看你target下的pom.xml，然后解析一下 读一下 生成一下报告 就行了吧。

**Comment by King-Pan** [comment]
同问，使用sonarqube 怎么与ali的p3c-pmd组件结合使用

**Comment by xuantan** [comment]
可以自行包装出一个sonar插件，集成sonar进行统计查看
