### ISSUE TITLE
能不能配置只扫描每次改动或新增的diff文件？

### ISSUE THREAD

**Issue by xu20160924** [alibaba/p3c#804]
## 问题描述
能不能配置只扫描每次改动或新增的diff文件？这样每次就只用关心自己的改动，不用整体都扫描。
## 修改建议
能不能配置只扫描每次改动或新增的diff文件？这样每次就只用关心自己的改动，不用整体都扫描。

**Comment by XenoAmess** [comment]
给你个思路
git钩子判断diff 的java文件
然后调用pmd

**Comment by xu20160924** [comment]
可以通过idea 里的git 窗口看到变动的文件  然后全选进行扫描。 这样扫描会扫描整个文件，但也缩小了范围。

**Comment by XenoAmess** [comment]
> 可以通过idea 里的git 窗口看到变动的文件 然后全选进行扫描。 这样扫描会扫描整个文件，但也缩小了范围。

哦，我还以为你需要自动化方案来着233
