### ISSUE TITLE
结合gitlab乱码

### ISSUE THREAD

**Issue by fhyfhy17** [alibaba/p3c#809]
结合gitlab  pre-receive，push时乱码

`无文件要提交，干净的工作区
Counting objects: 13, done.
Delta compression using up to 16 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (7/7), 573 bytes | 0 bytes/s, done.
Total 7 (delta 1), reused 0 (delta 0)
remote: Mar 11, 2021 10:18:36 AM net.sourceforge.pmd.PMD processFiles
remote: WARNING: This analysis could be faster, please consider using Incremental Analysis: https://pmd.github.io/pmd-6.15.0/pmd_userdocs_incremental_analysis.html
remote: /var/opt/gitlab/git-data/repositories/root/pretest.git/tmp/src/main/java/com/Test.java:4:	??Test?????javadoc?????
remote: /var/opt/gitlab/git-data/repositories/root/pretest.git/tmp/src/main/java/com/Test.java:5:	?Test?????@author??
To http://192.168.101.164:8181/root/pretest.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: 无法推送一些引用到 'http://192.168.101.164:8181/root/pretest.git'`

应该不是终端问题，如上，其它汉字正常显示。

或者可否告之，怎么把提示切换成英语提示。
噢看到了。。。  private static String lang = System.getProperty("pmd.language", "zh");  设置这个是吧。。。没更方便的吗

**Comment by xuantan** [comment]
System.getProperty("pmd.language", "zh") 修改此参数试下？
