### ISSUE TITLE
请问哪里可以获取到编码规约的word或者markdown原文？

### ISSUE THREAD

**Issue by IcebergXTY** [alibaba/p3c#810]
公司内部的编码规范大部分都跟阿里规约相同，但有小部分是不一样的，希望能在阿里规约的基础上修改为内部的规范。

但是我只能看到pdf格式的，修改起来比较麻烦。

[gitbook](https://github.com/alibaba/p3c/tree/master/p3c-gitbook)里倒是有md源文件，但是似乎很老旧了

**Comment by xuantan** [comment]
@dyrone 关注下

**Comment by dyrone** [comment]
@IcebergXTY 

Thanks for the advice, here is the related PR:
https://github.com/alibaba/p3c/issues/847
