### ISSUE TITLE
We hope to increase AO and PO on the basis of DO and BO , DTO , VO.

### ISSUE THREAD

**Issue by JoverZhang** [alibaba/p3c#822]
## 规约原文

![image](https://user-images.githubusercontent.com/38241684/116982449-63703980-acfb-11eb-81dc-65a91feca5de.png)

## 问题描述

在使用 DO 和 BO, DTO 等均正常, 但是当使用 AO 和 PO 作为变量名后缀时, 会出现单词拼写异常.

![image](https://user-images.githubusercontent.com/38241684/116982987-1b9de200-acfc-11eb-965d-cdeb126794cc.png)

## 修改建议

希望支持 xxxAO 和 xxxPO 变量命名规则

**Comment by XenoAmess** [comment]
如果需要自由配置可以考虑切到TPM

https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

https://github.com/XenoAmess/p3c/blob/xenoamess_maintain_fork/idea-plugin/README_cn.md

**Comment by JoverZhang** [comment]
@XenoAmess 已解决, 多谢
