### ISSUE TITLE
idea2021.2报错

### ISSUE THREAD

**Issue by Ryoui** [alibaba/p3c#825]
2.1.0版本
![图片](https://user-images.githubusercontent.com/18000474/120293172-948e5a80-c2f7-11eb-9322-b594d5bc465d.png)

**Comment by yun-yun** [comment]
同样的问题

**Comment by yun-yun** [comment]
@xuantan @SeanCai 能抽空帮忙修复下吗

**Comment by fyeeme** [comment]
同样错误，希望尽快适配，另外，能否支持规则自定义禁止

**Comment by XenoAmess** [comment]
@Ryoui @yun-yun @fyeeme 
看起来是他们使用的旧配置机制在新版本idea中**终于**被废弃了
可以考虑换用TPM
https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

**Comment by Ryoui** [comment]
@XenoAmess 昨天已经切换了，确实没问题了，感谢
