### ISSUE TITLE
STS规约扫描报错

### ISSUE THREAD

**Issue by xin-hu** [alibaba/p3c#830]
**Describe the bug**
An internal error occurred during: "P3C Code Analysis".
javax/annotation/Generated

**To Reproduce**
规约扫描

**OS：windows10 64位，STS版本：4.10，JDK：1.8

**Comment by xuantan** [comment]
@imu2008 看下

**Comment by imu2008** [comment]
@xin-hu 建议先用原生eclipse测试下，sts的版本没有兼容性测试过
