### ISSUE TITLE
中文版：阿里巴巴Java开发手册中MySQL数据库的“唯一索引”写成了“惟一索引”

### ISSUE THREAD

**Issue by br-bai** [alibaba/p3c#833]
貌似提这个issue有点无聊，最近在看嵩山版发现中文版第五章MySQL数据库中“索引规约”的第11条“唯一索引”写成了“惟一索引”

11.【参考】创建索引时避免有如下极端误解：
    1） 索引宁滥勿缺。认为一个查询就需要建一个索引。
    2） 吝啬索引的创建。认为索引会消耗空间、严重拖慢记录的更新以及行的新增速度。
    3） 抵制惟一索引。认为惟一索引一律需要在应用层通过“先查后插”方式解决。

**Comment by mackyuqimack** [comment]
惟一和 唯一在语境方面有区别，两者虽然都表示“独、只有”的意思，但对象不同，惟一更侧重主观性。

**Comment by gujin520** [comment]
感谢反馈，在黄山版中修正。
