### ISSUE TITLE
idea 2018.3 换行/空行也计算在代码行数中，导致超过80行

### ISSUE THREAD

**Issue by imalvisc** [alibaba/p3c#835]
idea 2018.3 换行/空行也计算在代码行数中，导致超过80行

**Comment by XenoAmess** [comment]
1. 空行不该算吗
2. 80行的垃圾规矩还真有人遵守吗

**Comment by imalvisc** [comment]
> 1. 空行不该算吗
> 2. 80行的垃圾规矩还真有人遵守吗

规则说明有写着不包括空行

**Comment by XenoAmess** [comment]
![image](https://user-images.githubusercontent.com/17455337/126819910-0a6b069f-37df-4738-bb1a-02aaa442603b.png)
@imalvisc 
按照文本理解的话，我认为他的意思是需要计入空行。

**Comment by gujin520** [comment]
这个规定垃圾吗？这个有啥纠结的！！
1）统计过大量代码得出来的结论，90%以下的都是80行以内的。
2）人的记忆只有三屏，80行预计在两屏至两屏半之间。
3）强制大家在写长方法时，需要拆分主干逻辑和次要逻辑。
4）使大家有抽取公共方法的思维习惯。

**Comment by gujin520** [comment]
这个规定垃圾吗？这个有啥纠结的！！
1）统计过大量代码得出来的结论，90%以下的都是80行以内的。
2）人的记忆只有三屏，80行预计在两屏至两屏半之间。
3）强制大家在写长方法时，需要拆分主干逻辑和次要逻辑。
4）使大家有抽取公共方法的思维习惯。

**Comment by XenoAmess** [comment]
@gujin520
对于 1）那么剩下10%的 如果是刚需 怎么办？

特别是一些领域相关的，比如涉及语法解析，或者复杂自动机，这种天然就要几百行，拆出来就有可能会导致性能降低，你打算如何

对于 3）4） 并不是所有场景都能通过抽离公共方法，或者拆分逻辑的方式，无损失地拆出子函数。

举个例子，你现在用的组件中，有一小半，都含有超过80行的代码，你打算标记这些组件全部不合法吗？

**Comment by XenoAmess** [comment]
@gujin520

比如 你前司的著名作品fastjson，就包含这种我描述的领域相关的自动机

https://github.com/alibaba/fastjson/blob/master/src/main/java/com/alibaba/fastjson/parser/DefaultJSONParser.java#L186

这个函数是一个400多行的json自动机

@wenshao 你觉得你这个代码写的不符合规范，无法维护吗？
