### ISSUE TITLE
程序员奈何为难程序员。。

### ISSUE THREAD

**Issue by 15563988825** [alibaba/p3c#836]
都是为了KPI而已
![image](https://user-images.githubusercontent.com/4360198/124340903-2cc77a00-dbeb-11eb-95bb-bc1718adfcb3.png)

**Comment by iankingh** [comment]
激烈碰撞后才能写出好代码？？

**Comment by nickxin** [comment]
不好安装

**Comment by ztrue-zn** [comment]
差点笑岔气

**Comment by XenoAmess** [comment]
当你经历了工友写出一坨屎后跑路了这种屌事之后，你会有别的想法

特别是如果跑路工友的屎由你负责接手

……然后，当你知道那个傻逼工友是跑路去了阿里的时候

你会对这个世界的魔幻程度有更深的认知
