### ISSUE TITLE
请问有支持kotlin的计划吗

### ISSUE THREAD

**Issue by iVixiv** [alibaba/p3c#84]
Android项目已经大规模向Kotlin转移,体验了一下插件,感觉非常好希望可以支持.kt

**Comment by git-xuhao** [comment]
目前也正在熟悉Kotlin中。。。

**Comment by wangxufire** [comment]
这是java的code style，其他语言不应该加进来

**Comment by cl123456789123456789** [comment]
希望有人带带我

**Comment by youngxhui** [comment]
@wangxufire 但是kotlin和java完全兼容而且规范很相似

**Comment by wangxufire** [comment]
@youngxhui  这个我知道，我是说要加也是开另一个仓库比较好，不应该混在一起，也不应该java、kotlin混编

**Comment by fw8899** [comment]
Duplicated with issue #19
