### ISSUE TITLE
跪求Eclipse拥有与idea一样的更新频率待遇。

### ISSUE THREAD

**Issue by z875479694h** [alibaba/p3c#840]
跪求Eclipse拥有与idea一样的更新频率待遇。

**Comment by XenoAmess** [comment]
……eclipse……如果不是eclipse实在烂 谁会转用idea呢

**Comment by xufanchn** [comment]
正经人谁用Eclipse啊，哪怕idea社区版也比那玩意儿强的多

**Comment by xuantan** [comment]
你好，感谢反馈，由于维护者的精力投入问题没办法保证Eclipse的更新频率，请谅解。
