### ISSUE TITLE
使用到标记为过时的字段时 无法忽略该条规则

### ISSUE THREAD

**Issue by guohui-ma** [alibaba/p3c#843]
## 规约原文
不能使用过时的类或方法。
## 问题描述
无法忽略掉当前规则。
## 修改建议
希望能够对使用了过时方法和字段的场合，能够忽略掉这条规约的检查。

**Comment by PasseRR** [comment]
https://github.com/alibaba/p3c/blob/d10884c15f569db542151de8b647d0ed93b42533/p3c-gitbook/%E7%BC%96%E7%A8%8B%E8%A7%84%E7%BA%A6/OOP%E8%A7%84%E8%8C%83.md 过时规约应该是强制的 不能忽略

**Comment by xuantan** [comment]
你好，参考楼上的回复。
