### ISSUE TITLE
LowerCamelCaseVariableNamingRule 对专有名词缩写检测会判定为不符合驼峰规则

### ISSUE THREAD

**Issue by SureEdding** [alibaba/p3c#846]
规则 
4 [Mandatory] Method names, parameter names, member variable names, and local variable names should be written in lowerCamelCase. Positive example: localValue / getHttpMessage() / inputUserId

的实现类
**LowerCamelCaseVariableNamingRule** 

`
private Pattern pattern = Pattern.compile("^[a-z][a-z0-9]*([A-Z][a-z0-9]+)*(DO|DTO|VO|DAO|BO|DOList|DTOList|VOList|DAOList|BOList|X|Y|Z|UDF|UDAF|[A-Z])?$");

`

LowerCamelCaseVariableNamingRule 规则中
驼峰 + DO、DTO、DTOList 类似的结尾，才是符合规范的
但是如果命名中带有一些专有名词的缩写，比如 TV、ES、JSON 类似的命名
也会被判定为不符合驼峰规范。

这种情况我尝试去修改正则，会发现“专有名词” 和 “驼峰大写单词” 之间边界是没办法判断的。
只能去补充一些常用的专有名词表，才能实现。
这个大家有什么建议或者想法吗？

**Comment by xuantan** [comment]
你好，由于专有名词无法穷举，当前我们的建议是你可以按照自己的情况去维护个人的专有名词表。

**Comment by hiling** [comment]
> 

能否把专有名词表做成配置？

**Comment by zqq90** [comment]
@hiling 
FYI #556
