### ISSUE TITLE
请问编码规约能提供原文件吗

### ISSUE THREAD

**Issue by IcebergXTY** [alibaba/p3c#847]
我们想要基于阿里的规范出一套内部的规范，但是有一部分历史原因导致的编码习惯跟阿里规约有点不一样，需要修改一下再使用，但是PDF改起来太麻烦了。仓库里有个p3c-gitbook文件夹，也很久没更新了。
既然PDF都已经开源了，可以顺便把生成PDF的原文件也开源吗 😁

**Comment by xuantan** [comment]
@dyrone 看下

**Comment by dyrone** [comment]
@IcebergXTY  

感谢你的建议，目前新的规约内容正在整理中， 届时我们将在项目中的[git-book](https://github.com/alibaba/p3c/tree/master/p3c-gitbook)中进行更新.

Thanks for the advice. 

Currently, we are working on the new release of guidelines, we will update the corresponding [git-book](https://github.com/alibaba/p3c/tree/master/p3c-gitbook) when we finished this iteration.

**Comment by KerwinAusten** [comment]
> 感谢你的建议，目前新的规约内容正在整理中， 届时我们将在项目中的[git-book](https://github.com/alibaba/p3c/tree/master/p3c-gitbook)中进行更新.
> 
> Thanks for the advice.
> 
> Currently, we are working on the new release of guidelines, we will update the corresponding [git-book](https://github.com/alibaba/p3c/tree/master/p3c-gitbook) when we finished this iteration.

@dyrone Hello, is there any progress on gitbook?

**Comment by dyrone** [comment]
https://github.com/dyrone/java_coding_guidelines

基于adoc， 你看下是否有帮助，但是因为存在更新延迟，可能内容有略微差异

谢谢

**Comment by KerwinAusten** [comment]
@dyrone 你好，页面404。是不是我没有权限查看

**Comment by dyrone** [comment]
@IcebergXTY 已调整为public
