### ISSUE TITLE
eclipse插件在使用过程中出现异常

### ISSUE THREAD

**Issue by yespens** [alibaba/p3c#849]
在扫描到实例化对象调用静态方法或变量的时候会出现:
An internal error occurred during: "P3C Code Analysis".
message must not be null

测试代码:
	public static void demo() {
		Calendar calendarEnd = new GregorianCalendar();
		calendarEnd.set(calendarEnd.MONTH, 11);
	}

**Comment by huailide** [comment]
I've got the same problem.
Eclipse info:
Eclipse IDE for Enterprise Java Developers (includes Incubating components)

Version: 2020-12 (4.18.0)
Build id: 20201210-1552

**Comment by xuantan** [comment]
@imu2008 看下

**Comment by imu2008** [comment]
@yespens 换IDEA扫码试下是否同样会报错呢
