### ISSUE TITLE
wrong tag 'date'

### ISSUE THREAD

**Issue by zeromem** [alibaba/p3c#85]
自动提取得到的模版
/**
 *
 * @author ***
 * @date 2017/9/26
 */

idea提示 wrong tag 'date'

**Comment by SeanCai** [comment]
@zeromem 下次发版会自动添加date为自定义标签，另外请使用小写的date哈

**Comment by SeanCai** [comment]
https://github.com/alibaba/p3c/issues/95
看这里

**Comment by plummer2013** [comment]
添加date为自定义标签后，在Ctrl+Q打开的Quick Documentation view里看不到 date标签信息，这个有解决办法吗？

**Comment by dvsv2** [comment]
想请教下自定义标签怎么加 我自己写的插件也遇到了这个问题 感谢 @SeanCai

**Comment by zjhpure** [comment]
同样想请教下自定义标签怎么加，
/**
 * @description
 * @author pure
 * @date 18-6-5 下午11:17
 */ 
idea总是提示description和date是错误标签
感谢 @SeanCai

**Comment by wshidaijingshen** [comment]
javaDoc 官方仅支持有限的几个标签，用于自动生成 文档的。一般人用不到。

https://www.oracle.com/technical-resources/articles/java/javadoc-tool.html#orderoftags

捉襟见肘。


解决： 光标移动到 自定义tag上，Alt enter ---> add as custom tag 即可 

![image](https://github.com/alibaba/p3c/assets/34682234/8e9517f7-5d15-478a-816a-942f817837ca)
