### ISSUE TITLE
eclipse 插件包错 The currently displayed page contains invalid values.

### ISSUE THREAD

**Issue by fc88804DOTcn** [alibaba/p3c#850]
**Describe the bug**
报错：The currently displayed page contains invalid values. 

**To Reproduce**
1.安装插件
2. Click on 'window'
3. Click on 'preferrnces'
4. 3. Click on 'Alibaba Code Analysis'
5. See error

**Expected behavior**
spring tools suite 安装完插件后，依次打开 window==>>preferrnces==>>Alibaba Code Analysis 报错：The currently displayed page contains invalid values. 不同机器出现不同的页面效果，但都报错。有一天机器在右侧展示了部分代码规约。

**Screenshots**
![image](https://user-images.githubusercontent.com/59227215/129992889-787246b6-939d-4581-8aec-c08078a2029f.png)

**Desktop (please complete the following information):**
 - OS: Window 10
 - IDE: Spring Tool Suite 4 
 - Version: Version: 4.9.0.RELEASE

**Additional context**
代码正常交验。只是有的机器上有概率打开window就报该错误/打开preferrnces/手动点击Alibaba Code Analysis 触发该错误。

**Comment by xuantan** [comment]
@imu2008 看下

**Comment by imu2008** [comment]
@fc88804DOTcn 建议先用原生的eclipse版本试试，未做过sts的兼容性测试

**Comment by fc88804DOTcn** [comment]
原生eclipse同样出错，win&fedora都是这个错误，现在没有在用插件。有书。

**Comment by fc88804DOTcn** [comment]
> 原生eclipse同样出错，win&fedora都是这个错误，现在没有在用插件。有书。



> @fc88804DOTcn 建议先用原生的eclipse版本试试，未做过sts的兼容性测试

原生eclipse同样出错，win&fedora都是这个错误，现在没有在用插件。有书。

**Comment by fc88804DOTcn** [comment]
@imu2008

**Comment by imu2008** [comment]
@fc88804DOTcn 换IDEA吧...eclipse插件可能快要退出舞台了

**Comment by fc88804DOTcn** [comment]
谢啦，我就还是按照习惯好了。eclipse我会一直用滴

**Comment by imu2008** [comment]
@fc88804DOTcn 赞，那你也学习下eclipse的插件开发，争取也参与到插件维护，哈哈

**Comment by fc88804DOTcn** [comment]
谢谢你啦。
