### ISSUE TITLE
eclipse-codestyle.xml

### ISSUE THREAD

**Issue by AncientFairy** [alibaba/p3c#852]
## 规约原文
```xml
<setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_for_parameter" value="insert"/>
```
![IDEA中的注释换行前](https://user-images.githubusercontent.com/25677587/132077945-077e3432-db8d-4659-be83-581ad2adf22c.png)

## 问题描述
432行 和IDEA保持一致，注释换行
## 修改建议
```
<setting id="org.eclipse.jdt.core.formatter.comment.insert_new_line_for_parameter" value="do not insert"/>
```
![IDEA中的注释换行](https://user-images.githubusercontent.com/25677587/132077924-4ea2ea17-a15b-4ae5-807d-4cd40c1771b6.png)

**Comment by xuantan** [comment]
@imu2008 看下

**Comment by imu2008** [comment]
@AncientFairy tks.
