### ISSUE TITLE
A problem occurred configuring project ':p3c-common'

### ISSUE THREAD

**Issue by xuruichao** [alibaba/p3c#855]
你好！
我再执行 ../gradlew clean buildPlguin时报错

错误内容：
A problem occurred configuring project ':p3c-common'. > Could not find matching constructor for: org.gradle.api.publish.ivy.internal.publisher.IvyDescriptorFileGenerator(org.gradle.api.publish.ivy.internal.publication.DefaultIvyPublicationIdentity)

新拉的代码没做过改动，辛苦告知如何解决谢谢

**Comment by lkl22** [comment]
碰到相同的问题,通过升级 `id "org.jetbrains.intellij" version '0.4.5'` 到 `id "org.jetbrains.intellij" version '0.4.21'` 解决.

参考fork的工程:
[https://github.com/BlankLun/p3c](https://github.com/BlankLun/p3c)

**Comment by xuruichao** [comment]
gradle的版本降级到4.9也可以解决

**Comment by xuantan** [comment]
你好，参考楼上的回复。
