### ISSUE TITLE
怎么自动生成方法注释？插件能否实现这个功能

### ISSUE THREAD

**Issue by kongde7** [alibaba/p3c#865]
## 规约原文
1. 【强制】类、类属性、类方法的注释必须使用 Javadoc 规范。
1. 【强制】所有的类都必须添加创建者和创建日期。

## 问题
怎么样能实现自动生成 Javadoc 规范的方法注释？类的上方能自动生成创建者和创建日期吗？目前采用的是手动复制后修改的方式。

## 建议
IDEA代码检查插件能否增加在方法或类的上方自动生成注释的功能？

**Comment by XenoAmess** [comment]
你可以尝试maven-javadoc-plugin的fix goal

**Comment by xuantan** [comment]
见上。
