### ISSUE TITLE
p3c-pmd能不能出一个sonar版本的插件

### ISSUE THREAD

**Issue by bestv5** [alibaba/p3c#867]
p3c-pmd能不能出一个sonar版本的插件？

**Comment by XenoAmess** [comment]
sonar不能连pmd？

**Comment by bestv5** [comment]
> sonar不能连pmd？

我的意思是出一个sonar插件。用p3c规则扫描代码

**Comment by XenoAmess** [comment]
可是p3c是pmd啊 sonar应该有pmd插件 配置上这边的依赖然后配上规则不就好了？

**Comment by bestv5** [comment]
> 可是p3c是pmd啊 sonar应该有pmd插件 配置上这边的依赖然后配上规则不就好了？

你的意思是把pmd插件源码，配上p3c的依赖，然后再配置下规则？

**Comment by xuantan** [comment]
暂时还没有此计划，可以自己按照sonar文档封装一个。
