### ISSUE TITLE
p3c-pmd 怎么用？

### ISSUE THREAD

**Issue by mofadeyunduo** [alibaba/p3c#875]
就给了一个 maven 的 dependency，不太会用，查了 pmd 文档也不会用，有完整的 demo 吗？

**Comment by XenoAmess** [comment]
https://github.com/alibaba/p3c/blob/master/p3c-pmd/pom.xml#L111
至
https://github.com/alibaba/p3c/blob/master/p3c-pmd/pom.xml#L150

**Comment by XenoAmess** [comment]
给你梳理一下关系
maven-pmd-plugin是一个maven插件，用于在maven构建过程中使用pmd检测代码
pmd是一个检测框架，有检测器框架和样例规则
p3c-pmd是基于pmd框架提供的功能开发的检测工具包
所以逻辑上是maven运行maven-pmd-plugin，maven-pmd-plugin运行pmd，pmd使用p3c-pmd的规则检测代码
大致上是这样
上述的几个轮子如果感兴趣自己去联系，他们人都挺好说话的。

**Comment by mofadeyunduo** [comment]
感谢楼上，现在懂了

**Comment by gaoyn-cn** [comment]
> 给你梳理一下关系 maven-pmd-plugin是一个maven插件，用于在maven构建过程中使用pmd检测代码 pmd是一个检测框架，有检测器框架和样例规则 p3c-pmd是基于pmd框架提供的功能开发的检测工具包 所以逻辑上是maven运行maven-pmd-plugin，maven-pmd-plugin运行pmd，pmd使用p3c-pmd的规则检测代码 大致上是这样 上述的几个轮子如果感兴趣自己去联系，他们人都挺好说话的。


idea上的 Alibaba Java Coding Guidelines  插件与 p3c 是什么关系呢？
