### ISSUE TITLE
Gradle怎么像maven一样排除FixClassTypeResolver

### ISSUE THREAD

**Issue by lopoZ** [alibaba/p3c#886]
maven可以排除这个类
![image](https://user-images.githubusercontent.com/63772714/158331832-f080377a-d7e5-4d14-ac0f-eb676d24d086.png)
gradle怎么排除
![image](https://user-images.githubusercontent.com/63772714/158332032-62ab9755-1304-4ec3-9f66-5b312d773c40.png)

**Comment by XenoAmess** [comment]
你要清楚 maven里这么配 是在pmd-maven-plugin的configuration里， 这是pmd-maven-plugin的配置，不是这个项目的配置

**Comment by XenoAmess** [comment]
gradle里有没有相应的这种配置，你应该询问做pmd gradle插件的人

**Comment by XenoAmess** [comment]
p3c是pmd的插件，pmd-maven-plugin是maven的插件，pmd-maven-plugin使用pmd，加载了pmd的插件p3c.
是这样一个逻辑。
gradle那边也是类似的逻辑，虽然我不知道gradle那边那个插件叫什么。

**Comment by lopoZ** [comment]
> 

是的，我的意思是我想在gradle中实现打包检测，像maven一样，我需要排除这个类

**Comment by XenoAmess** [comment]
> 是的，我的意思是我想在gradle中实现打包检测，像maven一样，我需要排除这个类

我对gradle一点兴趣也没有 但是这个或许能帮你 https://stackoverflow.com/questions/32247190/pmd-exclude-pattern-with-gradle

**Comment by lopoZ** [comment]
> > 是的，我的意思是我想在gradle中实现打包检测，像maven一样，我需要排除这个类
> 
> 我对gradle一点兴趣也没有 但是这个或许能帮你 https://stackoverflow.com/questions/32247190/pmd-exclude-pattern-with-gradle
> 
> ```
> pmd {
>     sourceSets = [ project.sourceSets.main ]
>     ruleSetFiles = rootProject.files("codequality/pmd-ruleset.xml")
>     ruleSets = []
> 
>     pmdMain {
>         excludes = [
>                 '**/Application.*',
>                 '**/jivesoftware/.*'
>         ]
>     }
> }
> ```
> 
> 因为gradle就像一坨屎 所以我也不确定它这个pmd跟你用的 是不是同一个gradle pmd插件 不过如果真的是的话 或许可以解决你的问题

谢谢，我试了应该是不行，这个只能排除项目中的类，我决定换个方式去实现我的规则

**Comment by XenoAmess** [comment]
> > > 是的，我的意思是我想在gradle中实现打包检测，像maven一样，我需要排除这个类
> > 
> > 
> > 我对gradle一点兴趣也没有 但是这个或许能帮你 https://stackoverflow.com/questions/32247190/pmd-exclude-pattern-with-gradle
> > ```
> > pmd {
> >     sourceSets = [ project.sourceSets.main ]
> >     ruleSetFiles = rootProject.files("codequality/pmd-ruleset.xml")
> >     ruleSets = []
> > 
> >     pmdMain {
> >         excludes = [
> >                 '**/Application.*',
> >                 '**/jivesoftware/.*'
> >         ]
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 因为gradle就像一坨屎 所以我也不确定它这个pmd跟你用的 是不是同一个gradle pmd插件 不过如果真的是的话 或许可以解决你的问题
> 
> 谢谢，我试了应该是不行，这个只能排除项目中的类，我决定换个方式去实现我的规则

我开始感到有点好奇为什么这个类会造成影响 并且必须被排除掉了。
或许在TPM版的下个版本我会着手解决这个问题。

**Comment by lopoZ** [comment]
> > > > 是的，我的意思是我想在gradle中实现打包检测，像maven一样，我需要排除这个类
> > > 
> > > 
> > > 我对gradle一点兴趣也没有 但是这个或许能帮你 https://stackoverflow.com/questions/32247190/pmd-exclude-pattern-with-gradle
> > > ```
> > > pmd {
> > >     sourceSets = [ project.sourceSets.main ]
> > >     ruleSetFiles = rootProject.files("codequality/pmd-ruleset.xml")
> > >     ruleSets = []
> > > 
> > >     pmdMain {
> > >         excludes = [
> > >                 '**/Application.*',
> > >                 '**/jivesoftware/.*'
> > >         ]
> > >     }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 因为gradle就像一坨屎 所以我也不确定它这个pmd跟你用的 是不是同一个gradle pmd插件 不过如果真的是的话 或许可以解决你的问题
> > 
> > 
> > 谢谢，我试了应该是不行，这个只能排除项目中的类，我决定换个方式去实现我的规则
> 
> 我开始感到有点好奇为什么这个类会造成影响 并且必须被排除掉了。 或许在TPM版的下个版本我会着手解决这个问题。
> 
> 但是现在暂时没空……

这个类会影响isAssignableFrom 导致无法判断
