### ISSUE TITLE
请问如何离线安装？

### ISSUE THREAD

**Issue by zhipfang** [alibaba/p3c#89]

**Comment by wonius** [comment]
eclipse吗？下载zip解压，安装插件时不填插件url，直接找到本地的文件夹

**Comment by SeanCai** [comment]
IDEA：https://github.com/alibaba/p3c/blob/master/idea-plugin/README_cn.md#通过下载安装包进行安装
Eclipse：https://p3c.alibaba.com/plugin/eclipse/update
