### ISSUE TITLE
just remove the shit QRcode!

### ISSUE THREAD

**Issue by xgqfrms-gildata** [alibaba/p3c#9]
# shit QRcode

> just remove the shit QRcode!

https://yq.aliyun.com/articles/215391

![image](https://user-images.githubusercontent.com/29531779/31041303-696cc4d4-a5c5-11e7-93e0-db6b18c726e5.png)

https://github.com/alibaba/p3c/blob/master/%E9%98%BF%E9%87%8C%E5%B7%B4%E5%B7%B4Java%E5%BC%80%E5%8F%91%E6%89%8B%E5%86%8C%EF%BC%88%E7%BB%88%E6%9E%81%E7%89%88%EF%BC%89.pdf

![image](https://user-images.githubusercontent.com/29531779/31041313-8a0457ac-a5c5-11e7-884d-63259bdc0724.png)

![image](https://user-images.githubusercontent.com/29531779/31041324-ea8f8ede-a5c5-11e7-8431-e1a5dd958ca0.png)

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/31041303-696cc4d4-a5c5-11e7-93e0-db6b18c726e5.png)

![image](https://user-images.githubusercontent.com/29531779/31041313-8a0457ac-a5c5-11e7-884d-63259bdc0724.png)

**Comment by yangguanbao** [comment]
感谢你支持《阿里巴巴Java开发手册》
