### ISSUE TITLE
Eclipse4.3安装成功，但是重启后右键看不到该插件，无法使用功能

### ISSUE THREAD

**Issue by wonius** [alibaba/p3c#90]
如题。
在eclispse installation中能看到该插件，说明已经安装成功了。
不手动删除该插件尝试重装，也会提示已安装。
重装后也是不行。
在线安装、本地安装都试过了。
OS: WIN7 64bit

**Comment by SeanCai** [comment]
@wonius 升级Eclipse启动用更多jdk到1.8试试

**Comment by zdshuguang** [comment]
我的安装了也找不到插件

**Comment by xll0617** [comment]
怎么解决了呀？

**Comment by wonius** [comment]
@xll0617 换IDEA了。4.3不支持，可以升级
