### ISSUE TITLE
添加自定义`ruleset`后，执行`mvn install`报错

### ISSUE THREAD

**Issue by iyanghui** [alibaba/p3c#902]
`p3c-pmd`版本：
```
  <groupId>com.alibaba.p3c</groupId>
  <artifactId>p3c-pmd</artifactId>
  <version>2.1.1</version>
```

新增一个`ruleset`后，`mvn test`可以通过，但执行`mvn install`报错如下：
![image](https://user-images.githubusercontent.com/23468391/166404363-4474634c-e9a8-498e-a425-61ad042f7356.png)

**Comment by iyanghui** [comment]
没认真看`maven-pmd-plugin`配置而引发的问题，已关闭。
> 插件依赖`p3c-pmd`的版本是2.0.1，本身不带`ali-extend.xml`。个人可先将带有`ali-extend.xml`的项目`install`，之后再添加`ali-extend.xml`并修改依赖版本就可以了

**Comment by Mengleijin** [comment]
@iyanghui 你好，我也遇到了同样的问题，请教一下你后续是怎样解决的呢？
  “个人可先将带有ali-extend.xml的项目install，之后再添加ali-extend.xml并修改依赖版本就可以了”可以描述详细一点吗？谢谢！
