### ISSUE TITLE
插件不维护了吗？

### ISSUE THREAD

**Issue by xiaohaoo** [alibaba/p3c#905]

**Comment by msj905** [comment]
咱们的规则怎么集成到sonarqube8.x版本中

**Comment by sandangjia** [comment]
> @xiaohaoo 可以考虑改为使用https://plugins.jetbrains.com/plugin/14109-alibaba-java-coding-guidelines-xenoamess-tpm-

这个插件2023版本安装后会导致输入中文卡顿，另外一些检测也不支持，最主要的是卡顿问题
