### ISSUE TITLE
现在这个Android studio不能用诶

### ISSUE THREAD

**Issue by haogg1996** [alibaba/p3c#92]
as安装之后不可以用，望能支持

**Comment by SeanCai** [comment]
@haogg1996 as什么版本的，buildNumber是多少

**Comment by haogg1996** [comment]
Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by haogg1996** [comment]
不好意思啊，昨天重启了好几次as都没生效，今天上班开机打开as发现竟然可以用了
