### ISSUE TITLE
可以配置指定语法吗，有些地方检测太过严格

### ISSUE THREAD

**Issue by followwwind** [alibaba/p3c#93]
比如if下单行语句非要大括号，官方java类单行也没带大括号的，而且这些不可选择配置，每次扫描标记还没法去掉

**Comment by sqgzy** [comment]
如果是idea，可以在Settings-Inspections的Ali-check中勾选

**Comment by yangguanbao** [comment]
对不起，我们也是官方的，感谢支持《阿里巴巴Java开发手册》
