### ISSUE TITLE
MyEclipse2017 插件安装成功但功能缺失

### ISSUE THREAD

**Issue by ddhjx** [alibaba/p3c#94]
MyEclipse2017 CI 1 插件安装成功，
![image](https://user-images.githubusercontent.com/11793390/31697719-e5d933a2-b3eb-11e7-91f5-73ff3cb5049d.png)
但是在工程、包、类上右键都没有相应的功能菜单，工具条上的按钮也是灰色的不可点击，只有在进入到具体类中功能才可用。

**Comment by xianshi122** [comment]
MyEclipse2015 同样问题。没有右键菜单。具体类中也没菜单

**Comment by tianzhuli** [comment]
MyEclipse 2013也是安装之后没有任何反应，没有相关的选项，是不支持还是本身的bug

**Comment by SeanCai** [comment]
@tianzhuli 看看Workspace目录下的日志有没有什么相关的堆栈信息哈

**Comment by ChoingHyun** [comment]
Eclipse Juno安装之后同样没有任何反应，没有相关的选项，不知道是什么问题

**Comment by SeanCai** [comment]
看看MyEclipse是不是已经集成了PMD相关的插件，感觉是因为net.sourceforge.pmd.lang.Language类冲突了
