### ISSUE TITLE
mysql 是否字段的数据类型为什么不用bit(1)?

### ISSUE THREAD

**Issue by jiandanfeng** [alibaba/p3c#946]
## 规约原文
mysql建表规约：表达是与否概念的字段， 必须使用 is_xxx 的方式命名， 数据类型是 unsigned tinyint（1 表示
是， 0 表示否）。
## 问题描述
tinyint unsigned 占用一个字节，可以表达0~255，可是是否概念，只需要一个bit位就能存储了，为什么要多浪费7个bit位来存储呢？
## 修改建议
使用bit(1)来存储是否概念的字段。

**Comment by zqq90** [comment]
无论存储 还是计算，都要考虑对齐问题的
对于一些引擎，按照字节的倍数对齐了，浪费点儿空间反而性能更高

**Comment by jiandanfeng** [comment]
最终发现：bit(1)也是占用一个字节（8位），并且使用bit有可能会出现意外错误，所以用tinyint(1)比较保险。[Why I Use TINYINT Columns Instead Of BIT Columns For Boolean Data In A MySQL Application](https://www.bennadel.com/blog/3845-why-i-use-tinyint-columns-instead-of-bit-columns-for-boolean-data-in-a-mysql-application.htm)
