### ISSUE TITLE
代码格式支持不是很好...

### ISSUE THREAD

**Issue by joker-fu** [alibaba/p3c#95]
...
        int a= 0;
        a=mTextVersion.getVisibility() == View.GONE?1:0;
        if(a==0) {return;}
        mTextVersion.setVisibility(View.VISIBLE);
...
今天早上集成测试了，不错的插件！专门写了这样一段来测试，没有自动提示。是我姿势不对，还望指教！
还有就是@date会警告，还有部分格式是否必须那样做，可以给个说明！

**Comment by SeanCai** [comment]
目前代码格式方面没有做检测，@date标签下一版会自动添加到 custom tag中，这样就不会警告了。另外标签全小写会好一点
