### ISSUE TITLE
强烈建议：加上代码修复功能。

### ISSUE THREAD

**Issue by NotSky** [alibaba/p3c#97]
对筛选出来不合规范的代码，提供单个或者批量修复功能。
例如if()语句缺少大括号这类问题，提供自动补全功能。

**Comment by SeanCai** [comment]
https://github.com/alibaba/p3c/blob/master/eclipse-plugin/README_cn.md#扫描结果
https://github.com/alibaba/p3c/blob/master/idea-plugin/README_cn.md#quickfix
