### ISSUE TITLE
界面需要更加友好

### ISSUE THREAD

**Issue by Lnybb** [alibaba/p3c#98]
<img width="910" alt="2017-10-18 11 33 52" src="https://user-images.githubusercontent.com/12817197/31699909-5aed2eac-b38b-11e7-848c-001a6183efd4.png">

滚轮是不是应该自动消失 :-O

**Comment by SeanCai** [comment]
@Lnybb 界面复用IDEA inspection results的面板 https://www.jetbrains.com/help/idea/running-inspection-by-name.html
